/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AiGatewayChatCompletionRequest,
  AiGatewayChatCompletionResponse,
  AiGatewayErrorResponse,
} from '../models/index';
import {
    AiGatewayChatCompletionRequestFromJSON,
    AiGatewayChatCompletionRequestToJSON,
    AiGatewayChatCompletionResponseFromJSON,
    AiGatewayChatCompletionResponseToJSON,
    AiGatewayErrorResponseFromJSON,
    AiGatewayErrorResponseToJSON,
} from '../models/index';

export interface AiGatewayV1ChatCompletionsPostRequest {
    aiGatewayChatCompletionRequest?: AiGatewayChatCompletionRequest;
}

/**
 * AiGatewayChatApi - interface
 * 
 * @export
 * @interface AiGatewayChatApiInterface
 */
export interface AiGatewayChatApiInterface {
    /**
     * Creates a chat completion using AI providers via Cloudflare AI Gateway. Supports BYOK (Bring Your Own Key) - pass your AI provider API key in the X-API-Key header.
     * @summary Create chat completion
     * @param {AiGatewayChatCompletionRequest} [aiGatewayChatCompletionRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiGatewayChatApiInterface
     */
    aiGatewayV1ChatCompletionsPostRaw(requestParameters: AiGatewayV1ChatCompletionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiGatewayChatCompletionResponse>>;

    /**
     * Creates a chat completion using AI providers via Cloudflare AI Gateway. Supports BYOK (Bring Your Own Key) - pass your AI provider API key in the X-API-Key header.
     * Create chat completion
     */
    aiGatewayV1ChatCompletionsPost(requestParameters: AiGatewayV1ChatCompletionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiGatewayChatCompletionResponse>;

}

/**
 * 
 */
export class AiGatewayChatApi extends runtime.BaseAPI implements AiGatewayChatApiInterface {

    /**
     * Creates a chat completion using AI providers via Cloudflare AI Gateway. Supports BYOK (Bring Your Own Key) - pass your AI provider API key in the X-API-Key header.
     * Create chat completion
     */
    async aiGatewayV1ChatCompletionsPostRaw(requestParameters: AiGatewayV1ChatCompletionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiGatewayChatCompletionResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ai-gateway/v1/chat/completions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiGatewayChatCompletionRequestToJSON(requestParameters['aiGatewayChatCompletionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiGatewayChatCompletionResponseFromJSON(jsonValue));
    }

    /**
     * Creates a chat completion using AI providers via Cloudflare AI Gateway. Supports BYOK (Bring Your Own Key) - pass your AI provider API key in the X-API-Key header.
     * Create chat completion
     */
    async aiGatewayV1ChatCompletionsPost(requestParameters: AiGatewayV1ChatCompletionsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiGatewayChatCompletionResponse> {
        const response = await this.aiGatewayV1ChatCompletionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
