/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AiGatewayHealthzResponse,
} from '../models/index';
import {
    AiGatewayHealthzResponseFromJSON,
    AiGatewayHealthzResponseToJSON,
} from '../models/index';

/**
 * AiGatewayHealthApi - interface
 * 
 * @export
 * @interface AiGatewayHealthApiInterface
 */
export interface AiGatewayHealthApiInterface {
    /**
     * Returns service health status
     * @summary Health check endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AiGatewayHealthApiInterface
     */
    aiGatewayV1HealthzGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiGatewayHealthzResponse>>;

    /**
     * Returns service health status
     * Health check endpoint
     */
    aiGatewayV1HealthzGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiGatewayHealthzResponse>;

}

/**
 * 
 */
export class AiGatewayHealthApi extends runtime.BaseAPI implements AiGatewayHealthApiInterface {

    /**
     * Returns service health status
     * Health check endpoint
     */
    async aiGatewayV1HealthzGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiGatewayHealthzResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ai-gateway/v1/healthz`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiGatewayHealthzResponseFromJSON(jsonValue));
    }

    /**
     * Returns service health status
     * Health check endpoint
     */
    async aiGatewayV1HealthzGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiGatewayHealthzResponse> {
        const response = await this.aiGatewayV1HealthzGetRaw(initOverrides);
        return await response.value();
    }

}
