/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AwardBadgeRequest,
  Badge,
  BadgeListResponse,
  CreateBadgeRequest,
  GamificationErrorResponse,
  UserBadge,
  UserBadgeListResponse,
} from '../models/index';
import {
    AwardBadgeRequestFromJSON,
    AwardBadgeRequestToJSON,
    BadgeFromJSON,
    BadgeToJSON,
    BadgeListResponseFromJSON,
    BadgeListResponseToJSON,
    CreateBadgeRequestFromJSON,
    CreateBadgeRequestToJSON,
    GamificationErrorResponseFromJSON,
    GamificationErrorResponseToJSON,
    UserBadgeFromJSON,
    UserBadgeToJSON,
    UserBadgeListResponseFromJSON,
    UserBadgeListResponseToJSON,
} from '../models/index';

export interface GamificationV1BadgesAwardPostRequest {
    awardBadgeRequest?: AwardBadgeRequest;
}

export interface GamificationV1BadgesGetRequest {
    category?: string;
}

export interface GamificationV1BadgesPostRequest {
    createBadgeRequest?: CreateBadgeRequest;
}

export interface GamificationV1BadgesUserGetRequest {
    userId: string;
}

/**
 * BadgesApi - interface
 * 
 * @export
 * @interface BadgesApiInterface
 */
export interface BadgesApiInterface {
    /**
     * Creates request options for gamificationV1BadgesAwardPost without sending the request
     * @param {AwardBadgeRequest} [awardBadgeRequest] 
     * @throws {RequiredError}
     * @memberof BadgesApiInterface
     */
    gamificationV1BadgesAwardPostRequestOpts(requestParameters: GamificationV1BadgesAwardPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Manually awards a badge to a user
     * @summary Award badge
     * @param {AwardBadgeRequest} [awardBadgeRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BadgesApiInterface
     */
    gamificationV1BadgesAwardPostRaw(requestParameters: GamificationV1BadgesAwardPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserBadge>>;

    /**
     * Manually awards a badge to a user
     * Award badge
     */
    gamificationV1BadgesAwardPost(requestParameters: GamificationV1BadgesAwardPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserBadge>;

    /**
     * Creates request options for gamificationV1BadgesGet without sending the request
     * @param {string} [category] 
     * @throws {RequiredError}
     * @memberof BadgesApiInterface
     */
    gamificationV1BadgesGetRequestOpts(requestParameters: GamificationV1BadgesGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns all badge definitions for this venture
     * @summary List badges
     * @param {string} [category] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BadgesApiInterface
     */
    gamificationV1BadgesGetRaw(requestParameters: GamificationV1BadgesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BadgeListResponse>>;

    /**
     * Returns all badge definitions for this venture
     * List badges
     */
    gamificationV1BadgesGet(requestParameters: GamificationV1BadgesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BadgeListResponse>;

    /**
     * Creates request options for gamificationV1BadgesPost without sending the request
     * @param {CreateBadgeRequest} [createBadgeRequest] 
     * @throws {RequiredError}
     * @memberof BadgesApiInterface
     */
    gamificationV1BadgesPostRequestOpts(requestParameters: GamificationV1BadgesPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new badge definition for this venture
     * @summary Create badge
     * @param {CreateBadgeRequest} [createBadgeRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BadgesApiInterface
     */
    gamificationV1BadgesPostRaw(requestParameters: GamificationV1BadgesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Badge>>;

    /**
     * Creates a new badge definition for this venture
     * Create badge
     */
    gamificationV1BadgesPost(requestParameters: GamificationV1BadgesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Badge>;

    /**
     * Creates request options for gamificationV1BadgesUserGet without sending the request
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof BadgesApiInterface
     */
    gamificationV1BadgesUserGetRequestOpts(requestParameters: GamificationV1BadgesUserGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns all badges earned by a user
     * @summary Get user badges
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BadgesApiInterface
     */
    gamificationV1BadgesUserGetRaw(requestParameters: GamificationV1BadgesUserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserBadgeListResponse>>;

    /**
     * Returns all badges earned by a user
     * Get user badges
     */
    gamificationV1BadgesUserGet(requestParameters: GamificationV1BadgesUserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserBadgeListResponse>;

}

/**
 * 
 */
export class BadgesApi extends runtime.BaseAPI implements BadgesApiInterface {

    /**
     * Creates request options for gamificationV1BadgesAwardPost without sending the request
     */
    async gamificationV1BadgesAwardPostRequestOpts(requestParameters: GamificationV1BadgesAwardPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/badges/award`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AwardBadgeRequestToJSON(requestParameters['awardBadgeRequest']),
        };
    }

    /**
     * Manually awards a badge to a user
     * Award badge
     */
    async gamificationV1BadgesAwardPostRaw(requestParameters: GamificationV1BadgesAwardPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserBadge>> {
        const requestOptions = await this.gamificationV1BadgesAwardPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserBadgeFromJSON(jsonValue));
    }

    /**
     * Manually awards a badge to a user
     * Award badge
     */
    async gamificationV1BadgesAwardPost(requestParameters: GamificationV1BadgesAwardPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserBadge> {
        const response = await this.gamificationV1BadgesAwardPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1BadgesGet without sending the request
     */
    async gamificationV1BadgesGetRequestOpts(requestParameters: GamificationV1BadgesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/badges`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all badge definitions for this venture
     * List badges
     */
    async gamificationV1BadgesGetRaw(requestParameters: GamificationV1BadgesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BadgeListResponse>> {
        const requestOptions = await this.gamificationV1BadgesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BadgeListResponseFromJSON(jsonValue));
    }

    /**
     * Returns all badge definitions for this venture
     * List badges
     */
    async gamificationV1BadgesGet(requestParameters: GamificationV1BadgesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BadgeListResponse> {
        const response = await this.gamificationV1BadgesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1BadgesPost without sending the request
     */
    async gamificationV1BadgesPostRequestOpts(requestParameters: GamificationV1BadgesPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/badges`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBadgeRequestToJSON(requestParameters['createBadgeRequest']),
        };
    }

    /**
     * Creates a new badge definition for this venture
     * Create badge
     */
    async gamificationV1BadgesPostRaw(requestParameters: GamificationV1BadgesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Badge>> {
        const requestOptions = await this.gamificationV1BadgesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BadgeFromJSON(jsonValue));
    }

    /**
     * Creates a new badge definition for this venture
     * Create badge
     */
    async gamificationV1BadgesPost(requestParameters: GamificationV1BadgesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Badge> {
        const response = await this.gamificationV1BadgesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1BadgesUserGet without sending the request
     */
    async gamificationV1BadgesUserGetRequestOpts(requestParameters: GamificationV1BadgesUserGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling gamificationV1BadgesUserGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/badges/user`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all badges earned by a user
     * Get user badges
     */
    async gamificationV1BadgesUserGetRaw(requestParameters: GamificationV1BadgesUserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserBadgeListResponse>> {
        const requestOptions = await this.gamificationV1BadgesUserGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserBadgeListResponseFromJSON(jsonValue));
    }

    /**
     * Returns all badges earned by a user
     * Get user badges
     */
    async gamificationV1BadgesUserGet(requestParameters: GamificationV1BadgesUserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserBadgeListResponse> {
        const response = await this.gamificationV1BadgesUserGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
