/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGoalRequest,
  GamificationErrorResponse,
  Goal,
  GoalListResponse,
  GoalWithPledges,
  UpdateGoalRequest,
} from '../models/index';
import {
    CreateGoalRequestFromJSON,
    CreateGoalRequestToJSON,
    GamificationErrorResponseFromJSON,
    GamificationErrorResponseToJSON,
    GoalFromJSON,
    GoalToJSON,
    GoalListResponseFromJSON,
    GoalListResponseToJSON,
    GoalWithPledgesFromJSON,
    GoalWithPledgesToJSON,
    UpdateGoalRequestFromJSON,
    UpdateGoalRequestToJSON,
} from '../models/index';

export interface GamificationV1GoalsGetRequest {
    userId: string;
    status?: GamificationV1GoalsGetStatusEnum;
}

export interface GamificationV1GoalsGoalIdGetRequest {
    goalId: string;
}

export interface GamificationV1GoalsGoalIdPatchRequest {
    goalId: string;
    updateGoalRequest?: UpdateGoalRequest;
}

export interface GamificationV1GoalsPostRequest {
    createGoalRequest?: CreateGoalRequest;
}

/**
 * GoalsApi - interface
 * 
 * @export
 * @interface GoalsApiInterface
 */
export interface GoalsApiInterface {
    /**
     * Creates request options for gamificationV1GoalsGet without sending the request
     * @param {string} userId 
     * @param {'active' | 'completed' | 'expired' | 'cancelled'} [status] 
     * @throws {RequiredError}
     * @memberof GoalsApiInterface
     */
    gamificationV1GoalsGetRequestOpts(requestParameters: GamificationV1GoalsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns goals for a user (optionally filtered by status)
     * @summary List goals
     * @param {string} userId 
     * @param {'active' | 'completed' | 'expired' | 'cancelled'} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApiInterface
     */
    gamificationV1GoalsGetRaw(requestParameters: GamificationV1GoalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoalListResponse>>;

    /**
     * Returns goals for a user (optionally filtered by status)
     * List goals
     */
    gamificationV1GoalsGet(requestParameters: GamificationV1GoalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoalListResponse>;

    /**
     * Creates request options for gamificationV1GoalsGoalIdGet without sending the request
     * @param {string} goalId 
     * @throws {RequiredError}
     * @memberof GoalsApiInterface
     */
    gamificationV1GoalsGoalIdGetRequestOpts(requestParameters: GamificationV1GoalsGoalIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a specific goal with all its pledges
     * @summary Get goal with pledges
     * @param {string} goalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApiInterface
     */
    gamificationV1GoalsGoalIdGetRaw(requestParameters: GamificationV1GoalsGoalIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoalWithPledges>>;

    /**
     * Returns a specific goal with all its pledges
     * Get goal with pledges
     */
    gamificationV1GoalsGoalIdGet(requestParameters: GamificationV1GoalsGoalIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoalWithPledges>;

    /**
     * Creates request options for gamificationV1GoalsGoalIdPatch without sending the request
     * @param {string} goalId 
     * @param {UpdateGoalRequest} [updateGoalRequest] 
     * @throws {RequiredError}
     * @memberof GoalsApiInterface
     */
    gamificationV1GoalsGoalIdPatchRequestOpts(requestParameters: GamificationV1GoalsGoalIdPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates goal progress or status
     * @summary Update goal
     * @param {string} goalId 
     * @param {UpdateGoalRequest} [updateGoalRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApiInterface
     */
    gamificationV1GoalsGoalIdPatchRaw(requestParameters: GamificationV1GoalsGoalIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>>;

    /**
     * Updates goal progress or status
     * Update goal
     */
    gamificationV1GoalsGoalIdPatch(requestParameters: GamificationV1GoalsGoalIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal>;

    /**
     * Creates request options for gamificationV1GoalsPost without sending the request
     * @param {CreateGoalRequest} [createGoalRequest] 
     * @throws {RequiredError}
     * @memberof GoalsApiInterface
     */
    gamificationV1GoalsPostRequestOpts(requestParameters: GamificationV1GoalsPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new goal for a user with optional reward
     * @summary Create goal
     * @param {CreateGoalRequest} [createGoalRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoalsApiInterface
     */
    gamificationV1GoalsPostRaw(requestParameters: GamificationV1GoalsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>>;

    /**
     * Creates a new goal for a user with optional reward
     * Create goal
     */
    gamificationV1GoalsPost(requestParameters: GamificationV1GoalsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal>;

}

/**
 * 
 */
export class GoalsApi extends runtime.BaseAPI implements GoalsApiInterface {

    /**
     * Creates request options for gamificationV1GoalsGet without sending the request
     */
    async gamificationV1GoalsGetRequestOpts(requestParameters: GamificationV1GoalsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling gamificationV1GoalsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/goals`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns goals for a user (optionally filtered by status)
     * List goals
     */
    async gamificationV1GoalsGetRaw(requestParameters: GamificationV1GoalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoalListResponse>> {
        const requestOptions = await this.gamificationV1GoalsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoalListResponseFromJSON(jsonValue));
    }

    /**
     * Returns goals for a user (optionally filtered by status)
     * List goals
     */
    async gamificationV1GoalsGet(requestParameters: GamificationV1GoalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoalListResponse> {
        const response = await this.gamificationV1GoalsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1GoalsGoalIdGet without sending the request
     */
    async gamificationV1GoalsGoalIdGetRequestOpts(requestParameters: GamificationV1GoalsGoalIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['goalId'] == null) {
            throw new runtime.RequiredError(
                'goalId',
                'Required parameter "goalId" was null or undefined when calling gamificationV1GoalsGoalIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/goals/{goalId}`;
        urlPath = urlPath.replace(`{${"goalId"}}`, encodeURIComponent(String(requestParameters['goalId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a specific goal with all its pledges
     * Get goal with pledges
     */
    async gamificationV1GoalsGoalIdGetRaw(requestParameters: GamificationV1GoalsGoalIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoalWithPledges>> {
        const requestOptions = await this.gamificationV1GoalsGoalIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoalWithPledgesFromJSON(jsonValue));
    }

    /**
     * Returns a specific goal with all its pledges
     * Get goal with pledges
     */
    async gamificationV1GoalsGoalIdGet(requestParameters: GamificationV1GoalsGoalIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoalWithPledges> {
        const response = await this.gamificationV1GoalsGoalIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1GoalsGoalIdPatch without sending the request
     */
    async gamificationV1GoalsGoalIdPatchRequestOpts(requestParameters: GamificationV1GoalsGoalIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['goalId'] == null) {
            throw new runtime.RequiredError(
                'goalId',
                'Required parameter "goalId" was null or undefined when calling gamificationV1GoalsGoalIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/goals/{goalId}`;
        urlPath = urlPath.replace(`{${"goalId"}}`, encodeURIComponent(String(requestParameters['goalId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGoalRequestToJSON(requestParameters['updateGoalRequest']),
        };
    }

    /**
     * Updates goal progress or status
     * Update goal
     */
    async gamificationV1GoalsGoalIdPatchRaw(requestParameters: GamificationV1GoalsGoalIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>> {
        const requestOptions = await this.gamificationV1GoalsGoalIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
    }

    /**
     * Updates goal progress or status
     * Update goal
     */
    async gamificationV1GoalsGoalIdPatch(requestParameters: GamificationV1GoalsGoalIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
        const response = await this.gamificationV1GoalsGoalIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1GoalsPost without sending the request
     */
    async gamificationV1GoalsPostRequestOpts(requestParameters: GamificationV1GoalsPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/goals`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGoalRequestToJSON(requestParameters['createGoalRequest']),
        };
    }

    /**
     * Creates a new goal for a user with optional reward
     * Create goal
     */
    async gamificationV1GoalsPostRaw(requestParameters: GamificationV1GoalsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Goal>> {
        const requestOptions = await this.gamificationV1GoalsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoalFromJSON(jsonValue));
    }

    /**
     * Creates a new goal for a user with optional reward
     * Create goal
     */
    async gamificationV1GoalsPost(requestParameters: GamificationV1GoalsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Goal> {
        const response = await this.gamificationV1GoalsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GamificationV1GoalsGetStatusEnum = {
    ACTIVE: 'active',
    COMPLETED: 'completed',
    EXPIRED: 'expired',
    CANCELLED: 'cancelled'
} as const;
export type GamificationV1GoalsGetStatusEnum = typeof GamificationV1GoalsGetStatusEnum[keyof typeof GamificationV1GoalsGetStatusEnum];
