/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateGroupRequest,
  Group,
  GroupListResponse,
  GroupsErrorResponse,
  UpdateGroupRequest,
} from '../models/index';
import {
    CreateGroupRequestFromJSON,
    CreateGroupRequestToJSON,
    GroupFromJSON,
    GroupToJSON,
    GroupListResponseFromJSON,
    GroupListResponseToJSON,
    GroupsErrorResponseFromJSON,
    GroupsErrorResponseToJSON,
    UpdateGroupRequestFromJSON,
    UpdateGroupRequestToJSON,
} from '../models/index';

export interface GroupsV1GroupsByExternalGetRequest {
    groupType: string;
    externalId: string;
}

export interface GroupsV1GroupsGetRequest {
    groupType?: string;
    limit?: number;
    offset?: number | null;
}

export interface GroupsV1GroupsGroupIdDeleteRequest {
    groupId: string;
}

export interface GroupsV1GroupsGroupIdGetRequest {
    groupId: string;
}

export interface GroupsV1GroupsGroupIdPatchRequest {
    groupId: string;
    updateGroupRequest?: UpdateGroupRequest;
}

export interface GroupsV1GroupsPostRequest {
    createGroupRequest?: CreateGroupRequest;
}

export interface GroupsV1GroupsSearchGetRequest {
    query?: string;
    groupType?: string;
    limit?: number;
    offset?: number | null;
}

/**
 * GroupsApi - interface
 * 
 * @export
 * @interface GroupsApiInterface
 */
export interface GroupsApiInterface {
    /**
     * Creates request options for groupsV1GroupsByExternalGet without sending the request
     * @param {string} groupType 
     * @param {string} externalId 
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsByExternalGetRequestOpts(requestParameters: GroupsV1GroupsByExternalGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a group by type and external ID
     * @summary Get group by external ID
     * @param {string} groupType 
     * @param {string} externalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsByExternalGetRaw(requestParameters: GroupsV1GroupsByExternalGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>>;

    /**
     * Returns a group by type and external ID
     * Get group by external ID
     */
    groupsV1GroupsByExternalGet(requestParameters: GroupsV1GroupsByExternalGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group>;

    /**
     * Creates request options for groupsV1GroupsGet without sending the request
     * @param {string} [groupType] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsGetRequestOpts(requestParameters: GroupsV1GroupsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns groups for this venture
     * @summary List groups
     * @param {string} [groupType] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsGetRaw(requestParameters: GroupsV1GroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupListResponse>>;

    /**
     * Returns groups for this venture
     * List groups
     */
    groupsV1GroupsGet(requestParameters: GroupsV1GroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupListResponse>;

    /**
     * Creates request options for groupsV1GroupsGroupIdDelete without sending the request
     * @param {string} groupId 
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsGroupIdDeleteRequestOpts(requestParameters: GroupsV1GroupsGroupIdDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Deletes a group
     * @summary Delete group
     * @param {string} groupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsGroupIdDeleteRaw(requestParameters: GroupsV1GroupsGroupIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a group
     * Delete group
     */
    groupsV1GroupsGroupIdDelete(requestParameters: GroupsV1GroupsGroupIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for groupsV1GroupsGroupIdGet without sending the request
     * @param {string} groupId 
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsGroupIdGetRequestOpts(requestParameters: GroupsV1GroupsGroupIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a group by ID
     * @summary Get group
     * @param {string} groupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsGroupIdGetRaw(requestParameters: GroupsV1GroupsGroupIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>>;

    /**
     * Returns a group by ID
     * Get group
     */
    groupsV1GroupsGroupIdGet(requestParameters: GroupsV1GroupsGroupIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group>;

    /**
     * Creates request options for groupsV1GroupsGroupIdPatch without sending the request
     * @param {string} groupId 
     * @param {UpdateGroupRequest} [updateGroupRequest] 
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsGroupIdPatchRequestOpts(requestParameters: GroupsV1GroupsGroupIdPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates a group
     * @summary Update group
     * @param {string} groupId 
     * @param {UpdateGroupRequest} [updateGroupRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsGroupIdPatchRaw(requestParameters: GroupsV1GroupsGroupIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>>;

    /**
     * Updates a group
     * Update group
     */
    groupsV1GroupsGroupIdPatch(requestParameters: GroupsV1GroupsGroupIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group>;

    /**
     * Creates request options for groupsV1GroupsPost without sending the request
     * @param {CreateGroupRequest} [createGroupRequest] 
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsPostRequestOpts(requestParameters: GroupsV1GroupsPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new group for this venture
     * @summary Create group
     * @param {CreateGroupRequest} [createGroupRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsPostRaw(requestParameters: GroupsV1GroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>>;

    /**
     * Creates a new group for this venture
     * Create group
     */
    groupsV1GroupsPost(requestParameters: GroupsV1GroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group>;

    /**
     * Creates request options for groupsV1GroupsSearchGet without sending the request
     * @param {string} [query] 
     * @param {string} [groupType] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsSearchGetRequestOpts(requestParameters: GroupsV1GroupsSearchGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Search for public/joinable groups
     * @summary Search public groups
     * @param {string} [query] 
     * @param {string} [groupType] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApiInterface
     */
    groupsV1GroupsSearchGetRaw(requestParameters: GroupsV1GroupsSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupListResponse>>;

    /**
     * Search for public/joinable groups
     * Search public groups
     */
    groupsV1GroupsSearchGet(requestParameters: GroupsV1GroupsSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupListResponse>;

}

/**
 * 
 */
export class GroupsApi extends runtime.BaseAPI implements GroupsApiInterface {

    /**
     * Creates request options for groupsV1GroupsByExternalGet without sending the request
     */
    async groupsV1GroupsByExternalGetRequestOpts(requestParameters: GroupsV1GroupsByExternalGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupType'] == null) {
            throw new runtime.RequiredError(
                'groupType',
                'Required parameter "groupType" was null or undefined when calling groupsV1GroupsByExternalGet().'
            );
        }

        if (requestParameters['externalId'] == null) {
            throw new runtime.RequiredError(
                'externalId',
                'Required parameter "externalId" was null or undefined when calling groupsV1GroupsByExternalGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['groupType'] != null) {
            queryParameters['groupType'] = requestParameters['groupType'];
        }

        if (requestParameters['externalId'] != null) {
            queryParameters['externalId'] = requestParameters['externalId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/groups/by-external`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a group by type and external ID
     * Get group by external ID
     */
    async groupsV1GroupsByExternalGetRaw(requestParameters: GroupsV1GroupsByExternalGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        const requestOptions = await this.groupsV1GroupsByExternalGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Returns a group by type and external ID
     * Get group by external ID
     */
    async groupsV1GroupsByExternalGet(requestParameters: GroupsV1GroupsByExternalGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.groupsV1GroupsByExternalGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for groupsV1GroupsGet without sending the request
     */
    async groupsV1GroupsGetRequestOpts(requestParameters: GroupsV1GroupsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['groupType'] != null) {
            queryParameters['groupType'] = requestParameters['groupType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/groups`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns groups for this venture
     * List groups
     */
    async groupsV1GroupsGetRaw(requestParameters: GroupsV1GroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupListResponse>> {
        const requestOptions = await this.groupsV1GroupsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupListResponseFromJSON(jsonValue));
    }

    /**
     * Returns groups for this venture
     * List groups
     */
    async groupsV1GroupsGet(requestParameters: GroupsV1GroupsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupListResponse> {
        const response = await this.groupsV1GroupsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for groupsV1GroupsGroupIdDelete without sending the request
     */
    async groupsV1GroupsGroupIdDeleteRequestOpts(requestParameters: GroupsV1GroupsGroupIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling groupsV1GroupsGroupIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/groups/{groupId}`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a group
     * Delete group
     */
    async groupsV1GroupsGroupIdDeleteRaw(requestParameters: GroupsV1GroupsGroupIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.groupsV1GroupsGroupIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a group
     * Delete group
     */
    async groupsV1GroupsGroupIdDelete(requestParameters: GroupsV1GroupsGroupIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.groupsV1GroupsGroupIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for groupsV1GroupsGroupIdGet without sending the request
     */
    async groupsV1GroupsGroupIdGetRequestOpts(requestParameters: GroupsV1GroupsGroupIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling groupsV1GroupsGroupIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/groups/{groupId}`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a group by ID
     * Get group
     */
    async groupsV1GroupsGroupIdGetRaw(requestParameters: GroupsV1GroupsGroupIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        const requestOptions = await this.groupsV1GroupsGroupIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Returns a group by ID
     * Get group
     */
    async groupsV1GroupsGroupIdGet(requestParameters: GroupsV1GroupsGroupIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.groupsV1GroupsGroupIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for groupsV1GroupsGroupIdPatch without sending the request
     */
    async groupsV1GroupsGroupIdPatchRequestOpts(requestParameters: GroupsV1GroupsGroupIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling groupsV1GroupsGroupIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/groups/{groupId}`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGroupRequestToJSON(requestParameters['updateGroupRequest']),
        };
    }

    /**
     * Updates a group
     * Update group
     */
    async groupsV1GroupsGroupIdPatchRaw(requestParameters: GroupsV1GroupsGroupIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        const requestOptions = await this.groupsV1GroupsGroupIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Updates a group
     * Update group
     */
    async groupsV1GroupsGroupIdPatch(requestParameters: GroupsV1GroupsGroupIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.groupsV1GroupsGroupIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for groupsV1GroupsPost without sending the request
     */
    async groupsV1GroupsPostRequestOpts(requestParameters: GroupsV1GroupsPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/groups`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGroupRequestToJSON(requestParameters['createGroupRequest']),
        };
    }

    /**
     * Creates a new group for this venture
     * Create group
     */
    async groupsV1GroupsPostRaw(requestParameters: GroupsV1GroupsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        const requestOptions = await this.groupsV1GroupsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Creates a new group for this venture
     * Create group
     */
    async groupsV1GroupsPost(requestParameters: GroupsV1GroupsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.groupsV1GroupsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for groupsV1GroupsSearchGet without sending the request
     */
    async groupsV1GroupsSearchGetRequestOpts(requestParameters: GroupsV1GroupsSearchGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['groupType'] != null) {
            queryParameters['groupType'] = requestParameters['groupType'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/groups/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search for public/joinable groups
     * Search public groups
     */
    async groupsV1GroupsSearchGetRaw(requestParameters: GroupsV1GroupsSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupListResponse>> {
        const requestOptions = await this.groupsV1GroupsSearchGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupListResponseFromJSON(jsonValue));
    }

    /**
     * Search for public/joinable groups
     * Search public groups
     */
    async groupsV1GroupsSearchGet(requestParameters: GroupsV1GroupsSearchGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupListResponse> {
        const response = await this.groupsV1GroupsSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
