/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HelloWorldErrorResponse,
  HelloWorldProtectedResponse,
} from '../models/index';
import {
    HelloWorldErrorResponseFromJSON,
    HelloWorldErrorResponseToJSON,
    HelloWorldProtectedResponseFromJSON,
    HelloWorldProtectedResponseToJSON,
} from '../models/index';

/**
 * HelloWorldAuthApi - interface
 * 
 * @export
 * @interface HelloWorldAuthApiInterface
 */
export interface HelloWorldAuthApiInterface {
    /**
     * Demonstrates authentication - requires valid user JWT from Supabase
     * @summary Protected endpoint (requires authentication)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HelloWorldAuthApiInterface
     */
    helloWorldV1ProtectedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HelloWorldProtectedResponse>>;

    /**
     * Demonstrates authentication - requires valid user JWT from Supabase
     * Protected endpoint (requires authentication)
     */
    helloWorldV1ProtectedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HelloWorldProtectedResponse>;

}

/**
 * 
 */
export class HelloWorldAuthApi extends runtime.BaseAPI implements HelloWorldAuthApiInterface {

    /**
     * Demonstrates authentication - requires valid user JWT from Supabase
     * Protected endpoint (requires authentication)
     */
    async helloWorldV1ProtectedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HelloWorldProtectedResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hello-world/v1/protected`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HelloWorldProtectedResponseFromJSON(jsonValue));
    }

    /**
     * Demonstrates authentication - requires valid user JWT from Supabase
     * Protected endpoint (requires authentication)
     */
    async helloWorldV1ProtectedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HelloWorldProtectedResponse> {
        const response = await this.helloWorldV1ProtectedGetRaw(initOverrides);
        return await response.value();
    }

}
