/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HelloWorldCreateMessageRequest,
  HelloWorldCreateMessageResponse,
  HelloWorldErrorResponse,
} from '../models/index';
import {
    HelloWorldCreateMessageRequestFromJSON,
    HelloWorldCreateMessageRequestToJSON,
    HelloWorldCreateMessageResponseFromJSON,
    HelloWorldCreateMessageResponseToJSON,
    HelloWorldErrorResponseFromJSON,
    HelloWorldErrorResponseToJSON,
} from '../models/index';

export interface HelloWorldV1MessagesPostRequest {
    helloWorldCreateMessageRequest?: HelloWorldCreateMessageRequest;
}

/**
 * HelloWorldMessagesApi - interface
 * 
 * @export
 * @interface HelloWorldMessagesApiInterface
 */
export interface HelloWorldMessagesApiInterface {
    /**
     * Creates a new message
     * @summary Create message
     * @param {HelloWorldCreateMessageRequest} [helloWorldCreateMessageRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HelloWorldMessagesApiInterface
     */
    helloWorldV1MessagesPostRaw(requestParameters: HelloWorldV1MessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HelloWorldCreateMessageResponse>>;

    /**
     * Creates a new message
     * Create message
     */
    helloWorldV1MessagesPost(requestParameters: HelloWorldV1MessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HelloWorldCreateMessageResponse>;

}

/**
 * 
 */
export class HelloWorldMessagesApi extends runtime.BaseAPI implements HelloWorldMessagesApiInterface {

    /**
     * Creates a new message
     * Create message
     */
    async helloWorldV1MessagesPostRaw(requestParameters: HelloWorldV1MessagesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HelloWorldCreateMessageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/hello-world/v1/messages`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HelloWorldCreateMessageRequestToJSON(requestParameters['helloWorldCreateMessageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HelloWorldCreateMessageResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new message
     * Create message
     */
    async helloWorldV1MessagesPost(requestParameters: HelloWorldV1MessagesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HelloWorldCreateMessageResponse> {
        const response = await this.helloWorldV1MessagesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
