/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GroupMembership,
  GroupsErrorResponse,
  GroupsV1GroupsGroupIdJoinRequestsPostRequest,
} from '../models/index';
import {
    GroupMembershipFromJSON,
    GroupMembershipToJSON,
    GroupsErrorResponseFromJSON,
    GroupsErrorResponseToJSON,
    GroupsV1GroupsGroupIdJoinRequestsPostRequestFromJSON,
    GroupsV1GroupsGroupIdJoinRequestsPostRequestToJSON,
} from '../models/index';

export interface GroupsV1GroupsGroupIdJoinRequestsPostOperationRequest {
    groupId: string;
    groupsV1GroupsGroupIdJoinRequestsPostRequest?: GroupsV1GroupsGroupIdJoinRequestsPostRequest;
}

/**
 * JoinRequestsApi - interface
 * 
 * @export
 * @interface JoinRequestsApiInterface
 */
export interface JoinRequestsApiInterface {
    /**
     * Creates request options for groupsV1GroupsGroupIdJoinRequestsPost without sending the request
     * @param {string} groupId 
     * @param {GroupsV1GroupsGroupIdJoinRequestsPostRequest} [groupsV1GroupsGroupIdJoinRequestsPostRequest] 
     * @throws {RequiredError}
     * @memberof JoinRequestsApiInterface
     */
    groupsV1GroupsGroupIdJoinRequestsPostRequestOpts(requestParameters: GroupsV1GroupsGroupIdJoinRequestsPostOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a pending membership for a user to join a group
     * @summary Request to join
     * @param {string} groupId 
     * @param {GroupsV1GroupsGroupIdJoinRequestsPostRequest} [groupsV1GroupsGroupIdJoinRequestsPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JoinRequestsApiInterface
     */
    groupsV1GroupsGroupIdJoinRequestsPostRaw(requestParameters: GroupsV1GroupsGroupIdJoinRequestsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupMembership>>;

    /**
     * Creates a pending membership for a user to join a group
     * Request to join
     */
    groupsV1GroupsGroupIdJoinRequestsPost(requestParameters: GroupsV1GroupsGroupIdJoinRequestsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupMembership>;

}

/**
 * 
 */
export class JoinRequestsApi extends runtime.BaseAPI implements JoinRequestsApiInterface {

    /**
     * Creates request options for groupsV1GroupsGroupIdJoinRequestsPost without sending the request
     */
    async groupsV1GroupsGroupIdJoinRequestsPostRequestOpts(requestParameters: GroupsV1GroupsGroupIdJoinRequestsPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling groupsV1GroupsGroupIdJoinRequestsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/groups/{groupId}/join-requests`;
        urlPath = urlPath.replace(`{${"groupId"}}`, encodeURIComponent(String(requestParameters['groupId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupsV1GroupsGroupIdJoinRequestsPostRequestToJSON(requestParameters['groupsV1GroupsGroupIdJoinRequestsPostRequest']),
        };
    }

    /**
     * Creates a pending membership for a user to join a group
     * Request to join
     */
    async groupsV1GroupsGroupIdJoinRequestsPostRaw(requestParameters: GroupsV1GroupsGroupIdJoinRequestsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupMembership>> {
        const requestOptions = await this.groupsV1GroupsGroupIdJoinRequestsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupMembershipFromJSON(jsonValue));
    }

    /**
     * Creates a pending membership for a user to join a group
     * Request to join
     */
    async groupsV1GroupsGroupIdJoinRequestsPost(requestParameters: GroupsV1GroupsGroupIdJoinRequestsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupMembership> {
        const response = await this.groupsV1GroupsGroupIdJoinRequestsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
