/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClaimManagedUserRequest,
  ClaimManagedUserResponse,
  CreateManagedUserRequest,
  CreateManagedUserResponse,
  ErrorResponse,
  GrantConsentRequest,
  GrantConsentResponse,
  LoginManagedUserRequest,
  LoginManagedUserResponse,
} from '../models/index';
import {
    ClaimManagedUserRequestFromJSON,
    ClaimManagedUserRequestToJSON,
    ClaimManagedUserResponseFromJSON,
    ClaimManagedUserResponseToJSON,
    CreateManagedUserRequestFromJSON,
    CreateManagedUserRequestToJSON,
    CreateManagedUserResponseFromJSON,
    CreateManagedUserResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GrantConsentRequestFromJSON,
    GrantConsentRequestToJSON,
    GrantConsentResponseFromJSON,
    GrantConsentResponseToJSON,
    LoginManagedUserRequestFromJSON,
    LoginManagedUserRequestToJSON,
    LoginManagedUserResponseFromJSON,
    LoginManagedUserResponseToJSON,
} from '../models/index';

export interface AuthV1ManagedUserClaimPostRequest {
    claimManagedUserRequest?: ClaimManagedUserRequest;
}

export interface AuthV1ManagedUserConsentPostRequest {
    grantConsentRequest?: GrantConsentRequest;
}

export interface AuthV1ManagedUserLoginPostRequest {
    loginManagedUserRequest?: LoginManagedUserRequest;
}

export interface AuthV1ManagedUserPostRequest {
    createManagedUserRequest?: CreateManagedUserRequest;
}

/**
 * ManagedAccountsApi - interface
 * 
 * @export
 * @interface ManagedAccountsApiInterface
 */
export interface ManagedAccountsApiInterface {
    /**
     * Creates request options for authV1ManagedUserClaimPost without sending the request
     * @param {ClaimManagedUserRequest} [claimManagedUserRequest] 
     * @throws {RequiredError}
     * @memberof ManagedAccountsApiInterface
     */
    authV1ManagedUserClaimPostRequestOpts(requestParameters: AuthV1ManagedUserClaimPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Add email and password to an existing managed user account, enabling independent login. All history (activities, data) is preserved. This is a public endpoint - no authentication required.
     * @summary Claim managed user account
     * @param {ClaimManagedUserRequest} [claimManagedUserRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagedAccountsApiInterface
     */
    authV1ManagedUserClaimPostRaw(requestParameters: AuthV1ManagedUserClaimPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClaimManagedUserResponse>>;

    /**
     * Add email and password to an existing managed user account, enabling independent login. All history (activities, data) is preserved. This is a public endpoint - no authentication required.
     * Claim managed user account
     */
    authV1ManagedUserClaimPost(requestParameters: AuthV1ManagedUserClaimPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClaimManagedUserResponse>;

    /**
     * Creates request options for authV1ManagedUserConsentPost without sending the request
     * @param {GrantConsentRequest} [grantConsentRequest] 
     * @throws {RequiredError}
     * @memberof ManagedAccountsApiInterface
     */
    authV1ManagedUserConsentPostRequestOpts(requestParameters: AuthV1ManagedUserConsentPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a parental consent record allowing the authenticated user (parent) to access the specified child account. Required for multi-child device sharing. Idempotent - safe to call if consent already exists.
     * @summary Grant parental consent for a managed child
     * @param {GrantConsentRequest} [grantConsentRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagedAccountsApiInterface
     */
    authV1ManagedUserConsentPostRaw(requestParameters: AuthV1ManagedUserConsentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrantConsentResponse>>;

    /**
     * Creates a parental consent record allowing the authenticated user (parent) to access the specified child account. Required for multi-child device sharing. Idempotent - safe to call if consent already exists.
     * Grant parental consent for a managed child
     */
    authV1ManagedUserConsentPost(requestParameters: AuthV1ManagedUserConsentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrantConsentResponse>;

    /**
     * Creates request options for authV1ManagedUserLoginPost without sending the request
     * @param {LoginManagedUserRequest} [loginManagedUserRequest] 
     * @throws {RequiredError}
     * @memberof ManagedAccountsApiInterface
     */
    authV1ManagedUserLoginPostRequestOpts(requestParameters: AuthV1ManagedUserLoginPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a session for a managed user (child without email/password). Requires parent authorization via Bearer token. Parent must have parental consent relationship with the managed user. Returns child JWT for multi-account device sharing.
     * @summary Login as managed user (requires parent authorization)
     * @param {LoginManagedUserRequest} [loginManagedUserRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagedAccountsApiInterface
     */
    authV1ManagedUserLoginPostRaw(requestParameters: AuthV1ManagedUserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginManagedUserResponse>>;

    /**
     * Creates a session for a managed user (child without email/password). Requires parent authorization via Bearer token. Parent must have parental consent relationship with the managed user. Returns child JWT for multi-account device sharing.
     * Login as managed user (requires parent authorization)
     */
    authV1ManagedUserLoginPost(requestParameters: AuthV1ManagedUserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginManagedUserResponse>;

    /**
     * Creates request options for authV1ManagedUserPost without sending the request
     * @param {CreateManagedUserRequest} [createManagedUserRequest] 
     * @throws {RequiredError}
     * @memberof ManagedAccountsApiInterface
     */
    authV1ManagedUserPostRequestOpts(requestParameters: AuthV1ManagedUserPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a managed user account without email/password. The user can participate in platform features but cannot log in until they claim their account. Requires service authentication (internal JWT).
     * @summary Create managed user account
     * @param {CreateManagedUserRequest} [createManagedUserRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagedAccountsApiInterface
     */
    authV1ManagedUserPostRaw(requestParameters: AuthV1ManagedUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateManagedUserResponse>>;

    /**
     * Create a managed user account without email/password. The user can participate in platform features but cannot log in until they claim their account. Requires service authentication (internal JWT).
     * Create managed user account
     */
    authV1ManagedUserPost(requestParameters: AuthV1ManagedUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateManagedUserResponse>;

}

/**
 * 
 */
export class ManagedAccountsApi extends runtime.BaseAPI implements ManagedAccountsApiInterface {

    /**
     * Creates request options for authV1ManagedUserClaimPost without sending the request
     */
    async authV1ManagedUserClaimPostRequestOpts(requestParameters: AuthV1ManagedUserClaimPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/v1/managed-user/claim`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClaimManagedUserRequestToJSON(requestParameters['claimManagedUserRequest']),
        };
    }

    /**
     * Add email and password to an existing managed user account, enabling independent login. All history (activities, data) is preserved. This is a public endpoint - no authentication required.
     * Claim managed user account
     */
    async authV1ManagedUserClaimPostRaw(requestParameters: AuthV1ManagedUserClaimPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClaimManagedUserResponse>> {
        const requestOptions = await this.authV1ManagedUserClaimPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClaimManagedUserResponseFromJSON(jsonValue));
    }

    /**
     * Add email and password to an existing managed user account, enabling independent login. All history (activities, data) is preserved. This is a public endpoint - no authentication required.
     * Claim managed user account
     */
    async authV1ManagedUserClaimPost(requestParameters: AuthV1ManagedUserClaimPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClaimManagedUserResponse> {
        const response = await this.authV1ManagedUserClaimPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authV1ManagedUserConsentPost without sending the request
     */
    async authV1ManagedUserConsentPostRequestOpts(requestParameters: AuthV1ManagedUserConsentPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/v1/managed-user/consent`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GrantConsentRequestToJSON(requestParameters['grantConsentRequest']),
        };
    }

    /**
     * Creates a parental consent record allowing the authenticated user (parent) to access the specified child account. Required for multi-child device sharing. Idempotent - safe to call if consent already exists.
     * Grant parental consent for a managed child
     */
    async authV1ManagedUserConsentPostRaw(requestParameters: AuthV1ManagedUserConsentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrantConsentResponse>> {
        const requestOptions = await this.authV1ManagedUserConsentPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrantConsentResponseFromJSON(jsonValue));
    }

    /**
     * Creates a parental consent record allowing the authenticated user (parent) to access the specified child account. Required for multi-child device sharing. Idempotent - safe to call if consent already exists.
     * Grant parental consent for a managed child
     */
    async authV1ManagedUserConsentPost(requestParameters: AuthV1ManagedUserConsentPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrantConsentResponse> {
        const response = await this.authV1ManagedUserConsentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authV1ManagedUserLoginPost without sending the request
     */
    async authV1ManagedUserLoginPostRequestOpts(requestParameters: AuthV1ManagedUserLoginPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/v1/managed-user/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginManagedUserRequestToJSON(requestParameters['loginManagedUserRequest']),
        };
    }

    /**
     * Creates a session for a managed user (child without email/password). Requires parent authorization via Bearer token. Parent must have parental consent relationship with the managed user. Returns child JWT for multi-account device sharing.
     * Login as managed user (requires parent authorization)
     */
    async authV1ManagedUserLoginPostRaw(requestParameters: AuthV1ManagedUserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginManagedUserResponse>> {
        const requestOptions = await this.authV1ManagedUserLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginManagedUserResponseFromJSON(jsonValue));
    }

    /**
     * Creates a session for a managed user (child without email/password). Requires parent authorization via Bearer token. Parent must have parental consent relationship with the managed user. Returns child JWT for multi-account device sharing.
     * Login as managed user (requires parent authorization)
     */
    async authV1ManagedUserLoginPost(requestParameters: AuthV1ManagedUserLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginManagedUserResponse> {
        const response = await this.authV1ManagedUserLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authV1ManagedUserPost without sending the request
     */
    async authV1ManagedUserPostRequestOpts(requestParameters: AuthV1ManagedUserPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/v1/managed-user`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateManagedUserRequestToJSON(requestParameters['createManagedUserRequest']),
        };
    }

    /**
     * Create a managed user account without email/password. The user can participate in platform features but cannot log in until they claim their account. Requires service authentication (internal JWT).
     * Create managed user account
     */
    async authV1ManagedUserPostRaw(requestParameters: AuthV1ManagedUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateManagedUserResponse>> {
        const requestOptions = await this.authV1ManagedUserPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateManagedUserResponseFromJSON(jsonValue));
    }

    /**
     * Create a managed user account without email/password. The user can participate in platform features but cannot log in until they claim their account. Requires service authentication (internal JWT).
     * Create managed user account
     */
    async authV1ManagedUserPost(requestParameters: AuthV1ManagedUserPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateManagedUserResponse> {
        const response = await this.authV1ManagedUserPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
