/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InboxResponse,
  NotificationErrorResponse,
  SendNotificationRequest,
  SendNotificationResponse,
} from '../models/index';
import {
    InboxResponseFromJSON,
    InboxResponseToJSON,
    NotificationErrorResponseFromJSON,
    NotificationErrorResponseToJSON,
    SendNotificationRequestFromJSON,
    SendNotificationRequestToJSON,
    SendNotificationResponseFromJSON,
    SendNotificationResponseToJSON,
} from '../models/index';

export interface NotificationsV1InboxGetRequest {
    limit?: string;
    cursor?: string;
    unreadOnly?: NotificationsV1InboxGetUnreadOnlyEnum;
}

export interface NotificationsV1NotificationIdReadPatchRequest {
    notificationId: string;
}

export interface NotificationsV1SendPostRequest {
    sendNotificationRequest?: SendNotificationRequest;
}

/**
 * NotificationsApi - interface
 * 
 * @export
 * @interface NotificationsApiInterface
 */
export interface NotificationsApiInterface {
    /**
     * Creates request options for notificationsV1InboxGet without sending the request
     * @param {string} [limit] 
     * @param {string} [cursor] 
     * @param {'true' | 'false'} [unreadOnly] 
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsV1InboxGetRequestOpts(requestParameters: NotificationsV1InboxGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns the authenticated user\'s notifications
     * @summary Get notification inbox
     * @param {string} [limit] 
     * @param {string} [cursor] 
     * @param {'true' | 'false'} [unreadOnly] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsV1InboxGetRaw(requestParameters: NotificationsV1InboxGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InboxResponse>>;

    /**
     * Returns the authenticated user\'s notifications
     * Get notification inbox
     */
    notificationsV1InboxGet(requestParameters: NotificationsV1InboxGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InboxResponse>;

    /**
     * Creates request options for notificationsV1NotificationIdReadPatch without sending the request
     * @param {string} notificationId 
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsV1NotificationIdReadPatchRequestOpts(requestParameters: NotificationsV1NotificationIdReadPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Marks a specific notification as read
     * @summary Mark notification as read
     * @param {string} notificationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsV1NotificationIdReadPatchRaw(requestParameters: NotificationsV1NotificationIdReadPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Marks a specific notification as read
     * Mark notification as read
     */
    notificationsV1NotificationIdReadPatch(requestParameters: NotificationsV1NotificationIdReadPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for notificationsV1ReadAllPatch without sending the request
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsV1ReadAllPatchRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Marks all of the user\'s notifications as read
     * @summary Mark all notifications as read
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsV1ReadAllPatchRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Marks all of the user\'s notifications as read
     * Mark all notifications as read
     */
    notificationsV1ReadAllPatch(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for notificationsV1SendPost without sending the request
     * @param {SendNotificationRequest} [sendNotificationRequest] 
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsV1SendPostRequestOpts(requestParameters: NotificationsV1SendPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new notification for a user (typically called by other services)
     * @summary Send notification
     * @param {SendNotificationRequest} [sendNotificationRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationsApiInterface
     */
    notificationsV1SendPostRaw(requestParameters: NotificationsV1SendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendNotificationResponse>>;

    /**
     * Creates a new notification for a user (typically called by other services)
     * Send notification
     */
    notificationsV1SendPost(requestParameters: NotificationsV1SendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendNotificationResponse>;

}

/**
 * 
 */
export class NotificationsApi extends runtime.BaseAPI implements NotificationsApiInterface {

    /**
     * Creates request options for notificationsV1InboxGet without sending the request
     */
    async notificationsV1InboxGetRequestOpts(requestParameters: NotificationsV1InboxGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['unreadOnly'] != null) {
            queryParameters['unreadOnly'] = requestParameters['unreadOnly'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/v1/inbox`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the authenticated user\'s notifications
     * Get notification inbox
     */
    async notificationsV1InboxGetRaw(requestParameters: NotificationsV1InboxGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InboxResponse>> {
        const requestOptions = await this.notificationsV1InboxGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InboxResponseFromJSON(jsonValue));
    }

    /**
     * Returns the authenticated user\'s notifications
     * Get notification inbox
     */
    async notificationsV1InboxGet(requestParameters: NotificationsV1InboxGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InboxResponse> {
        const response = await this.notificationsV1InboxGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for notificationsV1NotificationIdReadPatch without sending the request
     */
    async notificationsV1NotificationIdReadPatchRequestOpts(requestParameters: NotificationsV1NotificationIdReadPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notificationId'] == null) {
            throw new runtime.RequiredError(
                'notificationId',
                'Required parameter "notificationId" was null or undefined when calling notificationsV1NotificationIdReadPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/v1/{notificationId}/read`;
        urlPath = urlPath.replace(`{${"notificationId"}}`, encodeURIComponent(String(requestParameters['notificationId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marks a specific notification as read
     * Mark notification as read
     */
    async notificationsV1NotificationIdReadPatchRaw(requestParameters: NotificationsV1NotificationIdReadPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.notificationsV1NotificationIdReadPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Marks a specific notification as read
     * Mark notification as read
     */
    async notificationsV1NotificationIdReadPatch(requestParameters: NotificationsV1NotificationIdReadPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsV1NotificationIdReadPatchRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for notificationsV1ReadAllPatch without sending the request
     */
    async notificationsV1ReadAllPatchRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/v1/read-all`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marks all of the user\'s notifications as read
     * Mark all notifications as read
     */
    async notificationsV1ReadAllPatchRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.notificationsV1ReadAllPatchRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Marks all of the user\'s notifications as read
     * Mark all notifications as read
     */
    async notificationsV1ReadAllPatch(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.notificationsV1ReadAllPatchRaw(initOverrides);
    }

    /**
     * Creates request options for notificationsV1SendPost without sending the request
     */
    async notificationsV1SendPostRequestOpts(requestParameters: NotificationsV1SendPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/v1/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendNotificationRequestToJSON(requestParameters['sendNotificationRequest']),
        };
    }

    /**
     * Creates a new notification for a user (typically called by other services)
     * Send notification
     */
    async notificationsV1SendPostRaw(requestParameters: NotificationsV1SendPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendNotificationResponse>> {
        const requestOptions = await this.notificationsV1SendPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendNotificationResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new notification for a user (typically called by other services)
     * Send notification
     */
    async notificationsV1SendPost(requestParameters: NotificationsV1SendPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendNotificationResponse> {
        const response = await this.notificationsV1SendPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const NotificationsV1InboxGetUnreadOnlyEnum = {
    TRUE: 'true',
    FALSE: 'false'
} as const;
export type NotificationsV1InboxGetUnreadOnlyEnum = typeof NotificationsV1InboxGetUnreadOnlyEnum[keyof typeof NotificationsV1InboxGetUnreadOnlyEnum];
