/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  OAuthCallbackRequest,
  OAuthCallbackResponse,
  OAuthStartRequest,
  OAuthStartResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    OAuthCallbackRequestFromJSON,
    OAuthCallbackRequestToJSON,
    OAuthCallbackResponseFromJSON,
    OAuthCallbackResponseToJSON,
    OAuthStartRequestFromJSON,
    OAuthStartRequestToJSON,
    OAuthStartResponseFromJSON,
    OAuthStartResponseToJSON,
} from '../models/index';

export interface AuthV1OauthCallbackPostRequest {
    oAuthCallbackRequest?: OAuthCallbackRequest;
}

export interface AuthV1OauthStartPostRequest {
    oAuthStartRequest?: OAuthStartRequest;
}

/**
 * OAuthApi - interface
 * 
 * @export
 * @interface OAuthApiInterface
 */
export interface OAuthApiInterface {
    /**
     * Creates request options for authV1OauthCallbackPost without sending the request
     * @param {OAuthCallbackRequest} [oAuthCallbackRequest] 
     * @throws {RequiredError}
     * @memberof OAuthApiInterface
     */
    authV1OauthCallbackPostRequestOpts(requestParameters: AuthV1OauthCallbackPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Handle OAuth callback from provider
     * @summary OAuth callback
     * @param {OAuthCallbackRequest} [oAuthCallbackRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OAuthApiInterface
     */
    authV1OauthCallbackPostRaw(requestParameters: AuthV1OauthCallbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuthCallbackResponse>>;

    /**
     * Handle OAuth callback from provider
     * OAuth callback
     */
    authV1OauthCallbackPost(requestParameters: AuthV1OauthCallbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuthCallbackResponse>;

    /**
     * Creates request options for authV1OauthStartPost without sending the request
     * @param {OAuthStartRequest} [oAuthStartRequest] 
     * @throws {RequiredError}
     * @memberof OAuthApiInterface
     */
    authV1OauthStartPostRequestOpts(requestParameters: AuthV1OauthStartPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Initiate OAuth authentication with external provider
     * @summary Start OAuth flow
     * @param {OAuthStartRequest} [oAuthStartRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OAuthApiInterface
     */
    authV1OauthStartPostRaw(requestParameters: AuthV1OauthStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuthStartResponse>>;

    /**
     * Initiate OAuth authentication with external provider
     * Start OAuth flow
     */
    authV1OauthStartPost(requestParameters: AuthV1OauthStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuthStartResponse>;

}

/**
 * 
 */
export class OAuthApi extends runtime.BaseAPI implements OAuthApiInterface {

    /**
     * Creates request options for authV1OauthCallbackPost without sending the request
     */
    async authV1OauthCallbackPostRequestOpts(requestParameters: AuthV1OauthCallbackPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/v1/oauth/callback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OAuthCallbackRequestToJSON(requestParameters['oAuthCallbackRequest']),
        };
    }

    /**
     * Handle OAuth callback from provider
     * OAuth callback
     */
    async authV1OauthCallbackPostRaw(requestParameters: AuthV1OauthCallbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuthCallbackResponse>> {
        const requestOptions = await this.authV1OauthCallbackPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OAuthCallbackResponseFromJSON(jsonValue));
    }

    /**
     * Handle OAuth callback from provider
     * OAuth callback
     */
    async authV1OauthCallbackPost(requestParameters: AuthV1OauthCallbackPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuthCallbackResponse> {
        const response = await this.authV1OauthCallbackPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authV1OauthStartPost without sending the request
     */
    async authV1OauthStartPostRequestOpts(requestParameters: AuthV1OauthStartPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/v1/oauth/start`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OAuthStartRequestToJSON(requestParameters['oAuthStartRequest']),
        };
    }

    /**
     * Initiate OAuth authentication with external provider
     * Start OAuth flow
     */
    async authV1OauthStartPostRaw(requestParameters: AuthV1OauthStartPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuthStartResponse>> {
        const requestOptions = await this.authV1OauthStartPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OAuthStartResponseFromJSON(jsonValue));
    }

    /**
     * Initiate OAuth authentication with external provider
     * Start OAuth flow
     */
    async authV1OauthStartPost(requestParameters: AuthV1OauthStartPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuthStartResponse> {
        const response = await this.authV1OauthStartPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
