/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteObjectRequest,
  DeleteObjectResponse,
  DownloadUrlRequest,
  DownloadUrlResponse,
  GetMetadataRequest,
  ListObjectsRequest,
  ListObjectsResponse,
  ObjectMetadata,
  StorageV1UploadUrlPost400Response,
  UploadUrlRequest,
  UploadUrlResponse,
} from '../models/index';
import {
    DeleteObjectRequestFromJSON,
    DeleteObjectRequestToJSON,
    DeleteObjectResponseFromJSON,
    DeleteObjectResponseToJSON,
    DownloadUrlRequestFromJSON,
    DownloadUrlRequestToJSON,
    DownloadUrlResponseFromJSON,
    DownloadUrlResponseToJSON,
    GetMetadataRequestFromJSON,
    GetMetadataRequestToJSON,
    ListObjectsRequestFromJSON,
    ListObjectsRequestToJSON,
    ListObjectsResponseFromJSON,
    ListObjectsResponseToJSON,
    ObjectMetadataFromJSON,
    ObjectMetadataToJSON,
    StorageV1UploadUrlPost400ResponseFromJSON,
    StorageV1UploadUrlPost400ResponseToJSON,
    UploadUrlRequestFromJSON,
    UploadUrlRequestToJSON,
    UploadUrlResponseFromJSON,
    UploadUrlResponseToJSON,
} from '../models/index';

export interface StorageV1DownloadUrlPostRequest {
    downloadUrlRequest?: DownloadUrlRequest;
}

export interface StorageV1ObjectDeleteRequest {
    deleteObjectRequest?: DeleteObjectRequest;
}

export interface StorageV1ObjectMetaPostRequest {
    getMetadataRequest?: GetMetadataRequest;
}

export interface StorageV1ObjectsPostRequest {
    listObjectsRequest?: ListObjectsRequest;
}

export interface StorageV1UploadUrlPostRequest {
    uploadUrlRequest?: UploadUrlRequest;
}

/**
 * ObjectsApi - interface
 * 
 * @export
 * @interface ObjectsApiInterface
 */
export interface ObjectsApiInterface {
    /**
     * Creates request options for storageV1DownloadUrlPost without sending the request
     * @param {DownloadUrlRequest} [downloadUrlRequest] 
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1DownloadUrlPostRequestOpts(requestParameters: StorageV1DownloadUrlPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Generate a pre-signed URL for downloading an object from R2 storage
     * @summary Get signed download URL
     * @param {DownloadUrlRequest} [downloadUrlRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1DownloadUrlPostRaw(requestParameters: StorageV1DownloadUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DownloadUrlResponse>>;

    /**
     * Generate a pre-signed URL for downloading an object from R2 storage
     * Get signed download URL
     */
    storageV1DownloadUrlPost(requestParameters: StorageV1DownloadUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DownloadUrlResponse>;

    /**
     * Creates request options for storageV1ObjectDelete without sending the request
     * @param {DeleteObjectRequest} [deleteObjectRequest] 
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1ObjectDeleteRequestOpts(requestParameters: StorageV1ObjectDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete an object from R2 storage
     * @summary Delete object
     * @param {DeleteObjectRequest} [deleteObjectRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1ObjectDeleteRaw(requestParameters: StorageV1ObjectDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteObjectResponse>>;

    /**
     * Delete an object from R2 storage
     * Delete object
     */
    storageV1ObjectDelete(requestParameters: StorageV1ObjectDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteObjectResponse>;

    /**
     * Creates request options for storageV1ObjectMetaPost without sending the request
     * @param {GetMetadataRequest} [getMetadataRequest] 
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1ObjectMetaPostRequestOpts(requestParameters: StorageV1ObjectMetaPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieve metadata for an object without downloading it
     * @summary Get object metadata
     * @param {GetMetadataRequest} [getMetadataRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1ObjectMetaPostRaw(requestParameters: StorageV1ObjectMetaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectMetadata>>;

    /**
     * Retrieve metadata for an object without downloading it
     * Get object metadata
     */
    storageV1ObjectMetaPost(requestParameters: StorageV1ObjectMetaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectMetadata>;

    /**
     * Creates request options for storageV1ObjectsPost without sending the request
     * @param {ListObjectsRequest} [listObjectsRequest] 
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1ObjectsPostRequestOpts(requestParameters: StorageV1ObjectsPostRequest): Promise<runtime.RequestOpts>;

    /**
     * List objects in a bucket with optional prefix filtering and pagination
     * @summary List objects
     * @param {ListObjectsRequest} [listObjectsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1ObjectsPostRaw(requestParameters: StorageV1ObjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListObjectsResponse>>;

    /**
     * List objects in a bucket with optional prefix filtering and pagination
     * List objects
     */
    storageV1ObjectsPost(requestParameters: StorageV1ObjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListObjectsResponse>;

    /**
     * Creates request options for storageV1UploadUrlPost without sending the request
     * @param {UploadUrlRequest} [uploadUrlRequest] 
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1UploadUrlPostRequestOpts(requestParameters: StorageV1UploadUrlPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Generate a pre-signed URL for uploading an object to R2 storage
     * @summary Get signed upload URL
     * @param {UploadUrlRequest} [uploadUrlRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObjectsApiInterface
     */
    storageV1UploadUrlPostRaw(requestParameters: StorageV1UploadUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadUrlResponse>>;

    /**
     * Generate a pre-signed URL for uploading an object to R2 storage
     * Get signed upload URL
     */
    storageV1UploadUrlPost(requestParameters: StorageV1UploadUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadUrlResponse>;

}

/**
 * 
 */
export class ObjectsApi extends runtime.BaseAPI implements ObjectsApiInterface {

    /**
     * Creates request options for storageV1DownloadUrlPost without sending the request
     */
    async storageV1DownloadUrlPostRequestOpts(requestParameters: StorageV1DownloadUrlPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/download-url`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DownloadUrlRequestToJSON(requestParameters['downloadUrlRequest']),
        };
    }

    /**
     * Generate a pre-signed URL for downloading an object from R2 storage
     * Get signed download URL
     */
    async storageV1DownloadUrlPostRaw(requestParameters: StorageV1DownloadUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DownloadUrlResponse>> {
        const requestOptions = await this.storageV1DownloadUrlPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DownloadUrlResponseFromJSON(jsonValue));
    }

    /**
     * Generate a pre-signed URL for downloading an object from R2 storage
     * Get signed download URL
     */
    async storageV1DownloadUrlPost(requestParameters: StorageV1DownloadUrlPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DownloadUrlResponse> {
        const response = await this.storageV1DownloadUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storageV1ObjectDelete without sending the request
     */
    async storageV1ObjectDeleteRequestOpts(requestParameters: StorageV1ObjectDeleteRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/object`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteObjectRequestToJSON(requestParameters['deleteObjectRequest']),
        };
    }

    /**
     * Delete an object from R2 storage
     * Delete object
     */
    async storageV1ObjectDeleteRaw(requestParameters: StorageV1ObjectDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteObjectResponse>> {
        const requestOptions = await this.storageV1ObjectDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteObjectResponseFromJSON(jsonValue));
    }

    /**
     * Delete an object from R2 storage
     * Delete object
     */
    async storageV1ObjectDelete(requestParameters: StorageV1ObjectDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteObjectResponse> {
        const response = await this.storageV1ObjectDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storageV1ObjectMetaPost without sending the request
     */
    async storageV1ObjectMetaPostRequestOpts(requestParameters: StorageV1ObjectMetaPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/object/meta`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetMetadataRequestToJSON(requestParameters['getMetadataRequest']),
        };
    }

    /**
     * Retrieve metadata for an object without downloading it
     * Get object metadata
     */
    async storageV1ObjectMetaPostRaw(requestParameters: StorageV1ObjectMetaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectMetadata>> {
        const requestOptions = await this.storageV1ObjectMetaPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectMetadataFromJSON(jsonValue));
    }

    /**
     * Retrieve metadata for an object without downloading it
     * Get object metadata
     */
    async storageV1ObjectMetaPost(requestParameters: StorageV1ObjectMetaPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectMetadata> {
        const response = await this.storageV1ObjectMetaPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storageV1ObjectsPost without sending the request
     */
    async storageV1ObjectsPostRequestOpts(requestParameters: StorageV1ObjectsPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/objects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListObjectsRequestToJSON(requestParameters['listObjectsRequest']),
        };
    }

    /**
     * List objects in a bucket with optional prefix filtering and pagination
     * List objects
     */
    async storageV1ObjectsPostRaw(requestParameters: StorageV1ObjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListObjectsResponse>> {
        const requestOptions = await this.storageV1ObjectsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListObjectsResponseFromJSON(jsonValue));
    }

    /**
     * List objects in a bucket with optional prefix filtering and pagination
     * List objects
     */
    async storageV1ObjectsPost(requestParameters: StorageV1ObjectsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListObjectsResponse> {
        const response = await this.storageV1ObjectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storageV1UploadUrlPost without sending the request
     */
    async storageV1UploadUrlPostRequestOpts(requestParameters: StorageV1UploadUrlPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/upload-url`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadUrlRequestToJSON(requestParameters['uploadUrlRequest']),
        };
    }

    /**
     * Generate a pre-signed URL for uploading an object to R2 storage
     * Get signed upload URL
     */
    async storageV1UploadUrlPostRaw(requestParameters: StorageV1UploadUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadUrlResponse>> {
        const requestOptions = await this.storageV1UploadUrlPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadUrlResponseFromJSON(jsonValue));
    }

    /**
     * Generate a pre-signed URL for uploading an object to R2 storage
     * Get signed upload URL
     */
    async storageV1UploadUrlPost(requestParameters: StorageV1UploadUrlPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadUrlResponse> {
        const response = await this.storageV1UploadUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
