/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePledgeRequest,
  GamificationErrorResponse,
  PledgeListResponse,
  SponsorPledge,
  UpdatePledgeRequest,
} from '../models/index';
import {
    CreatePledgeRequestFromJSON,
    CreatePledgeRequestToJSON,
    GamificationErrorResponseFromJSON,
    GamificationErrorResponseToJSON,
    PledgeListResponseFromJSON,
    PledgeListResponseToJSON,
    SponsorPledgeFromJSON,
    SponsorPledgeToJSON,
    UpdatePledgeRequestFromJSON,
    UpdatePledgeRequestToJSON,
} from '../models/index';

export interface GamificationV1PledgesGetRequest {
    goalId?: string;
    sponsorId?: string;
}

export interface GamificationV1PledgesPledgeIdGetRequest {
    pledgeId: string;
}

export interface GamificationV1PledgesPledgeIdPatchRequest {
    pledgeId: string;
    updatePledgeRequest?: UpdatePledgeRequest;
}

export interface GamificationV1PledgesPostRequest {
    createPledgeRequest?: CreatePledgeRequest;
}

/**
 * PledgesApi - interface
 * 
 * @export
 * @interface PledgesApiInterface
 */
export interface PledgesApiInterface {
    /**
     * Creates request options for gamificationV1PledgesGet without sending the request
     * @param {string} [goalId] 
     * @param {string} [sponsorId] 
     * @throws {RequiredError}
     * @memberof PledgesApiInterface
     */
    gamificationV1PledgesGetRequestOpts(requestParameters: GamificationV1PledgesGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns pledges (filtered by goal or sponsor)
     * @summary List pledges
     * @param {string} [goalId] 
     * @param {string} [sponsorId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PledgesApiInterface
     */
    gamificationV1PledgesGetRaw(requestParameters: GamificationV1PledgesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PledgeListResponse>>;

    /**
     * Returns pledges (filtered by goal or sponsor)
     * List pledges
     */
    gamificationV1PledgesGet(requestParameters: GamificationV1PledgesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PledgeListResponse>;

    /**
     * Creates request options for gamificationV1PledgesPledgeIdGet without sending the request
     * @param {string} pledgeId 
     * @throws {RequiredError}
     * @memberof PledgesApiInterface
     */
    gamificationV1PledgesPledgeIdGetRequestOpts(requestParameters: GamificationV1PledgesPledgeIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a specific pledge by ID
     * @summary Get pledge
     * @param {string} pledgeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PledgesApiInterface
     */
    gamificationV1PledgesPledgeIdGetRaw(requestParameters: GamificationV1PledgesPledgeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SponsorPledge>>;

    /**
     * Returns a specific pledge by ID
     * Get pledge
     */
    gamificationV1PledgesPledgeIdGet(requestParameters: GamificationV1PledgesPledgeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SponsorPledge>;

    /**
     * Creates request options for gamificationV1PledgesPledgeIdPatch without sending the request
     * @param {string} pledgeId 
     * @param {UpdatePledgeRequest} [updatePledgeRequest] 
     * @throws {RequiredError}
     * @memberof PledgesApiInterface
     */
    gamificationV1PledgesPledgeIdPatchRequestOpts(requestParameters: GamificationV1PledgesPledgeIdPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates pledge status or payment info
     * @summary Update pledge
     * @param {string} pledgeId 
     * @param {UpdatePledgeRequest} [updatePledgeRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PledgesApiInterface
     */
    gamificationV1PledgesPledgeIdPatchRaw(requestParameters: GamificationV1PledgesPledgeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SponsorPledge>>;

    /**
     * Updates pledge status or payment info
     * Update pledge
     */
    gamificationV1PledgesPledgeIdPatch(requestParameters: GamificationV1PledgesPledgeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SponsorPledge>;

    /**
     * Creates request options for gamificationV1PledgesPost without sending the request
     * @param {CreatePledgeRequest} [createPledgeRequest] 
     * @throws {RequiredError}
     * @memberof PledgesApiInterface
     */
    gamificationV1PledgesPostRequestOpts(requestParameters: GamificationV1PledgesPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a sponsor pledge for a goal
     * @summary Create pledge
     * @param {CreatePledgeRequest} [createPledgeRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PledgesApiInterface
     */
    gamificationV1PledgesPostRaw(requestParameters: GamificationV1PledgesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SponsorPledge>>;

    /**
     * Creates a sponsor pledge for a goal
     * Create pledge
     */
    gamificationV1PledgesPost(requestParameters: GamificationV1PledgesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SponsorPledge>;

}

/**
 * 
 */
export class PledgesApi extends runtime.BaseAPI implements PledgesApiInterface {

    /**
     * Creates request options for gamificationV1PledgesGet without sending the request
     */
    async gamificationV1PledgesGetRequestOpts(requestParameters: GamificationV1PledgesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['goalId'] != null) {
            queryParameters['goalId'] = requestParameters['goalId'];
        }

        if (requestParameters['sponsorId'] != null) {
            queryParameters['sponsorId'] = requestParameters['sponsorId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/pledges`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns pledges (filtered by goal or sponsor)
     * List pledges
     */
    async gamificationV1PledgesGetRaw(requestParameters: GamificationV1PledgesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PledgeListResponse>> {
        const requestOptions = await this.gamificationV1PledgesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PledgeListResponseFromJSON(jsonValue));
    }

    /**
     * Returns pledges (filtered by goal or sponsor)
     * List pledges
     */
    async gamificationV1PledgesGet(requestParameters: GamificationV1PledgesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PledgeListResponse> {
        const response = await this.gamificationV1PledgesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1PledgesPledgeIdGet without sending the request
     */
    async gamificationV1PledgesPledgeIdGetRequestOpts(requestParameters: GamificationV1PledgesPledgeIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pledgeId'] == null) {
            throw new runtime.RequiredError(
                'pledgeId',
                'Required parameter "pledgeId" was null or undefined when calling gamificationV1PledgesPledgeIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/pledges/{pledgeId}`;
        urlPath = urlPath.replace(`{${"pledgeId"}}`, encodeURIComponent(String(requestParameters['pledgeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a specific pledge by ID
     * Get pledge
     */
    async gamificationV1PledgesPledgeIdGetRaw(requestParameters: GamificationV1PledgesPledgeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SponsorPledge>> {
        const requestOptions = await this.gamificationV1PledgesPledgeIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SponsorPledgeFromJSON(jsonValue));
    }

    /**
     * Returns a specific pledge by ID
     * Get pledge
     */
    async gamificationV1PledgesPledgeIdGet(requestParameters: GamificationV1PledgesPledgeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SponsorPledge> {
        const response = await this.gamificationV1PledgesPledgeIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1PledgesPledgeIdPatch without sending the request
     */
    async gamificationV1PledgesPledgeIdPatchRequestOpts(requestParameters: GamificationV1PledgesPledgeIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pledgeId'] == null) {
            throw new runtime.RequiredError(
                'pledgeId',
                'Required parameter "pledgeId" was null or undefined when calling gamificationV1PledgesPledgeIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/pledges/{pledgeId}`;
        urlPath = urlPath.replace(`{${"pledgeId"}}`, encodeURIComponent(String(requestParameters['pledgeId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePledgeRequestToJSON(requestParameters['updatePledgeRequest']),
        };
    }

    /**
     * Updates pledge status or payment info
     * Update pledge
     */
    async gamificationV1PledgesPledgeIdPatchRaw(requestParameters: GamificationV1PledgesPledgeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SponsorPledge>> {
        const requestOptions = await this.gamificationV1PledgesPledgeIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SponsorPledgeFromJSON(jsonValue));
    }

    /**
     * Updates pledge status or payment info
     * Update pledge
     */
    async gamificationV1PledgesPledgeIdPatch(requestParameters: GamificationV1PledgesPledgeIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SponsorPledge> {
        const response = await this.gamificationV1PledgesPledgeIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1PledgesPost without sending the request
     */
    async gamificationV1PledgesPostRequestOpts(requestParameters: GamificationV1PledgesPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/pledges`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePledgeRequestToJSON(requestParameters['createPledgeRequest']),
        };
    }

    /**
     * Creates a sponsor pledge for a goal
     * Create pledge
     */
    async gamificationV1PledgesPostRaw(requestParameters: GamificationV1PledgesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SponsorPledge>> {
        const requestOptions = await this.gamificationV1PledgesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SponsorPledgeFromJSON(jsonValue));
    }

    /**
     * Creates a sponsor pledge for a goal
     * Create pledge
     */
    async gamificationV1PledgesPost(requestParameters: GamificationV1PledgesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SponsorPledge> {
        const response = await this.gamificationV1PledgesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
