/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetPreferencesResponse,
  NotificationErrorResponse,
  UpdatePreferencesRequest,
} from '../models/index';
import {
    GetPreferencesResponseFromJSON,
    GetPreferencesResponseToJSON,
    NotificationErrorResponseFromJSON,
    NotificationErrorResponseToJSON,
    UpdatePreferencesRequestFromJSON,
    UpdatePreferencesRequestToJSON,
} from '../models/index';

export interface NotificationsV1PreferencesPatchRequest {
    updatePreferencesRequest?: UpdatePreferencesRequest;
}

/**
 * PreferencesApi - interface
 * 
 * @export
 * @interface PreferencesApiInterface
 */
export interface PreferencesApiInterface {
    /**
     * Creates request options for notificationsV1PreferencesGet without sending the request
     * @throws {RequiredError}
     * @memberof PreferencesApiInterface
     */
    notificationsV1PreferencesGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns the authenticated user\'s notification preferences
     * @summary Get notification preferences
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApiInterface
     */
    notificationsV1PreferencesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPreferencesResponse>>;

    /**
     * Returns the authenticated user\'s notification preferences
     * Get notification preferences
     */
    notificationsV1PreferencesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPreferencesResponse>;

    /**
     * Creates request options for notificationsV1PreferencesPatch without sending the request
     * @param {UpdatePreferencesRequest} [updatePreferencesRequest] 
     * @throws {RequiredError}
     * @memberof PreferencesApiInterface
     */
    notificationsV1PreferencesPatchRequestOpts(requestParameters: NotificationsV1PreferencesPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates the authenticated user\'s notification preferences
     * @summary Update notification preferences
     * @param {UpdatePreferencesRequest} [updatePreferencesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PreferencesApiInterface
     */
    notificationsV1PreferencesPatchRaw(requestParameters: NotificationsV1PreferencesPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPreferencesResponse>>;

    /**
     * Updates the authenticated user\'s notification preferences
     * Update notification preferences
     */
    notificationsV1PreferencesPatch(requestParameters: NotificationsV1PreferencesPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPreferencesResponse>;

}

/**
 * 
 */
export class PreferencesApi extends runtime.BaseAPI implements PreferencesApiInterface {

    /**
     * Creates request options for notificationsV1PreferencesGet without sending the request
     */
    async notificationsV1PreferencesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/v1/preferences`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the authenticated user\'s notification preferences
     * Get notification preferences
     */
    async notificationsV1PreferencesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPreferencesResponse>> {
        const requestOptions = await this.notificationsV1PreferencesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPreferencesResponseFromJSON(jsonValue));
    }

    /**
     * Returns the authenticated user\'s notification preferences
     * Get notification preferences
     */
    async notificationsV1PreferencesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPreferencesResponse> {
        const response = await this.notificationsV1PreferencesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for notificationsV1PreferencesPatch without sending the request
     */
    async notificationsV1PreferencesPatchRequestOpts(requestParameters: NotificationsV1PreferencesPatchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/v1/preferences`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePreferencesRequestToJSON(requestParameters['updatePreferencesRequest']),
        };
    }

    /**
     * Updates the authenticated user\'s notification preferences
     * Update notification preferences
     */
    async notificationsV1PreferencesPatchRaw(requestParameters: NotificationsV1PreferencesPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPreferencesResponse>> {
        const requestOptions = await this.notificationsV1PreferencesPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPreferencesResponseFromJSON(jsonValue));
    }

    /**
     * Updates the authenticated user\'s notification preferences
     * Update notification preferences
     */
    async notificationsV1PreferencesPatch(requestParameters: NotificationsV1PreferencesPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPreferencesResponse> {
        const response = await this.notificationsV1PreferencesPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
