/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRewardRequest,
  GamificationErrorResponse,
  Reward,
  RewardListResponse,
  UpdateRewardRequest,
} from '../models/index';
import {
    CreateRewardRequestFromJSON,
    CreateRewardRequestToJSON,
    GamificationErrorResponseFromJSON,
    GamificationErrorResponseToJSON,
    RewardFromJSON,
    RewardToJSON,
    RewardListResponseFromJSON,
    RewardListResponseToJSON,
    UpdateRewardRequestFromJSON,
    UpdateRewardRequestToJSON,
} from '../models/index';

export interface GamificationV1RewardsGetRequest {
    providedBy?: string;
    recipientId?: string;
    groupId?: string;
    status?: GamificationV1RewardsGetStatusEnum;
}

export interface GamificationV1RewardsPostRequest {
    createRewardRequest?: CreateRewardRequest;
}

export interface GamificationV1RewardsRewardIdFulfillPostRequest {
    rewardId: string;
}

export interface GamificationV1RewardsRewardIdGetRequest {
    rewardId: string;
}

export interface GamificationV1RewardsRewardIdPatchRequest {
    rewardId: string;
    updateRewardRequest?: UpdateRewardRequest;
}

/**
 * RewardsApi - interface
 * 
 * @export
 * @interface RewardsApiInterface
 */
export interface RewardsApiInterface {
    /**
     * Creates request options for gamificationV1RewardsGet without sending the request
     * @param {string} [providedBy] 
     * @param {string} [recipientId] 
     * @param {string} [groupId] 
     * @param {'active' | 'fulfilled' | 'cancelled'} [status] 
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsGetRequestOpts(requestParameters: GamificationV1RewardsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns rewards for this venture with optional filters
     * @summary List rewards
     * @param {string} [providedBy] 
     * @param {string} [recipientId] 
     * @param {string} [groupId] 
     * @param {'active' | 'fulfilled' | 'cancelled'} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsGetRaw(requestParameters: GamificationV1RewardsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardListResponse>>;

    /**
     * Returns rewards for this venture with optional filters
     * List rewards
     */
    gamificationV1RewardsGet(requestParameters: GamificationV1RewardsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardListResponse>;

    /**
     * Creates request options for gamificationV1RewardsPost without sending the request
     * @param {CreateRewardRequest} [createRewardRequest] 
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsPostRequestOpts(requestParameters: GamificationV1RewardsPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new reward definition
     * @summary Create reward
     * @param {CreateRewardRequest} [createRewardRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsPostRaw(requestParameters: GamificationV1RewardsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>>;

    /**
     * Creates a new reward definition
     * Create reward
     */
    gamificationV1RewardsPost(requestParameters: GamificationV1RewardsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward>;

    /**
     * Creates request options for gamificationV1RewardsRewardIdFulfillPost without sending the request
     * @param {string} rewardId 
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsRewardIdFulfillPostRequestOpts(requestParameters: GamificationV1RewardsRewardIdFulfillPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Marks a reward as fulfilled (delivered to recipient)
     * @summary Fulfill reward
     * @param {string} rewardId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsRewardIdFulfillPostRaw(requestParameters: GamificationV1RewardsRewardIdFulfillPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>>;

    /**
     * Marks a reward as fulfilled (delivered to recipient)
     * Fulfill reward
     */
    gamificationV1RewardsRewardIdFulfillPost(requestParameters: GamificationV1RewardsRewardIdFulfillPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward>;

    /**
     * Creates request options for gamificationV1RewardsRewardIdGet without sending the request
     * @param {string} rewardId 
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsRewardIdGetRequestOpts(requestParameters: GamificationV1RewardsRewardIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a specific reward by ID
     * @summary Get reward
     * @param {string} rewardId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsRewardIdGetRaw(requestParameters: GamificationV1RewardsRewardIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>>;

    /**
     * Returns a specific reward by ID
     * Get reward
     */
    gamificationV1RewardsRewardIdGet(requestParameters: GamificationV1RewardsRewardIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward>;

    /**
     * Creates request options for gamificationV1RewardsRewardIdPatch without sending the request
     * @param {string} rewardId 
     * @param {UpdateRewardRequest} [updateRewardRequest] 
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsRewardIdPatchRequestOpts(requestParameters: GamificationV1RewardsRewardIdPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates a reward (name, description, value, or status)
     * @summary Update reward
     * @param {string} rewardId 
     * @param {UpdateRewardRequest} [updateRewardRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RewardsApiInterface
     */
    gamificationV1RewardsRewardIdPatchRaw(requestParameters: GamificationV1RewardsRewardIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>>;

    /**
     * Updates a reward (name, description, value, or status)
     * Update reward
     */
    gamificationV1RewardsRewardIdPatch(requestParameters: GamificationV1RewardsRewardIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward>;

}

/**
 * 
 */
export class RewardsApi extends runtime.BaseAPI implements RewardsApiInterface {

    /**
     * Creates request options for gamificationV1RewardsGet without sending the request
     */
    async gamificationV1RewardsGetRequestOpts(requestParameters: GamificationV1RewardsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['providedBy'] != null) {
            queryParameters['providedBy'] = requestParameters['providedBy'];
        }

        if (requestParameters['recipientId'] != null) {
            queryParameters['recipientId'] = requestParameters['recipientId'];
        }

        if (requestParameters['groupId'] != null) {
            queryParameters['groupId'] = requestParameters['groupId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/rewards`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns rewards for this venture with optional filters
     * List rewards
     */
    async gamificationV1RewardsGetRaw(requestParameters: GamificationV1RewardsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RewardListResponse>> {
        const requestOptions = await this.gamificationV1RewardsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardListResponseFromJSON(jsonValue));
    }

    /**
     * Returns rewards for this venture with optional filters
     * List rewards
     */
    async gamificationV1RewardsGet(requestParameters: GamificationV1RewardsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RewardListResponse> {
        const response = await this.gamificationV1RewardsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1RewardsPost without sending the request
     */
    async gamificationV1RewardsPostRequestOpts(requestParameters: GamificationV1RewardsPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/rewards`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRewardRequestToJSON(requestParameters['createRewardRequest']),
        };
    }

    /**
     * Creates a new reward definition
     * Create reward
     */
    async gamificationV1RewardsPostRaw(requestParameters: GamificationV1RewardsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>> {
        const requestOptions = await this.gamificationV1RewardsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardFromJSON(jsonValue));
    }

    /**
     * Creates a new reward definition
     * Create reward
     */
    async gamificationV1RewardsPost(requestParameters: GamificationV1RewardsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward> {
        const response = await this.gamificationV1RewardsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1RewardsRewardIdFulfillPost without sending the request
     */
    async gamificationV1RewardsRewardIdFulfillPostRequestOpts(requestParameters: GamificationV1RewardsRewardIdFulfillPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rewardId'] == null) {
            throw new runtime.RequiredError(
                'rewardId',
                'Required parameter "rewardId" was null or undefined when calling gamificationV1RewardsRewardIdFulfillPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/rewards/{rewardId}/fulfill`;
        urlPath = urlPath.replace(`{${"rewardId"}}`, encodeURIComponent(String(requestParameters['rewardId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marks a reward as fulfilled (delivered to recipient)
     * Fulfill reward
     */
    async gamificationV1RewardsRewardIdFulfillPostRaw(requestParameters: GamificationV1RewardsRewardIdFulfillPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>> {
        const requestOptions = await this.gamificationV1RewardsRewardIdFulfillPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardFromJSON(jsonValue));
    }

    /**
     * Marks a reward as fulfilled (delivered to recipient)
     * Fulfill reward
     */
    async gamificationV1RewardsRewardIdFulfillPost(requestParameters: GamificationV1RewardsRewardIdFulfillPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward> {
        const response = await this.gamificationV1RewardsRewardIdFulfillPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1RewardsRewardIdGet without sending the request
     */
    async gamificationV1RewardsRewardIdGetRequestOpts(requestParameters: GamificationV1RewardsRewardIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rewardId'] == null) {
            throw new runtime.RequiredError(
                'rewardId',
                'Required parameter "rewardId" was null or undefined when calling gamificationV1RewardsRewardIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/rewards/{rewardId}`;
        urlPath = urlPath.replace(`{${"rewardId"}}`, encodeURIComponent(String(requestParameters['rewardId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a specific reward by ID
     * Get reward
     */
    async gamificationV1RewardsRewardIdGetRaw(requestParameters: GamificationV1RewardsRewardIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>> {
        const requestOptions = await this.gamificationV1RewardsRewardIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardFromJSON(jsonValue));
    }

    /**
     * Returns a specific reward by ID
     * Get reward
     */
    async gamificationV1RewardsRewardIdGet(requestParameters: GamificationV1RewardsRewardIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward> {
        const response = await this.gamificationV1RewardsRewardIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1RewardsRewardIdPatch without sending the request
     */
    async gamificationV1RewardsRewardIdPatchRequestOpts(requestParameters: GamificationV1RewardsRewardIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rewardId'] == null) {
            throw new runtime.RequiredError(
                'rewardId',
                'Required parameter "rewardId" was null or undefined when calling gamificationV1RewardsRewardIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/rewards/{rewardId}`;
        urlPath = urlPath.replace(`{${"rewardId"}}`, encodeURIComponent(String(requestParameters['rewardId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRewardRequestToJSON(requestParameters['updateRewardRequest']),
        };
    }

    /**
     * Updates a reward (name, description, value, or status)
     * Update reward
     */
    async gamificationV1RewardsRewardIdPatchRaw(requestParameters: GamificationV1RewardsRewardIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reward>> {
        const requestOptions = await this.gamificationV1RewardsRewardIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RewardFromJSON(jsonValue));
    }

    /**
     * Updates a reward (name, description, value, or status)
     * Update reward
     */
    async gamificationV1RewardsRewardIdPatch(requestParameters: GamificationV1RewardsRewardIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reward> {
        const response = await this.gamificationV1RewardsRewardIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GamificationV1RewardsGetStatusEnum = {
    ACTIVE: 'active',
    FULFILLED: 'fulfilled',
    CANCELLED: 'cancelled'
} as const;
export type GamificationV1RewardsGetStatusEnum = typeof GamificationV1RewardsGetStatusEnum[keyof typeof GamificationV1RewardsGetStatusEnum];
