/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  LogoutRequest,
  LogoutResponse,
  SessionsResponse,
  SuccessResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LogoutRequestFromJSON,
    LogoutRequestToJSON,
    LogoutResponseFromJSON,
    LogoutResponseToJSON,
    SessionsResponseFromJSON,
    SessionsResponseToJSON,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
} from '../models/index';

export interface AuthV1LogoutPostRequest {
    logoutRequest?: LogoutRequest;
}

export interface AuthV1SessionsSessionIdDeleteRequest {
    sessionId: string;
}

/**
 * SessionApi - interface
 * 
 * @export
 * @interface SessionApiInterface
 */
export interface SessionApiInterface {
    /**
     * Creates request options for authV1LogoutPost without sending the request
     * @param {LogoutRequest} [logoutRequest] 
     * @throws {RequiredError}
     * @memberof SessionApiInterface
     */
    authV1LogoutPostRequestOpts(requestParameters: AuthV1LogoutPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Revoke refresh token and end session
     * @summary Logout user
     * @param {LogoutRequest} [logoutRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionApiInterface
     */
    authV1LogoutPostRaw(requestParameters: AuthV1LogoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LogoutResponse>>;

    /**
     * Revoke refresh token and end session
     * Logout user
     */
    authV1LogoutPost(requestParameters: AuthV1LogoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LogoutResponse>;

    /**
     * Creates request options for authV1SessionsGet without sending the request
     * @throws {RequiredError}
     * @memberof SessionApiInterface
     */
    authV1SessionsGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Get all active sessions for the current user
     * @summary List active sessions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionApiInterface
     */
    authV1SessionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionsResponse>>;

    /**
     * Get all active sessions for the current user
     * List active sessions
     */
    authV1SessionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionsResponse>;

    /**
     * Creates request options for authV1SessionsSessionIdDelete without sending the request
     * @param {string} sessionId 
     * @throws {RequiredError}
     * @memberof SessionApiInterface
     */
    authV1SessionsSessionIdDeleteRequestOpts(requestParameters: AuthV1SessionsSessionIdDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Revoke a specific session by ID
     * @summary Revoke a session
     * @param {string} sessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SessionApiInterface
     */
    authV1SessionsSessionIdDeleteRaw(requestParameters: AuthV1SessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>>;

    /**
     * Revoke a specific session by ID
     * Revoke a session
     */
    authV1SessionsSessionIdDelete(requestParameters: AuthV1SessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse>;

}

/**
 * 
 */
export class SessionApi extends runtime.BaseAPI implements SessionApiInterface {

    /**
     * Creates request options for authV1LogoutPost without sending the request
     */
    async authV1LogoutPostRequestOpts(requestParameters: AuthV1LogoutPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/v1/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogoutRequestToJSON(requestParameters['logoutRequest']),
        };
    }

    /**
     * Revoke refresh token and end session
     * Logout user
     */
    async authV1LogoutPostRaw(requestParameters: AuthV1LogoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LogoutResponse>> {
        const requestOptions = await this.authV1LogoutPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LogoutResponseFromJSON(jsonValue));
    }

    /**
     * Revoke refresh token and end session
     * Logout user
     */
    async authV1LogoutPost(requestParameters: AuthV1LogoutPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LogoutResponse> {
        const response = await this.authV1LogoutPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authV1SessionsGet without sending the request
     */
    async authV1SessionsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/v1/sessions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all active sessions for the current user
     * List active sessions
     */
    async authV1SessionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionsResponse>> {
        const requestOptions = await this.authV1SessionsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionsResponseFromJSON(jsonValue));
    }

    /**
     * Get all active sessions for the current user
     * List active sessions
     */
    async authV1SessionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionsResponse> {
        const response = await this.authV1SessionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authV1SessionsSessionIdDelete without sending the request
     */
    async authV1SessionsSessionIdDeleteRequestOpts(requestParameters: AuthV1SessionsSessionIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling authV1SessionsSessionIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/v1/sessions/{sessionId}`;
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke a specific session by ID
     * Revoke a session
     */
    async authV1SessionsSessionIdDeleteRaw(requestParameters: AuthV1SessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        const requestOptions = await this.authV1SessionsSessionIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Revoke a specific session by ID
     * Revoke a session
     */
    async authV1SessionsSessionIdDelete(requestParameters: AuthV1SessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.authV1SessionsSessionIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
