/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GamificationErrorResponse,
  StreakListResponse,
  UpdateStreakRequest,
  UpdateStreakResponse,
} from '../models/index';
import {
    GamificationErrorResponseFromJSON,
    GamificationErrorResponseToJSON,
    StreakListResponseFromJSON,
    StreakListResponseToJSON,
    UpdateStreakRequestFromJSON,
    UpdateStreakRequestToJSON,
    UpdateStreakResponseFromJSON,
    UpdateStreakResponseToJSON,
} from '../models/index';

export interface GamificationV1StreaksGetRequest {
    userId: string;
}

export interface GamificationV1StreaksPostRequest {
    updateStreakRequest?: UpdateStreakRequest;
}

/**
 * StreaksApi - interface
 * 
 * @export
 * @interface StreaksApiInterface
 */
export interface StreaksApiInterface {
    /**
     * Creates request options for gamificationV1StreaksGet without sending the request
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof StreaksApiInterface
     */
    gamificationV1StreaksGetRequestOpts(requestParameters: GamificationV1StreaksGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns all streaks for a user
     * @summary Get user streaks
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StreaksApiInterface
     */
    gamificationV1StreaksGetRaw(requestParameters: GamificationV1StreaksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakListResponse>>;

    /**
     * Returns all streaks for a user
     * Get user streaks
     */
    gamificationV1StreaksGet(requestParameters: GamificationV1StreaksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakListResponse>;

    /**
     * Creates request options for gamificationV1StreaksPost without sending the request
     * @param {UpdateStreakRequest} [updateStreakRequest] 
     * @throws {RequiredError}
     * @memberof StreaksApiInterface
     */
    gamificationV1StreaksPostRequestOpts(requestParameters: GamificationV1StreaksPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates a streak based on activity. Creates streak if not exists.
     * @summary Update streak
     * @param {UpdateStreakRequest} [updateStreakRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StreaksApiInterface
     */
    gamificationV1StreaksPostRaw(requestParameters: GamificationV1StreaksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateStreakResponse>>;

    /**
     * Updates a streak based on activity. Creates streak if not exists.
     * Update streak
     */
    gamificationV1StreaksPost(requestParameters: GamificationV1StreaksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateStreakResponse>;

}

/**
 * 
 */
export class StreaksApi extends runtime.BaseAPI implements StreaksApiInterface {

    /**
     * Creates request options for gamificationV1StreaksGet without sending the request
     */
    async gamificationV1StreaksGetRequestOpts(requestParameters: GamificationV1StreaksGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling gamificationV1StreaksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/streaks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all streaks for a user
     * Get user streaks
     */
    async gamificationV1StreaksGetRaw(requestParameters: GamificationV1StreaksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakListResponse>> {
        const requestOptions = await this.gamificationV1StreaksGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakListResponseFromJSON(jsonValue));
    }

    /**
     * Returns all streaks for a user
     * Get user streaks
     */
    async gamificationV1StreaksGet(requestParameters: GamificationV1StreaksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakListResponse> {
        const response = await this.gamificationV1StreaksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1StreaksPost without sending the request
     */
    async gamificationV1StreaksPostRequestOpts(requestParameters: GamificationV1StreaksPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/streaks`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateStreakRequestToJSON(requestParameters['updateStreakRequest']),
        };
    }

    /**
     * Updates a streak based on activity. Creates streak if not exists.
     * Update streak
     */
    async gamificationV1StreaksPostRaw(requestParameters: GamificationV1StreaksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateStreakResponse>> {
        const requestOptions = await this.gamificationV1StreaksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateStreakResponseFromJSON(jsonValue));
    }

    /**
     * Updates a streak based on activity. Creates streak if not exists.
     * Update streak
     */
    async gamificationV1StreaksPost(requestParameters: GamificationV1StreaksPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateStreakResponse> {
        const response = await this.gamificationV1StreaksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
