/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GroupsErrorResponse,
  UserGroupsResponse,
} from '../models/index';
import {
    GroupsErrorResponseFromJSON,
    GroupsErrorResponseToJSON,
    UserGroupsResponseFromJSON,
    UserGroupsResponseToJSON,
} from '../models/index';

export interface GroupsV1UsersUserIdGroupsGetRequest {
    userId: string;
    groupType?: string;
    status?: GroupsV1UsersUserIdGroupsGetStatusEnum;
}

/**
 * UserGroupsApi - interface
 * 
 * @export
 * @interface UserGroupsApiInterface
 */
export interface UserGroupsApiInterface {
    /**
     * Creates request options for groupsV1UsersUserIdGroupsGet without sending the request
     * @param {string} userId 
     * @param {string} [groupType] 
     * @param {'active' | 'pending' | 'rejected'} [status] 
     * @throws {RequiredError}
     * @memberof UserGroupsApiInterface
     */
    groupsV1UsersUserIdGroupsGetRequestOpts(requestParameters: GroupsV1UsersUserIdGroupsGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns all groups a user belongs to
     * @summary Get user groups
     * @param {string} userId 
     * @param {string} [groupType] 
     * @param {'active' | 'pending' | 'rejected'} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserGroupsApiInterface
     */
    groupsV1UsersUserIdGroupsGetRaw(requestParameters: GroupsV1UsersUserIdGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserGroupsResponse>>;

    /**
     * Returns all groups a user belongs to
     * Get user groups
     */
    groupsV1UsersUserIdGroupsGet(requestParameters: GroupsV1UsersUserIdGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserGroupsResponse>;

}

/**
 * 
 */
export class UserGroupsApi extends runtime.BaseAPI implements UserGroupsApiInterface {

    /**
     * Creates request options for groupsV1UsersUserIdGroupsGet without sending the request
     */
    async groupsV1UsersUserIdGroupsGetRequestOpts(requestParameters: GroupsV1UsersUserIdGroupsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling groupsV1UsersUserIdGroupsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['groupType'] != null) {
            queryParameters['groupType'] = requestParameters['groupType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/groups/v1/users/{userId}/groups`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all groups a user belongs to
     * Get user groups
     */
    async groupsV1UsersUserIdGroupsGetRaw(requestParameters: GroupsV1UsersUserIdGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserGroupsResponse>> {
        const requestOptions = await this.groupsV1UsersUserIdGroupsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserGroupsResponseFromJSON(jsonValue));
    }

    /**
     * Returns all groups a user belongs to
     * Get user groups
     */
    async groupsV1UsersUserIdGroupsGet(requestParameters: GroupsV1UsersUserIdGroupsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserGroupsResponse> {
        const response = await this.groupsV1UsersUserIdGroupsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GroupsV1UsersUserIdGroupsGetStatusEnum = {
    ACTIVE: 'active',
    PENDING: 'pending',
    REJECTED: 'rejected'
} as const;
export type GroupsV1UsersUserIdGroupsGetStatusEnum = typeof GroupsV1UsersUserIdGroupsGetStatusEnum[keyof typeof GroupsV1UsersUserIdGroupsGetStatusEnum];
