/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteVideoResponse,
  StorageV1UploadUrlPost400Response,
  VideoSignedUrlRequest,
  VideoSignedUrlResponse,
  VideoStatus,
  VideoUploadRequest,
  VideoUploadResponse,
} from '../models/index';
import {
    DeleteVideoResponseFromJSON,
    DeleteVideoResponseToJSON,
    StorageV1UploadUrlPost400ResponseFromJSON,
    StorageV1UploadUrlPost400ResponseToJSON,
    VideoSignedUrlRequestFromJSON,
    VideoSignedUrlRequestToJSON,
    VideoSignedUrlResponseFromJSON,
    VideoSignedUrlResponseToJSON,
    VideoStatusFromJSON,
    VideoStatusToJSON,
    VideoUploadRequestFromJSON,
    VideoUploadRequestToJSON,
    VideoUploadResponseFromJSON,
    VideoUploadResponseToJSON,
} from '../models/index';

export interface StorageV1VideoSignedUrlPostRequest {
    videoSignedUrlRequest?: VideoSignedUrlRequest;
}

export interface StorageV1VideoUploadPostRequest {
    videoUploadRequest?: VideoUploadRequest;
}

export interface StorageV1VideoVideoIdDeleteRequest {
    videoId: string;
}

export interface StorageV1VideoVideoIdGetRequest {
    videoId: string;
}

/**
 * VideoApi - interface
 * 
 * @export
 * @interface VideoApiInterface
 */
export interface VideoApiInterface {
    /**
     * Creates request options for storageV1VideoSignedUrlPost without sending the request
     * @param {VideoSignedUrlRequest} [videoSignedUrlRequest] 
     * @throws {RequiredError}
     * @memberof VideoApiInterface
     */
    storageV1VideoSignedUrlPostRequestOpts(requestParameters: StorageV1VideoSignedUrlPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Generate a signed URL for video playback (required if requireSignedUrls is true)
     * @summary Get signed playback URL
     * @param {VideoSignedUrlRequest} [videoSignedUrlRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideoApiInterface
     */
    storageV1VideoSignedUrlPostRaw(requestParameters: StorageV1VideoSignedUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoSignedUrlResponse>>;

    /**
     * Generate a signed URL for video playback (required if requireSignedUrls is true)
     * Get signed playback URL
     */
    storageV1VideoSignedUrlPost(requestParameters: StorageV1VideoSignedUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoSignedUrlResponse>;

    /**
     * Creates request options for storageV1VideoUploadPost without sending the request
     * @param {VideoUploadRequest} [videoUploadRequest] 
     * @throws {RequiredError}
     * @memberof VideoApiInterface
     */
    storageV1VideoUploadPostRequestOpts(requestParameters: StorageV1VideoUploadPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a video upload session using Cloudflare Stream TUS protocol
     * @summary Create video upload
     * @param {VideoUploadRequest} [videoUploadRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideoApiInterface
     */
    storageV1VideoUploadPostRaw(requestParameters: StorageV1VideoUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoUploadResponse>>;

    /**
     * Create a video upload session using Cloudflare Stream TUS protocol
     * Create video upload
     */
    storageV1VideoUploadPost(requestParameters: StorageV1VideoUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoUploadResponse>;

    /**
     * Creates request options for storageV1VideoVideoIdDelete without sending the request
     * @param {string} videoId 
     * @throws {RequiredError}
     * @memberof VideoApiInterface
     */
    storageV1VideoVideoIdDeleteRequestOpts(requestParameters: StorageV1VideoVideoIdDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete a video from Cloudflare Stream
     * @summary Delete video
     * @param {string} videoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideoApiInterface
     */
    storageV1VideoVideoIdDeleteRaw(requestParameters: StorageV1VideoVideoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteVideoResponse>>;

    /**
     * Delete a video from Cloudflare Stream
     * Delete video
     */
    storageV1VideoVideoIdDelete(requestParameters: StorageV1VideoVideoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteVideoResponse>;

    /**
     * Creates request options for storageV1VideoVideoIdGet without sending the request
     * @param {string} videoId 
     * @throws {RequiredError}
     * @memberof VideoApiInterface
     */
    storageV1VideoVideoIdGetRequestOpts(requestParameters: StorageV1VideoVideoIdGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Get the current status and metadata of a video
     * @summary Get video status
     * @param {string} videoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideoApiInterface
     */
    storageV1VideoVideoIdGetRaw(requestParameters: StorageV1VideoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoStatus>>;

    /**
     * Get the current status and metadata of a video
     * Get video status
     */
    storageV1VideoVideoIdGet(requestParameters: StorageV1VideoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoStatus>;

}

/**
 * 
 */
export class VideoApi extends runtime.BaseAPI implements VideoApiInterface {

    /**
     * Creates request options for storageV1VideoSignedUrlPost without sending the request
     */
    async storageV1VideoSignedUrlPostRequestOpts(requestParameters: StorageV1VideoSignedUrlPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/video/signed-url`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoSignedUrlRequestToJSON(requestParameters['videoSignedUrlRequest']),
        };
    }

    /**
     * Generate a signed URL for video playback (required if requireSignedUrls is true)
     * Get signed playback URL
     */
    async storageV1VideoSignedUrlPostRaw(requestParameters: StorageV1VideoSignedUrlPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoSignedUrlResponse>> {
        const requestOptions = await this.storageV1VideoSignedUrlPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoSignedUrlResponseFromJSON(jsonValue));
    }

    /**
     * Generate a signed URL for video playback (required if requireSignedUrls is true)
     * Get signed playback URL
     */
    async storageV1VideoSignedUrlPost(requestParameters: StorageV1VideoSignedUrlPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoSignedUrlResponse> {
        const response = await this.storageV1VideoSignedUrlPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storageV1VideoUploadPost without sending the request
     */
    async storageV1VideoUploadPostRequestOpts(requestParameters: StorageV1VideoUploadPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/video/upload`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoUploadRequestToJSON(requestParameters['videoUploadRequest']),
        };
    }

    /**
     * Create a video upload session using Cloudflare Stream TUS protocol
     * Create video upload
     */
    async storageV1VideoUploadPostRaw(requestParameters: StorageV1VideoUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoUploadResponse>> {
        const requestOptions = await this.storageV1VideoUploadPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoUploadResponseFromJSON(jsonValue));
    }

    /**
     * Create a video upload session using Cloudflare Stream TUS protocol
     * Create video upload
     */
    async storageV1VideoUploadPost(requestParameters: StorageV1VideoUploadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoUploadResponse> {
        const response = await this.storageV1VideoUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storageV1VideoVideoIdDelete without sending the request
     */
    async storageV1VideoVideoIdDeleteRequestOpts(requestParameters: StorageV1VideoVideoIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling storageV1VideoVideoIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/video/{videoId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a video from Cloudflare Stream
     * Delete video
     */
    async storageV1VideoVideoIdDeleteRaw(requestParameters: StorageV1VideoVideoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteVideoResponse>> {
        const requestOptions = await this.storageV1VideoVideoIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteVideoResponseFromJSON(jsonValue));
    }

    /**
     * Delete a video from Cloudflare Stream
     * Delete video
     */
    async storageV1VideoVideoIdDelete(requestParameters: StorageV1VideoVideoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteVideoResponse> {
        const response = await this.storageV1VideoVideoIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for storageV1VideoVideoIdGet without sending the request
     */
    async storageV1VideoVideoIdGetRequestOpts(requestParameters: StorageV1VideoVideoIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling storageV1VideoVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage/v1/video/{videoId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current status and metadata of a video
     * Get video status
     */
    async storageV1VideoVideoIdGetRaw(requestParameters: StorageV1VideoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoStatus>> {
        const requestOptions = await this.storageV1VideoVideoIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoStatusFromJSON(jsonValue));
    }

    /**
     * Get the current status and metadata of a video
     * Get video status
     */
    async storageV1VideoVideoIdGet(requestParameters: StorageV1VideoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoStatus> {
        const response = await this.storageV1VideoVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
