/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AwardXpRequest,
  AwardXpResponse,
  GamificationErrorResponse,
  UserXpResponse,
} from '../models/index';
import {
    AwardXpRequestFromJSON,
    AwardXpRequestToJSON,
    AwardXpResponseFromJSON,
    AwardXpResponseToJSON,
    GamificationErrorResponseFromJSON,
    GamificationErrorResponseToJSON,
    UserXpResponseFromJSON,
    UserXpResponseToJSON,
} from '../models/index';

export interface GamificationV1XpGetRequest {
    userId: string;
}

export interface GamificationV1XpPostRequest {
    awardXpRequest?: AwardXpRequest;
}

/**
 * XPApi - interface
 * 
 * @export
 * @interface XPApiInterface
 */
export interface XPApiInterface {
    /**
     * Creates request options for gamificationV1XpGet without sending the request
     * @param {string} userId 
     * @throws {RequiredError}
     * @memberof XPApiInterface
     */
    gamificationV1XpGetRequestOpts(requestParameters: GamificationV1XpGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns user\'s XP total, level, and progress
     * @summary Get user XP
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof XPApiInterface
     */
    gamificationV1XpGetRaw(requestParameters: GamificationV1XpGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserXpResponse>>;

    /**
     * Returns user\'s XP total, level, and progress
     * Get user XP
     */
    gamificationV1XpGet(requestParameters: GamificationV1XpGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserXpResponse>;

    /**
     * Creates request options for gamificationV1XpPost without sending the request
     * @param {AwardXpRequest} [awardXpRequest] 
     * @throws {RequiredError}
     * @memberof XPApiInterface
     */
    gamificationV1XpPostRequestOpts(requestParameters: GamificationV1XpPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Awards XP to a user, updates totals, checks for badge unlocks
     * @summary Award XP
     * @param {AwardXpRequest} [awardXpRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof XPApiInterface
     */
    gamificationV1XpPostRaw(requestParameters: GamificationV1XpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AwardXpResponse>>;

    /**
     * Awards XP to a user, updates totals, checks for badge unlocks
     * Award XP
     */
    gamificationV1XpPost(requestParameters: GamificationV1XpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AwardXpResponse>;

}

/**
 * 
 */
export class XPApi extends runtime.BaseAPI implements XPApiInterface {

    /**
     * Creates request options for gamificationV1XpGet without sending the request
     */
    async gamificationV1XpGetRequestOpts(requestParameters: GamificationV1XpGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling gamificationV1XpGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/xp`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns user\'s XP total, level, and progress
     * Get user XP
     */
    async gamificationV1XpGetRaw(requestParameters: GamificationV1XpGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserXpResponse>> {
        const requestOptions = await this.gamificationV1XpGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserXpResponseFromJSON(jsonValue));
    }

    /**
     * Returns user\'s XP total, level, and progress
     * Get user XP
     */
    async gamificationV1XpGet(requestParameters: GamificationV1XpGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserXpResponse> {
        const response = await this.gamificationV1XpGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for gamificationV1XpPost without sending the request
     */
    async gamificationV1XpPostRequestOpts(requestParameters: GamificationV1XpPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/gamification/v1/xp`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AwardXpRequestToJSON(requestParameters['awardXpRequest']),
        };
    }

    /**
     * Awards XP to a user, updates totals, checks for badge unlocks
     * Award XP
     */
    async gamificationV1XpPostRaw(requestParameters: GamificationV1XpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AwardXpResponse>> {
        const requestOptions = await this.gamificationV1XpPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AwardXpResponseFromJSON(jsonValue));
    }

    /**
     * Awards XP to a user, updates totals, checks for badge unlocks
     * Award XP
     */
    async gamificationV1XpPost(requestParameters: GamificationV1XpPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AwardXpResponse> {
        const response = await this.gamificationV1XpPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
