/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination info
 * @export
 * @interface ActivityListResponsePagination
 */
export interface ActivityListResponsePagination {
    /**
     * Total number of activities
     * @type {number}
     * @memberof ActivityListResponsePagination
     */
    total: number;
    /**
     * Maximum activities returned
     * @type {number}
     * @memberof ActivityListResponsePagination
     */
    limit: number;
    /**
     * Offset from start
     * @type {number}
     * @memberof ActivityListResponsePagination
     */
    offset: number;
    /**
     * Whether there are more activities
     * @type {boolean}
     * @memberof ActivityListResponsePagination
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the ActivityListResponsePagination interface.
 */
export function instanceOfActivityListResponsePagination(value: object): value is ActivityListResponsePagination {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function ActivityListResponsePaginationFromJSON(json: any): ActivityListResponsePagination {
    return ActivityListResponsePaginationFromJSONTyped(json, false);
}

export function ActivityListResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityListResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
        'hasMore': json['hasMore'],
    };
}

export function ActivityListResponsePaginationToJSON(json: any): ActivityListResponsePagination {
    return ActivityListResponsePaginationToJSONTyped(json, false);
}

export function ActivityListResponsePaginationToJSONTyped(value?: ActivityListResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
        'hasMore': value['hasMore'],
    };
}

