/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityType
 */
export interface ActivityType {
    /**
     * Activity type ID
     * @type {string}
     * @memberof ActivityType
     */
    id: string;
    /**
     * Unique code for this activity type
     * @type {string}
     * @memberof ActivityType
     */
    code: string;
    /**
     * Display name
     * @type {string}
     * @memberof ActivityType
     */
    name: string;
    /**
     * Activity type description
     * @type {string}
     * @memberof ActivityType
     */
    description: string | null;
    /**
     * Category (learn, grow, help, security)
     * @type {string}
     * @memberof ActivityType
     */
    category: string;
    /**
     * Icon emoji or identifier
     * @type {string}
     * @memberof ActivityType
     */
    icon: string | null;
    /**
     * Unit of measurement (minutes, count, pages)
     * @type {string}
     * @memberof ActivityType
     */
    unit: string;
    /**
     * How to aggregate values
     * @type {string}
     * @memberof ActivityType
     */
    aggregation: ActivityTypeAggregationEnum;
    /**
     * XP awarded per unit of activity
     * @type {number}
     * @memberof ActivityType
     */
    xpPerUnit: number;
    /**
     * Whether this activity counts toward streaks
     * @type {boolean}
     * @memberof ActivityType
     */
    streakEligible: boolean;
    /**
     * Whether this activity type is active
     * @type {boolean}
     * @memberof ActivityType
     */
    isActive: boolean;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof ActivityType
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ActivityTypeAggregationEnum = {
    SUM: 'sum',
    COUNT: 'count',
    MAX: 'max',
    AVG: 'avg'
} as const;
export type ActivityTypeAggregationEnum = typeof ActivityTypeAggregationEnum[keyof typeof ActivityTypeAggregationEnum];


/**
 * Check if a given object implements the ActivityType interface.
 */
export function instanceOfActivityType(value: object): value is ActivityType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('aggregation' in value) || value['aggregation'] === undefined) return false;
    if (!('xpPerUnit' in value) || value['xpPerUnit'] === undefined) return false;
    if (!('streakEligible' in value) || value['streakEligible'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ActivityTypeFromJSON(json: any): ActivityType {
    return ActivityTypeFromJSONTyped(json, false);
}

export function ActivityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
        'category': json['category'],
        'icon': json['icon'],
        'unit': json['unit'],
        'aggregation': json['aggregation'],
        'xpPerUnit': json['xpPerUnit'],
        'streakEligible': json['streakEligible'],
        'isActive': json['isActive'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ActivityTypeToJSON(json: any): ActivityType {
    return ActivityTypeToJSONTyped(json, false);
}

export function ActivityTypeToJSONTyped(value?: ActivityType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'category': value['category'],
        'icon': value['icon'],
        'unit': value['unit'],
        'aggregation': value['aggregation'],
        'xpPerUnit': value['xpPerUnit'],
        'streakEligible': value['streakEligible'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

