/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityType } from './ActivityType';
import {
    ActivityTypeFromJSON,
    ActivityTypeFromJSONTyped,
    ActivityTypeToJSON,
    ActivityTypeToJSONTyped,
} from './ActivityType';

/**
 * 
 * @export
 * @interface ActivityTypeListResponse
 */
export interface ActivityTypeListResponse {
    /**
     * List of activity types
     * @type {Array<ActivityType>}
     * @memberof ActivityTypeListResponse
     */
    activityTypes: Array<ActivityType>;
}

/**
 * Check if a given object implements the ActivityTypeListResponse interface.
 */
export function instanceOfActivityTypeListResponse(value: object): value is ActivityTypeListResponse {
    if (!('activityTypes' in value) || value['activityTypes'] === undefined) return false;
    return true;
}

export function ActivityTypeListResponseFromJSON(json: any): ActivityTypeListResponse {
    return ActivityTypeListResponseFromJSONTyped(json, false);
}

export function ActivityTypeListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityTypeListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activityTypes': ((json['activityTypes'] as Array<any>).map(ActivityTypeFromJSON)),
    };
}

export function ActivityTypeListResponseToJSON(json: any): ActivityTypeListResponse {
    return ActivityTypeListResponseToJSONTyped(json, false);
}

export function ActivityTypeListResponseToJSONTyped(value?: ActivityTypeListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activityTypes': ((value['activityTypes'] as Array<any>).map(ActivityTypeToJSON)),
    };
}

