/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * Activity ID
     * @type {string}
     * @memberof Activity
     */
    id: string;
    /**
     * User who performed the activity
     * @type {string}
     * @memberof Activity
     */
    userId: string;
    /**
     * Activity type code
     * @type {string}
     * @memberof Activity
     */
    activityType: string;
    /**
     * Activity value (minutes, count, etc.)
     * @type {number}
     * @memberof Activity
     */
    value: number;
    /**
     * Activity-specific data
     * @type {{ [key: string]: any | null; }}
     * @memberof Activity
     */
    metadata?: { [key: string]: any | null; };
    /**
     * User notes
     * @type {string}
     * @memberof Activity
     */
    notes: string | null;
    /**
     * When the activity was performed
     * @type {Date}
     * @memberof Activity
     */
    performedAt: Date;
    /**
     * When the activity was recorded
     * @type {Date}
     * @memberof Activity
     */
    createdAt: Date;
    /**
     * XP awarded for this activity
     * @type {number}
     * @memberof Activity
     */
    xpAwarded: number;
}

/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('activityType' in value) || value['activityType'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('performedAt' in value) || value['performedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('xpAwarded' in value) || value['xpAwarded'] === undefined) return false;
    return true;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'activityType': json['activityType'],
        'value': json['value'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'notes': json['notes'],
        'performedAt': (new Date(json['performedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'xpAwarded': json['xpAwarded'],
    };
}

export function ActivityToJSON(json: any): Activity {
    return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(value?: Activity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'activityType': value['activityType'],
        'value': value['value'],
        'metadata': value['metadata'],
        'notes': value['notes'],
        'performedAt': value['performedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'xpAwarded': value['xpAwarded'],
    };
}

