/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Stop sequences
 * @export
 * @interface AiGatewayChatCompletionRequestStop
 */
export interface AiGatewayChatCompletionRequestStop {
}

/**
 * Check if a given object implements the AiGatewayChatCompletionRequestStop interface.
 */
export function instanceOfAiGatewayChatCompletionRequestStop(value: object): value is AiGatewayChatCompletionRequestStop {
    return true;
}

export function AiGatewayChatCompletionRequestStopFromJSON(json: any): AiGatewayChatCompletionRequestStop {
    return AiGatewayChatCompletionRequestStopFromJSONTyped(json, false);
}

export function AiGatewayChatCompletionRequestStopFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiGatewayChatCompletionRequestStop {
    return json;
}

export function AiGatewayChatCompletionRequestStopToJSON(json: any): AiGatewayChatCompletionRequestStop {
    return AiGatewayChatCompletionRequestStopToJSONTyped(json, false);
}

export function AiGatewayChatCompletionRequestStopToJSONTyped(value?: AiGatewayChatCompletionRequestStop | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

