/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiGatewayErrorResponseError
 */
export interface AiGatewayErrorResponseError {
    /**
     * Error code
     * @type {string}
     * @memberof AiGatewayErrorResponseError
     */
    code: string;
    /**
     * Error message
     * @type {string}
     * @memberof AiGatewayErrorResponseError
     */
    message: string;
    /**
     * Additional error details
     * @type {{ [key: string]: any; }}
     * @memberof AiGatewayErrorResponseError
     */
    details?: { [key: string]: any; };
}

/**
 * Check if a given object implements the AiGatewayErrorResponseError interface.
 */
export function instanceOfAiGatewayErrorResponseError(value: object): value is AiGatewayErrorResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AiGatewayErrorResponseErrorFromJSON(json: any): AiGatewayErrorResponseError {
    return AiGatewayErrorResponseErrorFromJSONTyped(json, false);
}

export function AiGatewayErrorResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiGatewayErrorResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function AiGatewayErrorResponseErrorToJSON(json: any): AiGatewayErrorResponseError {
    return AiGatewayErrorResponseErrorToJSONTyped(json, false);
}

export function AiGatewayErrorResponseErrorToJSONTyped(value?: AiGatewayErrorResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'details': value['details'],
    };
}

