/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiGatewayChatCompletionResponseUsage
 */
export interface AiGatewayChatCompletionResponseUsage {
    /**
     * 
     * @type {number}
     * @memberof AiGatewayChatCompletionResponseUsage
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof AiGatewayChatCompletionResponseUsage
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof AiGatewayChatCompletionResponseUsage
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the AiGatewayChatCompletionResponseUsage interface.
 */
export function instanceOfAiGatewayChatCompletionResponseUsage(value: object): value is AiGatewayChatCompletionResponseUsage {
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function AiGatewayChatCompletionResponseUsageFromJSON(json: any): AiGatewayChatCompletionResponseUsage {
    return AiGatewayChatCompletionResponseUsageFromJSONTyped(json, false);
}

export function AiGatewayChatCompletionResponseUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiGatewayChatCompletionResponseUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'promptTokens': json['prompt_tokens'],
        'completionTokens': json['completion_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function AiGatewayChatCompletionResponseUsageToJSON(json: any): AiGatewayChatCompletionResponseUsage {
    return AiGatewayChatCompletionResponseUsageToJSONTyped(json, false);
}

export function AiGatewayChatCompletionResponseUsageToJSONTyped(value?: AiGatewayChatCompletionResponseUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt_tokens': value['promptTokens'],
        'completion_tokens': value['completionTokens'],
        'total_tokens': value['totalTokens'],
    };
}

