/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiGatewayChatMessage } from './AiGatewayChatMessage';
import {
    AiGatewayChatMessageFromJSON,
    AiGatewayChatMessageFromJSONTyped,
    AiGatewayChatMessageToJSON,
    AiGatewayChatMessageToJSONTyped,
} from './AiGatewayChatMessage';

/**
 * 
 * @export
 * @interface AiGatewayChatCompletionResponseChoicesInner
 */
export interface AiGatewayChatCompletionResponseChoicesInner {
    /**
     * 
     * @type {number}
     * @memberof AiGatewayChatCompletionResponseChoicesInner
     */
    index: number;
    /**
     * 
     * @type {AiGatewayChatMessage}
     * @memberof AiGatewayChatCompletionResponseChoicesInner
     */
    message: AiGatewayChatMessage;
    /**
     * 
     * @type {string}
     * @memberof AiGatewayChatCompletionResponseChoicesInner
     */
    finishReason: string;
    /**
     * 
     * @type {any}
     * @memberof AiGatewayChatCompletionResponseChoicesInner
     */
    logprobs?: any | null;
}

/**
 * Check if a given object implements the AiGatewayChatCompletionResponseChoicesInner interface.
 */
export function instanceOfAiGatewayChatCompletionResponseChoicesInner(value: object): value is AiGatewayChatCompletionResponseChoicesInner {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('finishReason' in value) || value['finishReason'] === undefined) return false;
    return true;
}

export function AiGatewayChatCompletionResponseChoicesInnerFromJSON(json: any): AiGatewayChatCompletionResponseChoicesInner {
    return AiGatewayChatCompletionResponseChoicesInnerFromJSONTyped(json, false);
}

export function AiGatewayChatCompletionResponseChoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiGatewayChatCompletionResponseChoicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'message': AiGatewayChatMessageFromJSON(json['message']),
        'finishReason': json['finish_reason'],
        'logprobs': json['logprobs'] == null ? undefined : json['logprobs'],
    };
}

export function AiGatewayChatCompletionResponseChoicesInnerToJSON(json: any): AiGatewayChatCompletionResponseChoicesInner {
    return AiGatewayChatCompletionResponseChoicesInnerToJSONTyped(json, false);
}

export function AiGatewayChatCompletionResponseChoicesInnerToJSONTyped(value?: AiGatewayChatCompletionResponseChoicesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'message': AiGatewayChatMessageToJSON(value['message']),
        'finish_reason': value['finishReason'],
        'logprobs': value['logprobs'],
    };
}

