/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response format (text or json_object)
 * @export
 * @interface AiGatewayChatCompletionRequestResponseFormat
 */
export interface AiGatewayChatCompletionRequestResponseFormat {
    /**
     * 
     * @type {string}
     * @memberof AiGatewayChatCompletionRequestResponseFormat
     */
    type: AiGatewayChatCompletionRequestResponseFormatTypeEnum;
}


/**
 * @export
 */
export const AiGatewayChatCompletionRequestResponseFormatTypeEnum = {
    TEXT: 'text',
    JSON_OBJECT: 'json_object'
} as const;
export type AiGatewayChatCompletionRequestResponseFormatTypeEnum = typeof AiGatewayChatCompletionRequestResponseFormatTypeEnum[keyof typeof AiGatewayChatCompletionRequestResponseFormatTypeEnum];


/**
 * Check if a given object implements the AiGatewayChatCompletionRequestResponseFormat interface.
 */
export function instanceOfAiGatewayChatCompletionRequestResponseFormat(value: object): value is AiGatewayChatCompletionRequestResponseFormat {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AiGatewayChatCompletionRequestResponseFormatFromJSON(json: any): AiGatewayChatCompletionRequestResponseFormat {
    return AiGatewayChatCompletionRequestResponseFormatFromJSONTyped(json, false);
}

export function AiGatewayChatCompletionRequestResponseFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiGatewayChatCompletionRequestResponseFormat {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function AiGatewayChatCompletionRequestResponseFormatToJSON(json: any): AiGatewayChatCompletionRequestResponseFormat {
    return AiGatewayChatCompletionRequestResponseFormatToJSONTyped(json, false);
}

export function AiGatewayChatCompletionRequestResponseFormatToJSONTyped(value?: AiGatewayChatCompletionRequestResponseFormat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

