/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiGatewayChatCompletionResponseUsage } from './AiGatewayChatCompletionResponseUsage';
import {
    AiGatewayChatCompletionResponseUsageFromJSON,
    AiGatewayChatCompletionResponseUsageFromJSONTyped,
    AiGatewayChatCompletionResponseUsageToJSON,
    AiGatewayChatCompletionResponseUsageToJSONTyped,
} from './AiGatewayChatCompletionResponseUsage';
import type { AiGatewayChatCompletionResponseChoicesInner } from './AiGatewayChatCompletionResponseChoicesInner';
import {
    AiGatewayChatCompletionResponseChoicesInnerFromJSON,
    AiGatewayChatCompletionResponseChoicesInnerFromJSONTyped,
    AiGatewayChatCompletionResponseChoicesInnerToJSON,
    AiGatewayChatCompletionResponseChoicesInnerToJSONTyped,
} from './AiGatewayChatCompletionResponseChoicesInner';

/**
 * 
 * @export
 * @interface AiGatewayChatCompletionResponse
 */
export interface AiGatewayChatCompletionResponse {
    /**
     * 
     * @type {string}
     * @memberof AiGatewayChatCompletionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AiGatewayChatCompletionResponse
     */
    object: string;
    /**
     * 
     * @type {number}
     * @memberof AiGatewayChatCompletionResponse
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof AiGatewayChatCompletionResponse
     */
    model: string;
    /**
     * 
     * @type {Array<AiGatewayChatCompletionResponseChoicesInner>}
     * @memberof AiGatewayChatCompletionResponse
     */
    choices: Array<AiGatewayChatCompletionResponseChoicesInner>;
    /**
     * 
     * @type {AiGatewayChatCompletionResponseUsage}
     * @memberof AiGatewayChatCompletionResponse
     */
    usage?: AiGatewayChatCompletionResponseUsage;
    /**
     * 
     * @type {string}
     * @memberof AiGatewayChatCompletionResponse
     */
    systemFingerprint?: string;
}

/**
 * Check if a given object implements the AiGatewayChatCompletionResponse interface.
 */
export function instanceOfAiGatewayChatCompletionResponse(value: object): value is AiGatewayChatCompletionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    return true;
}

export function AiGatewayChatCompletionResponseFromJSON(json: any): AiGatewayChatCompletionResponse {
    return AiGatewayChatCompletionResponseFromJSONTyped(json, false);
}

export function AiGatewayChatCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiGatewayChatCompletionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'created': json['created'],
        'model': json['model'],
        'choices': ((json['choices'] as Array<any>).map(AiGatewayChatCompletionResponseChoicesInnerFromJSON)),
        'usage': json['usage'] == null ? undefined : AiGatewayChatCompletionResponseUsageFromJSON(json['usage']),
        'systemFingerprint': json['system_fingerprint'] == null ? undefined : json['system_fingerprint'],
    };
}

export function AiGatewayChatCompletionResponseToJSON(json: any): AiGatewayChatCompletionResponse {
    return AiGatewayChatCompletionResponseToJSONTyped(json, false);
}

export function AiGatewayChatCompletionResponseToJSONTyped(value?: AiGatewayChatCompletionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'model': value['model'],
        'choices': ((value['choices'] as Array<any>).map(AiGatewayChatCompletionResponseChoicesInnerToJSON)),
        'usage': AiGatewayChatCompletionResponseUsageToJSON(value['usage']),
        'system_fingerprint': value['systemFingerprint'],
    };
}

