/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiGatewayHealthzResponse
 */
export interface AiGatewayHealthzResponse {
    /**
     * Health status indicator
     * @type {string}
     * @memberof AiGatewayHealthzResponse
     */
    status: AiGatewayHealthzResponseStatusEnum;
    /**
     * Service name
     * @type {string}
     * @memberof AiGatewayHealthzResponse
     */
    service: string;
    /**
     * Deployment environment
     * @type {string}
     * @memberof AiGatewayHealthzResponse
     */
    environment: string;
    /**
     * Service version
     * @type {string}
     * @memberof AiGatewayHealthzResponse
     */
    version: string;
    /**
     * Current server time in ISO 8601 format
     * @type {Date}
     * @memberof AiGatewayHealthzResponse
     */
    timestamp: Date;
    /**
     * Service uptime in seconds (if available)
     * @type {number}
     * @memberof AiGatewayHealthzResponse
     */
    uptime?: number;
}


/**
 * @export
 */
export const AiGatewayHealthzResponseStatusEnum = {
    OK: 'ok'
} as const;
export type AiGatewayHealthzResponseStatusEnum = typeof AiGatewayHealthzResponseStatusEnum[keyof typeof AiGatewayHealthzResponseStatusEnum];


/**
 * Check if a given object implements the AiGatewayHealthzResponse interface.
 */
export function instanceOfAiGatewayHealthzResponse(value: object): value is AiGatewayHealthzResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function AiGatewayHealthzResponseFromJSON(json: any): AiGatewayHealthzResponse {
    return AiGatewayHealthzResponseFromJSONTyped(json, false);
}

export function AiGatewayHealthzResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiGatewayHealthzResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'service': json['service'],
        'environment': json['environment'],
        'version': json['version'],
        'timestamp': (new Date(json['timestamp'])),
        'uptime': json['uptime'] == null ? undefined : json['uptime'],
    };
}

export function AiGatewayHealthzResponseToJSON(json: any): AiGatewayHealthzResponse {
    return AiGatewayHealthzResponseToJSONTyped(json, false);
}

export function AiGatewayHealthzResponseToJSONTyped(value?: AiGatewayHealthzResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'service': value['service'],
        'environment': value['environment'],
        'version': value['version'],
        'timestamp': value['timestamp'].toISOString(),
        'uptime': value['uptime'],
    };
}

