/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiGatewayErrorResponseError } from './AiGatewayErrorResponseError';
import {
    AiGatewayErrorResponseErrorFromJSON,
    AiGatewayErrorResponseErrorFromJSONTyped,
    AiGatewayErrorResponseErrorToJSON,
    AiGatewayErrorResponseErrorToJSONTyped,
} from './AiGatewayErrorResponseError';

/**
 * 
 * @export
 * @interface AiGatewayErrorResponse
 */
export interface AiGatewayErrorResponse {
    /**
     * 
     * @type {AiGatewayErrorResponseError}
     * @memberof AiGatewayErrorResponse
     */
    error: AiGatewayErrorResponseError;
}

/**
 * Check if a given object implements the AiGatewayErrorResponse interface.
 */
export function instanceOfAiGatewayErrorResponse(value: object): value is AiGatewayErrorResponse {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AiGatewayErrorResponseFromJSON(json: any): AiGatewayErrorResponse {
    return AiGatewayErrorResponseFromJSONTyped(json, false);
}

export function AiGatewayErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiGatewayErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': AiGatewayErrorResponseErrorFromJSON(json['error']),
    };
}

export function AiGatewayErrorResponseToJSON(json: any): AiGatewayErrorResponse {
    return AiGatewayErrorResponseToJSONTyped(json, false);
}

export function AiGatewayErrorResponseToJSONTyped(value?: AiGatewayErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': AiGatewayErrorResponseErrorToJSON(value['error']),
    };
}

