/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiV1ChatCompletionsPost400ResponseAllOfError
 */
export interface AiV1ChatCompletionsPost400ResponseAllOfError {
    /**
     * Error code
     * @type {string}
     * @memberof AiV1ChatCompletionsPost400ResponseAllOfError
     */
    code: string;
    /**
     * Error message
     * @type {string}
     * @memberof AiV1ChatCompletionsPost400ResponseAllOfError
     */
    message: string;
    /**
     * Additional error details
     * @type {{ [key: string]: any | null; }}
     * @memberof AiV1ChatCompletionsPost400ResponseAllOfError
     */
    details?: { [key: string]: any | null; };
}

/**
 * Check if a given object implements the AiV1ChatCompletionsPost400ResponseAllOfError interface.
 */
export function instanceOfAiV1ChatCompletionsPost400ResponseAllOfError(value: object): value is AiV1ChatCompletionsPost400ResponseAllOfError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AiV1ChatCompletionsPost400ResponseAllOfErrorFromJSON(json: any): AiV1ChatCompletionsPost400ResponseAllOfError {
    return AiV1ChatCompletionsPost400ResponseAllOfErrorFromJSONTyped(json, false);
}

export function AiV1ChatCompletionsPost400ResponseAllOfErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiV1ChatCompletionsPost400ResponseAllOfError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function AiV1ChatCompletionsPost400ResponseAllOfErrorToJSON(json: any): AiV1ChatCompletionsPost400ResponseAllOfError {
    return AiV1ChatCompletionsPost400ResponseAllOfErrorToJSONTyped(json, false);
}

export function AiV1ChatCompletionsPost400ResponseAllOfErrorToJSONTyped(value?: AiV1ChatCompletionsPost400ResponseAllOfError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'details': value['details'],
    };
}

