/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AwardBadgeRequest
 */
export interface AwardBadgeRequest {
    /**
     * User to award badge to
     * @type {string}
     * @memberof AwardBadgeRequest
     */
    userId: string;
    /**
     * Badge code to award
     * @type {string}
     * @memberof AwardBadgeRequest
     */
    badgeCode: string;
    /**
     * Context about how badge was earned
     * @type {{ [key: string]: any | null; }}
     * @memberof AwardBadgeRequest
     */
    metadata?: { [key: string]: any | null; };
}

/**
 * Check if a given object implements the AwardBadgeRequest interface.
 */
export function instanceOfAwardBadgeRequest(value: object): value is AwardBadgeRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('badgeCode' in value) || value['badgeCode'] === undefined) return false;
    return true;
}

export function AwardBadgeRequestFromJSON(json: any): AwardBadgeRequest {
    return AwardBadgeRequestFromJSONTyped(json, false);
}

export function AwardBadgeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwardBadgeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'badgeCode': json['badgeCode'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function AwardBadgeRequestToJSON(json: any): AwardBadgeRequest {
    return AwardBadgeRequestToJSONTyped(json, false);
}

export function AwardBadgeRequestToJSONTyped(value?: AwardBadgeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'badgeCode': value['badgeCode'],
        'metadata': value['metadata'],
    };
}

