/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Badge
 */
export interface Badge {
    /**
     * Badge ID
     * @type {string}
     * @memberof Badge
     */
    id: string;
    /**
     * Unique badge code
     * @type {string}
     * @memberof Badge
     */
    code: string;
    /**
     * Display name
     * @type {string}
     * @memberof Badge
     */
    name: string;
    /**
     * Badge description
     * @type {string}
     * @memberof Badge
     */
    description: string | null;
    /**
     * Badge icon
     * @type {string}
     * @memberof Badge
     */
    icon: string | null;
    /**
     * Badge category (achievement, streak, milestone, special)
     * @type {string}
     * @memberof Badge
     */
    category: string;
    /**
     * XP threshold for auto-award
     * @type {number}
     * @memberof Badge
     */
    xpThreshold: number | null;
    /**
     * Streak threshold for auto-award
     * @type {number}
     * @memberof Badge
     */
    streakThreshold: number | null;
    /**
     * Activity count threshold for auto-award
     * @type {number}
     * @memberof Badge
     */
    activityCountThreshold: number | null;
    /**
     * Whether badge can be earned
     * @type {boolean}
     * @memberof Badge
     */
    isActive: boolean;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof Badge
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Badge interface.
 */
export function instanceOfBadge(value: object): value is Badge {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('xpThreshold' in value) || value['xpThreshold'] === undefined) return false;
    if (!('streakThreshold' in value) || value['streakThreshold'] === undefined) return false;
    if (!('activityCountThreshold' in value) || value['activityCountThreshold'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function BadgeFromJSON(json: any): Badge {
    return BadgeFromJSONTyped(json, false);
}

export function BadgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Badge {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'description': json['description'],
        'icon': json['icon'],
        'category': json['category'],
        'xpThreshold': json['xpThreshold'],
        'streakThreshold': json['streakThreshold'],
        'activityCountThreshold': json['activityCountThreshold'],
        'isActive': json['isActive'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function BadgeToJSON(json: any): Badge {
    return BadgeToJSONTyped(json, false);
}

export function BadgeToJSONTyped(value?: Badge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'category': value['category'],
        'xpThreshold': value['xpThreshold'],
        'streakThreshold': value['streakThreshold'],
        'activityCountThreshold': value['activityCountThreshold'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

