/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Badge } from './Badge';
import {
    BadgeFromJSON,
    BadgeFromJSONTyped,
    BadgeToJSON,
    BadgeToJSONTyped,
} from './Badge';

/**
 * 
 * @export
 * @interface BadgeListResponse
 */
export interface BadgeListResponse {
    /**
     * List of badges
     * @type {Array<Badge>}
     * @memberof BadgeListResponse
     */
    badges: Array<Badge>;
}

/**
 * Check if a given object implements the BadgeListResponse interface.
 */
export function instanceOfBadgeListResponse(value: object): value is BadgeListResponse {
    if (!('badges' in value) || value['badges'] === undefined) return false;
    return true;
}

export function BadgeListResponseFromJSON(json: any): BadgeListResponse {
    return BadgeListResponseFromJSONTyped(json, false);
}

export function BadgeListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadgeListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'badges': ((json['badges'] as Array<any>).map(BadgeFromJSON)),
    };
}

export function BadgeListResponseToJSON(json: any): BadgeListResponse {
    return BadgeListResponseToJSONTyped(json, false);
}

export function BadgeListResponseToJSONTyped(value?: BadgeListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'badges': ((value['badges'] as Array<any>).map(BadgeToJSON)),
    };
}

