/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface ChatCompletionResponseChoicesInner
 */
export interface ChatCompletionResponseChoicesInner {
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionResponseChoicesInner
     */
    index: number;
    /**
     * 
     * @type {ChatMessage}
     * @memberof ChatCompletionResponseChoicesInner
     */
    message: ChatMessage;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponseChoicesInner
     */
    finishReason: string | null;
    /**
     * 
     * @type {any}
     * @memberof ChatCompletionResponseChoicesInner
     */
    logprobs?: any | null;
}

/**
 * Check if a given object implements the ChatCompletionResponseChoicesInner interface.
 */
export function instanceOfChatCompletionResponseChoicesInner(value: object): value is ChatCompletionResponseChoicesInner {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('finishReason' in value) || value['finishReason'] === undefined) return false;
    return true;
}

export function ChatCompletionResponseChoicesInnerFromJSON(json: any): ChatCompletionResponseChoicesInner {
    return ChatCompletionResponseChoicesInnerFromJSONTyped(json, false);
}

export function ChatCompletionResponseChoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseChoicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'message': ChatMessageFromJSON(json['message']),
        'finishReason': json['finish_reason'],
        'logprobs': json['logprobs'] == null ? undefined : json['logprobs'],
    };
}

export function ChatCompletionResponseChoicesInnerToJSON(json: any): ChatCompletionResponseChoicesInner {
    return ChatCompletionResponseChoicesInnerToJSONTyped(json, false);
}

export function ChatCompletionResponseChoicesInnerToJSONTyped(value?: ChatCompletionResponseChoicesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'message': ChatMessageToJSON(value['message']),
        'finish_reason': value['finishReason'],
        'logprobs': value['logprobs'],
    };
}

