/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatCompletionResponseUsage } from './ChatCompletionResponseUsage';
import {
    ChatCompletionResponseUsageFromJSON,
    ChatCompletionResponseUsageFromJSONTyped,
    ChatCompletionResponseUsageToJSON,
    ChatCompletionResponseUsageToJSONTyped,
} from './ChatCompletionResponseUsage';
import type { ChatCompletionResponseChoicesInner } from './ChatCompletionResponseChoicesInner';
import {
    ChatCompletionResponseChoicesInnerFromJSON,
    ChatCompletionResponseChoicesInnerFromJSONTyped,
    ChatCompletionResponseChoicesInnerToJSON,
    ChatCompletionResponseChoicesInnerToJSONTyped,
} from './ChatCompletionResponseChoicesInner';

/**
 * 
 * @export
 * @interface ChatCompletionResponse
 */
export interface ChatCompletionResponse {
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    object: string;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionResponse
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    model: string;
    /**
     * 
     * @type {Array<ChatCompletionResponseChoicesInner>}
     * @memberof ChatCompletionResponse
     */
    choices: Array<ChatCompletionResponseChoicesInner>;
    /**
     * 
     * @type {ChatCompletionResponseUsage}
     * @memberof ChatCompletionResponse
     */
    usage?: ChatCompletionResponseUsage;
    /**
     * 
     * @type {string}
     * @memberof ChatCompletionResponse
     */
    systemFingerprint?: string;
}

/**
 * Check if a given object implements the ChatCompletionResponse interface.
 */
export function instanceOfChatCompletionResponse(value: object): value is ChatCompletionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('choices' in value) || value['choices'] === undefined) return false;
    return true;
}

export function ChatCompletionResponseFromJSON(json: any): ChatCompletionResponse {
    return ChatCompletionResponseFromJSONTyped(json, false);
}

export function ChatCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'object': json['object'],
        'created': json['created'],
        'model': json['model'],
        'choices': ((json['choices'] as Array<any>).map(ChatCompletionResponseChoicesInnerFromJSON)),
        'usage': json['usage'] == null ? undefined : ChatCompletionResponseUsageFromJSON(json['usage']),
        'systemFingerprint': json['system_fingerprint'] == null ? undefined : json['system_fingerprint'],
    };
}

export function ChatCompletionResponseToJSON(json: any): ChatCompletionResponse {
    return ChatCompletionResponseToJSONTyped(json, false);
}

export function ChatCompletionResponseToJSONTyped(value?: ChatCompletionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object': value['object'],
        'created': value['created'],
        'model': value['model'],
        'choices': ((value['choices'] as Array<any>).map(ChatCompletionResponseChoicesInnerToJSON)),
        'usage': ChatCompletionResponseUsageToJSON(value['usage']),
        'system_fingerprint': value['systemFingerprint'],
    };
}

