/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatCompletionResponseUsage
 */
export interface ChatCompletionResponseUsage {
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionResponseUsage
     */
    promptTokens: number;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionResponseUsage
     */
    completionTokens: number;
    /**
     * 
     * @type {number}
     * @memberof ChatCompletionResponseUsage
     */
    totalTokens: number;
}

/**
 * Check if a given object implements the ChatCompletionResponseUsage interface.
 */
export function instanceOfChatCompletionResponseUsage(value: object): value is ChatCompletionResponseUsage {
    if (!('promptTokens' in value) || value['promptTokens'] === undefined) return false;
    if (!('completionTokens' in value) || value['completionTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function ChatCompletionResponseUsageFromJSON(json: any): ChatCompletionResponseUsage {
    return ChatCompletionResponseUsageFromJSONTyped(json, false);
}

export function ChatCompletionResponseUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatCompletionResponseUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'promptTokens': json['prompt_tokens'],
        'completionTokens': json['completion_tokens'],
        'totalTokens': json['total_tokens'],
    };
}

export function ChatCompletionResponseUsageToJSON(json: any): ChatCompletionResponseUsage {
    return ChatCompletionResponseUsageToJSONTyped(json, false);
}

export function ChatCompletionResponseUsageToJSONTyped(value?: ChatCompletionResponseUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt_tokens': value['promptTokens'],
        'completion_tokens': value['completionTokens'],
        'total_tokens': value['totalTokens'],
    };
}

