/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimManagedUserRequest
 */
export interface ClaimManagedUserRequest {
    /**
     * Platform user ID to claim
     * @type {string}
     * @memberof ClaimManagedUserRequest
     */
    userId: string;
    /**
     * User email address (lowercase)
     * @type {string}
     * @memberof ClaimManagedUserRequest
     */
    email: string;
    /**
     * Password (8-128 characters)
     * @type {string}
     * @memberof ClaimManagedUserRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ClaimManagedUserRequest interface.
 */
export function instanceOfClaimManagedUserRequest(value: object): value is ClaimManagedUserRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ClaimManagedUserRequestFromJSON(json: any): ClaimManagedUserRequest {
    return ClaimManagedUserRequestFromJSONTyped(json, false);
}

export function ClaimManagedUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimManagedUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function ClaimManagedUserRequestToJSON(json: any): ClaimManagedUserRequest {
    return ClaimManagedUserRequestToJSONTyped(json, false);
}

export function ClaimManagedUserRequestToJSONTyped(value?: ClaimManagedUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'email': value['email'],
        'password': value['password'],
    };
}

