/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment';

/**
 * 
 * @export
 * @interface CommentListResponse
 */
export interface CommentListResponse {
    /**
     * List of comments
     * @type {Array<Comment>}
     * @memberof CommentListResponse
     */
    comments: Array<Comment>;
    /**
     * Cursor for next page
     * @type {string}
     * @memberof CommentListResponse
     */
    nextCursor: string | null;
    /**
     * Whether there are more comments
     * @type {boolean}
     * @memberof CommentListResponse
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the CommentListResponse interface.
 */
export function instanceOfCommentListResponse(value: object): value is CommentListResponse {
    if (!('comments' in value) || value['comments'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function CommentListResponseFromJSON(json: any): CommentListResponse {
    return CommentListResponseFromJSONTyped(json, false);
}

export function CommentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': ((json['comments'] as Array<any>).map(CommentFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function CommentListResponseToJSON(json: any): CommentListResponse {
    return CommentListResponseToJSONTyped(json, false);
}

export function CommentListResponseToJSONTyped(value?: CommentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': ((value['comments'] as Array<any>).map(CommentToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

