/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateManagedUserResponse
 */
export interface CreateManagedUserResponse {
    /**
     * Platform user ID
     * @type {string}
     * @memberof CreateManagedUserResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateManagedUserResponse
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateManagedUserResponse
     */
    avatarUrl: string | null;
    /**
     * Account type: adult or child (COPPA)
     * @type {string}
     * @memberof CreateManagedUserResponse
     */
    accountType: CreateManagedUserResponseAccountTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof CreateManagedUserResponse
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CreateManagedUserResponseAccountTypeEnum = {
    ADULT: 'adult',
    CHILD: 'child'
} as const;
export type CreateManagedUserResponseAccountTypeEnum = typeof CreateManagedUserResponseAccountTypeEnum[keyof typeof CreateManagedUserResponseAccountTypeEnum];


/**
 * Check if a given object implements the CreateManagedUserResponse interface.
 */
export function instanceOfCreateManagedUserResponse(value: object): value is CreateManagedUserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreateManagedUserResponseFromJSON(json: any): CreateManagedUserResponse {
    return CreateManagedUserResponseFromJSONTyped(json, false);
}

export function CreateManagedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateManagedUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'avatarUrl': json['avatarUrl'],
        'accountType': json['accountType'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CreateManagedUserResponseToJSON(json: any): CreateManagedUserResponse {
    return CreateManagedUserResponseToJSONTyped(json, false);
}

export function CreateManagedUserResponseToJSONTyped(value?: CreateManagedUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'avatarUrl': value['avatarUrl'],
        'accountType': value['accountType'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

