/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateManagedUserRequest
 */
export interface CreateManagedUserRequest {
    /**
     * User display name
     * @type {string}
     * @memberof CreateManagedUserRequest
     */
    name: string;
    /**
     * Account type (adult or child for COPPA)
     * @type {string}
     * @memberof CreateManagedUserRequest
     */
    accountType?: CreateManagedUserRequestAccountTypeEnum;
    /**
     * Birth year for age verification
     * @type {number}
     * @memberof CreateManagedUserRequest
     */
    birthYear?: number;
    /**
     * Profile picture URL
     * @type {string}
     * @memberof CreateManagedUserRequest
     */
    avatarUrl?: string;
    /**
     * Parent user ID. If provided, automatically creates a verified parental consent record. Required for multi-child device sharing to work.
     * @type {string}
     * @memberof CreateManagedUserRequest
     */
    parentUserId?: string;
}


/**
 * @export
 */
export const CreateManagedUserRequestAccountTypeEnum = {
    ADULT: 'adult',
    CHILD: 'child'
} as const;
export type CreateManagedUserRequestAccountTypeEnum = typeof CreateManagedUserRequestAccountTypeEnum[keyof typeof CreateManagedUserRequestAccountTypeEnum];


/**
 * Check if a given object implements the CreateManagedUserRequest interface.
 */
export function instanceOfCreateManagedUserRequest(value: object): value is CreateManagedUserRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateManagedUserRequestFromJSON(json: any): CreateManagedUserRequest {
    return CreateManagedUserRequestFromJSONTyped(json, false);
}

export function CreateManagedUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateManagedUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'accountType': json['accountType'] == null ? undefined : json['accountType'],
        'birthYear': json['birthYear'] == null ? undefined : json['birthYear'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'parentUserId': json['parentUserId'] == null ? undefined : json['parentUserId'],
    };
}

export function CreateManagedUserRequestToJSON(json: any): CreateManagedUserRequest {
    return CreateManagedUserRequestToJSONTyped(json, false);
}

export function CreateManagedUserRequestToJSONTyped(value?: CreateManagedUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'accountType': value['accountType'],
        'birthYear': value['birthYear'],
        'avatarUrl': value['avatarUrl'],
        'parentUserId': value['parentUserId'],
    };
}

