/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFeedItemRequest
 */
export interface CreateFeedItemRequest {
    /**
     * Group ID (family, team, etc.)
     * @type {string}
     * @memberof CreateFeedItemRequest
     */
    groupId: string;
    /**
     * User who performed the action
     * @type {string}
     * @memberof CreateFeedItemRequest
     */
    userId: string;
    /**
     * Type of feed item
     * @type {string}
     * @memberof CreateFeedItemRequest
     */
    itemType: string;
    /**
     * Feed item title
     * @type {string}
     * @memberof CreateFeedItemRequest
     */
    title: string;
    /**
     * Feed item subtitle
     * @type {string}
     * @memberof CreateFeedItemRequest
     */
    subtitle?: string;
    /**
     * Icon emoji or name
     * @type {string}
     * @memberof CreateFeedItemRequest
     */
    icon?: string;
    /**
     * Item-specific metadata
     * @type {{ [key: string]: any | null; }}
     * @memberof CreateFeedItemRequest
     */
    metadata?: { [key: string]: any | null; };
    /**
     * Source table name
     * @type {string}
     * @memberof CreateFeedItemRequest
     */
    sourceType?: string;
    /**
     * Source record ID
     * @type {string}
     * @memberof CreateFeedItemRequest
     */
    sourceId?: string;
    /**
     * When the activity occurred (defaults to now)
     * @type {Date}
     * @memberof CreateFeedItemRequest
     */
    occurredAt?: Date;
}

/**
 * Check if a given object implements the CreateFeedItemRequest interface.
 */
export function instanceOfCreateFeedItemRequest(value: object): value is CreateFeedItemRequest {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('itemType' in value) || value['itemType'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateFeedItemRequestFromJSON(json: any): CreateFeedItemRequest {
    return CreateFeedItemRequestFromJSONTyped(json, false);
}

export function CreateFeedItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeedItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'userId': json['userId'],
        'itemType': json['itemType'],
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'sourceType': json['sourceType'] == null ? undefined : json['sourceType'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'occurredAt': json['occurredAt'] == null ? undefined : (new Date(json['occurredAt'])),
    };
}

export function CreateFeedItemRequestToJSON(json: any): CreateFeedItemRequest {
    return CreateFeedItemRequestToJSONTyped(json, false);
}

export function CreateFeedItemRequestToJSONTyped(value?: CreateFeedItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groupId': value['groupId'],
        'userId': value['userId'],
        'itemType': value['itemType'],
        'title': value['title'],
        'subtitle': value['subtitle'],
        'icon': value['icon'],
        'metadata': value['metadata'],
        'sourceType': value['sourceType'],
        'sourceId': value['sourceId'],
        'occurredAt': value['occurredAt'] == null ? value['occurredAt'] : value['occurredAt'].toISOString(),
    };
}

