/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGroupRequest
 */
export interface CreateGroupRequest {
    /**
     * Group type (1-50 chars)
     * @type {string}
     * @memberof CreateGroupRequest
     */
    groupType: string;
    /**
     * External ID linking to venture entity
     * @type {string}
     * @memberof CreateGroupRequest
     */
    externalId?: string;
    /**
     * Group display name
     * @type {string}
     * @memberof CreateGroupRequest
     */
    name?: string;
    /**
     * Group description
     * @type {string}
     * @memberof CreateGroupRequest
     */
    description?: string;
    /**
     * Flexible metadata
     * @type {{ [key: string]: any | null; }}
     * @memberof CreateGroupRequest
     */
    metadata?: { [key: string]: any | null; };
    /**
     * Whether the group is discoverable (default: false)
     * @type {boolean}
     * @memberof CreateGroupRequest
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the CreateGroupRequest interface.
 */
export function instanceOfCreateGroupRequest(value: object): value is CreateGroupRequest {
    if (!('groupType' in value) || value['groupType'] === undefined) return false;
    return true;
}

export function CreateGroupRequestFromJSON(json: any): CreateGroupRequest {
    return CreateGroupRequestFromJSONTyped(json, false);
}

export function CreateGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'groupType': json['groupType'],
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

export function CreateGroupRequestToJSON(json: any): CreateGroupRequest {
    return CreateGroupRequestToJSONTyped(json, false);
}

export function CreateGroupRequestToJSONTyped(value?: CreateGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groupType': value['groupType'],
        'externalId': value['externalId'],
        'name': value['name'],
        'description': value['description'],
        'metadata': value['metadata'],
        'isPublic': value['isPublic'],
    };
}

