/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGoalRequest
 */
export interface CreateGoalRequest {
    /**
     * User this goal is for
     * @type {string}
     * @memberof CreateGoalRequest
     */
    userId: string;
    /**
     * Goal name
     * @type {string}
     * @memberof CreateGoalRequest
     */
    name: string;
    /**
     * Goal description
     * @type {string}
     * @memberof CreateGoalRequest
     */
    description?: string;
    /**
     * Type of goal
     * @type {string}
     * @memberof CreateGoalRequest
     */
    goalType: CreateGoalRequestGoalTypeEnum;
    /**
     * Target value to reach
     * @type {number}
     * @memberof CreateGoalRequest
     */
    targetValue: number;
    /**
     * Activity type code (for activity_count goals)
     * @type {string}
     * @memberof CreateGoalRequest
     */
    activityType?: string;
    /**
     * Start date (YYYY-MM-DD)
     * @type {string}
     * @memberof CreateGoalRequest
     */
    startDate: string;
    /**
     * End date (YYYY-MM-DD, optional)
     * @type {string}
     * @memberof CreateGoalRequest
     */
    endDate?: string;
    /**
     * Associated reward ID
     * @type {string}
     * @memberof CreateGoalRequest
     */
    rewardId?: string;
}


/**
 * @export
 */
export const CreateGoalRequestGoalTypeEnum = {
    XP: 'xp',
    ACTIVITY_COUNT: 'activity_count',
    STREAK: 'streak',
    CUSTOM: 'custom'
} as const;
export type CreateGoalRequestGoalTypeEnum = typeof CreateGoalRequestGoalTypeEnum[keyof typeof CreateGoalRequestGoalTypeEnum];


/**
 * Check if a given object implements the CreateGoalRequest interface.
 */
export function instanceOfCreateGoalRequest(value: object): value is CreateGoalRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('goalType' in value) || value['goalType'] === undefined) return false;
    if (!('targetValue' in value) || value['targetValue'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    return true;
}

export function CreateGoalRequestFromJSON(json: any): CreateGoalRequest {
    return CreateGoalRequestFromJSONTyped(json, false);
}

export function CreateGoalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGoalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'goalType': json['goalType'],
        'targetValue': json['targetValue'],
        'activityType': json['activityType'] == null ? undefined : json['activityType'],
        'startDate': json['startDate'],
        'endDate': json['endDate'] == null ? undefined : json['endDate'],
        'rewardId': json['rewardId'] == null ? undefined : json['rewardId'],
    };
}

export function CreateGoalRequestToJSON(json: any): CreateGoalRequest {
    return CreateGoalRequestToJSONTyped(json, false);
}

export function CreateGoalRequestToJSONTyped(value?: CreateGoalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'description': value['description'],
        'goalType': value['goalType'],
        'targetValue': value['targetValue'],
        'activityType': value['activityType'],
        'startDate': value['startDate'],
        'endDate': value['endDate'],
        'rewardId': value['rewardId'],
    };
}

