/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentRequest
 */
export interface CreateCommentRequest {
    /**
     * Comment content (max 500 chars)
     * @type {string}
     * @memberof CreateCommentRequest
     */
    content: string;
    /**
     * Parent comment ID (for threaded replies)
     * @type {string}
     * @memberof CreateCommentRequest
     */
    parentId?: string;
}

/**
 * Check if a given object implements the CreateCommentRequest interface.
 */
export function instanceOfCreateCommentRequest(value: object): value is CreateCommentRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateCommentRequestFromJSON(json: any): CreateCommentRequest {
    return CreateCommentRequestFromJSONTyped(json, false);
}

export function CreateCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
    };
}

export function CreateCommentRequestToJSON(json: any): CreateCommentRequest {
    return CreateCommentRequestToJSONTyped(json, false);
}

export function CreateCommentRequestToJSONTyped(value?: CreateCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'parentId': value['parentId'],
    };
}

