/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBadgeRequest
 */
export interface CreateBadgeRequest {
    /**
     * Unique badge code (1-50 chars)
     * @type {string}
     * @memberof CreateBadgeRequest
     */
    code: string;
    /**
     * Display name (1-100 chars)
     * @type {string}
     * @memberof CreateBadgeRequest
     */
    name: string;
    /**
     * Badge description
     * @type {string}
     * @memberof CreateBadgeRequest
     */
    description?: string;
    /**
     * Badge icon
     * @type {string}
     * @memberof CreateBadgeRequest
     */
    icon?: string;
    /**
     * Badge category (default: achievement)
     * @type {string}
     * @memberof CreateBadgeRequest
     */
    category?: string;
    /**
     * XP threshold for auto-award
     * @type {number}
     * @memberof CreateBadgeRequest
     */
    xpThreshold?: number;
    /**
     * Streak threshold for auto-award
     * @type {number}
     * @memberof CreateBadgeRequest
     */
    streakThreshold?: number;
    /**
     * Activity count threshold for auto-award
     * @type {number}
     * @memberof CreateBadgeRequest
     */
    activityCountThreshold?: number;
    /**
     * Custom criteria for badge (JSON)
     * @type {{ [key: string]: any | null; }}
     * @memberof CreateBadgeRequest
     */
    criteria?: { [key: string]: any | null; };
    /**
     * Display order
     * @type {number}
     * @memberof CreateBadgeRequest
     */
    sortOrder?: number;
}

/**
 * Check if a given object implements the CreateBadgeRequest interface.
 */
export function instanceOfCreateBadgeRequest(value: object): value is CreateBadgeRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateBadgeRequestFromJSON(json: any): CreateBadgeRequest {
    return CreateBadgeRequestFromJSONTyped(json, false);
}

export function CreateBadgeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBadgeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'category': json['category'] == null ? undefined : json['category'],
        'xpThreshold': json['xpThreshold'] == null ? undefined : json['xpThreshold'],
        'streakThreshold': json['streakThreshold'] == null ? undefined : json['streakThreshold'],
        'activityCountThreshold': json['activityCountThreshold'] == null ? undefined : json['activityCountThreshold'],
        'criteria': json['criteria'] == null ? undefined : json['criteria'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
    };
}

export function CreateBadgeRequestToJSON(json: any): CreateBadgeRequest {
    return CreateBadgeRequestToJSONTyped(json, false);
}

export function CreateBadgeRequestToJSONTyped(value?: CreateBadgeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'category': value['category'],
        'xpThreshold': value['xpThreshold'],
        'streakThreshold': value['streakThreshold'],
        'activityCountThreshold': value['activityCountThreshold'],
        'criteria': value['criteria'],
        'sortOrder': value['sortOrder'],
    };
}

