/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePledgeRequest
 */
export interface CreatePledgeRequest {
    /**
     * Goal to pledge for
     * @type {string}
     * @memberof CreatePledgeRequest
     */
    goalId: string;
    /**
     * Sponsor user ID
     * @type {string}
     * @memberof CreatePledgeRequest
     */
    sponsorId: string;
    /**
     * Sponsor display name
     * @type {string}
     * @memberof CreatePledgeRequest
     */
    sponsorName?: string;
    /**
     * Type of pledge
     * @type {string}
     * @memberof CreatePledgeRequest
     */
    pledgeType: CreatePledgeRequestPledgeTypeEnum;
    /**
     * Amount per unit (for per_unit pledges)
     * @type {number}
     * @memberof CreatePledgeRequest
     */
    amountPerUnit?: number;
    /**
     * Maximum total amount
     * @type {number}
     * @memberof CreatePledgeRequest
     */
    maxAmount?: number;
    /**
     * Bonus on completion
     * @type {number}
     * @memberof CreatePledgeRequest
     */
    bonusAmount?: number;
    /**
     * Currency code (default: USD)
     * @type {string}
     * @memberof CreatePledgeRequest
     */
    currency?: string;
    /**
     * Whether this is a monetary pledge (default: true)
     * @type {boolean}
     * @memberof CreatePledgeRequest
     */
    isMonetary?: boolean;
    /**
     * Description of non-monetary reward (for isMonetary=false)
     * @type {string}
     * @memberof CreatePledgeRequest
     */
    rewardDescription?: string;
    /**
     * Message from sponsor
     * @type {string}
     * @memberof CreatePledgeRequest
     */
    message?: string;
}


/**
 * @export
 */
export const CreatePledgeRequestPledgeTypeEnum = {
    PER_UNIT: 'per_unit',
    COMPLETION_BONUS: 'completion_bonus',
    FIXED: 'fixed'
} as const;
export type CreatePledgeRequestPledgeTypeEnum = typeof CreatePledgeRequestPledgeTypeEnum[keyof typeof CreatePledgeRequestPledgeTypeEnum];


/**
 * Check if a given object implements the CreatePledgeRequest interface.
 */
export function instanceOfCreatePledgeRequest(value: object): value is CreatePledgeRequest {
    if (!('goalId' in value) || value['goalId'] === undefined) return false;
    if (!('sponsorId' in value) || value['sponsorId'] === undefined) return false;
    if (!('pledgeType' in value) || value['pledgeType'] === undefined) return false;
    return true;
}

export function CreatePledgeRequestFromJSON(json: any): CreatePledgeRequest {
    return CreatePledgeRequestFromJSONTyped(json, false);
}

export function CreatePledgeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePledgeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'goalId': json['goalId'],
        'sponsorId': json['sponsorId'],
        'sponsorName': json['sponsorName'] == null ? undefined : json['sponsorName'],
        'pledgeType': json['pledgeType'],
        'amountPerUnit': json['amountPerUnit'] == null ? undefined : json['amountPerUnit'],
        'maxAmount': json['maxAmount'] == null ? undefined : json['maxAmount'],
        'bonusAmount': json['bonusAmount'] == null ? undefined : json['bonusAmount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'isMonetary': json['isMonetary'] == null ? undefined : json['isMonetary'],
        'rewardDescription': json['rewardDescription'] == null ? undefined : json['rewardDescription'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CreatePledgeRequestToJSON(json: any): CreatePledgeRequest {
    return CreatePledgeRequestToJSONTyped(json, false);
}

export function CreatePledgeRequestToJSONTyped(value?: CreatePledgeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'goalId': value['goalId'],
        'sponsorId': value['sponsorId'],
        'sponsorName': value['sponsorName'],
        'pledgeType': value['pledgeType'],
        'amountPerUnit': value['amountPerUnit'],
        'maxAmount': value['maxAmount'],
        'bonusAmount': value['bonusAmount'],
        'currency': value['currency'],
        'isMonetary': value['isMonetary'],
        'rewardDescription': value['rewardDescription'],
        'message': value['message'],
    };
}

