/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DailyStatByTypeValue } from './DailyStatByTypeValue';
import {
    DailyStatByTypeValueFromJSON,
    DailyStatByTypeValueFromJSONTyped,
    DailyStatByTypeValueToJSON,
    DailyStatByTypeValueToJSONTyped,
} from './DailyStatByTypeValue';

/**
 * 
 * @export
 * @interface DailyStat
 */
export interface DailyStat {
    /**
     * Date (YYYY-MM-DD)
     * @type {string}
     * @memberof DailyStat
     */
    date: string;
    /**
     * Stats per activity type
     * @type {{ [key: string]: DailyStatByTypeValue; }}
     * @memberof DailyStat
     */
    byType: { [key: string]: DailyStatByTypeValue; };
}

/**
 * Check if a given object implements the DailyStat interface.
 */
export function instanceOfDailyStat(value: object): value is DailyStat {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('byType' in value) || value['byType'] === undefined) return false;
    return true;
}

export function DailyStatFromJSON(json: any): DailyStat {
    return DailyStatFromJSONTyped(json, false);
}

export function DailyStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyStat {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'byType': (mapValues(json['byType'], DailyStatByTypeValueFromJSON)),
    };
}

export function DailyStatToJSON(json: any): DailyStat {
    return DailyStatToJSONTyped(json, false);
}

export function DailyStatToJSONTyped(value?: DailyStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'byType': (mapValues(value['byType'], DailyStatByTypeValueToJSON)),
    };
}

