/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyStatByTypeValue
 */
export interface DailyStatByTypeValue {
    /**
     * Total value
     * @type {number}
     * @memberof DailyStatByTypeValue
     */
    value: number;
    /**
     * Activity count
     * @type {number}
     * @memberof DailyStatByTypeValue
     */
    count: number;
}

/**
 * Check if a given object implements the DailyStatByTypeValue interface.
 */
export function instanceOfDailyStatByTypeValue(value: object): value is DailyStatByTypeValue {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function DailyStatByTypeValueFromJSON(json: any): DailyStatByTypeValue {
    return DailyStatByTypeValueFromJSONTyped(json, false);
}

export function DailyStatByTypeValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyStatByTypeValue {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'count': json['count'],
    };
}

export function DailyStatByTypeValueToJSON(json: any): DailyStatByTypeValue {
    return DailyStatByTypeValueToJSONTyped(json, false);
}

export function DailyStatByTypeValueToJSONTyped(value?: DailyStatByTypeValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'count': value['count'],
    };
}

