/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadUrlResponse
 */
export interface DownloadUrlResponse {
    /**
     * Pre-signed URL for downloading
     * @type {string}
     * @memberof DownloadUrlResponse
     */
    downloadUrl: string;
    /**
     * Download URL expiration timestamp
     * @type {Date}
     * @memberof DownloadUrlResponse
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the DownloadUrlResponse interface.
 */
export function instanceOfDownloadUrlResponse(value: object): value is DownloadUrlResponse {
    if (!('downloadUrl' in value) || value['downloadUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function DownloadUrlResponseFromJSON(json: any): DownloadUrlResponse {
    return DownloadUrlResponseFromJSONTyped(json, false);
}

export function DownloadUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadUrl': json['downloadUrl'],
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function DownloadUrlResponseToJSON(json: any): DownloadUrlResponse {
    return DownloadUrlResponseToJSONTyped(json, false);
}

export function DownloadUrlResponseToJSONTyped(value?: DownloadUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downloadUrl': value['downloadUrl'],
        'expiresAt': value['expiresAt'].toISOString(),
    };
}

