/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailVerifyRequest
 */
export interface EmailVerifyRequest {
    /**
     * Email verification token
     * @type {string}
     * @memberof EmailVerifyRequest
     */
    token: string;
}

/**
 * Check if a given object implements the EmailVerifyRequest interface.
 */
export function instanceOfEmailVerifyRequest(value: object): value is EmailVerifyRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function EmailVerifyRequestFromJSON(json: any): EmailVerifyRequest {
    return EmailVerifyRequestFromJSONTyped(json, false);
}

export function EmailVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function EmailVerifyRequestToJSON(json: any): EmailVerifyRequest {
    return EmailVerifyRequestToJSONTyped(json, false);
}

export function EmailVerifyRequestToJSONTyped(value?: EmailVerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

