/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedItem } from './FeedItem';
import {
    FeedItemFromJSON,
    FeedItemFromJSONTyped,
    FeedItemToJSON,
    FeedItemToJSONTyped,
} from './FeedItem';

/**
 * 
 * @export
 * @interface FeedListResponse
 */
export interface FeedListResponse {
    /**
     * List of feed items
     * @type {Array<FeedItem>}
     * @memberof FeedListResponse
     */
    items: Array<FeedItem>;
    /**
     * Cursor for next page
     * @type {string}
     * @memberof FeedListResponse
     */
    nextCursor: string | null;
    /**
     * Whether there are more items
     * @type {boolean}
     * @memberof FeedListResponse
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the FeedListResponse interface.
 */
export function instanceOfFeedListResponse(value: object): value is FeedListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function FeedListResponseFromJSON(json: any): FeedListResponse {
    return FeedListResponseFromJSONTyped(json, false);
}

export function FeedListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(FeedItemFromJSON)),
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function FeedListResponseToJSON(json: any): FeedListResponse {
    return FeedListResponseToJSONTyped(json, false);
}

export function FeedListResponseToJSONTyped(value?: FeedListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(FeedItemToJSON)),
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

