/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Group this item belongs to
 * @export
 * @interface FeedGroup
 */
export interface FeedGroup {
    /**
     * Group ID
     * @type {string}
     * @memberof FeedGroup
     */
    id: string;
    /**
     * Group name
     * @type {string}
     * @memberof FeedGroup
     */
    name: string | null;
    /**
     * Group type
     * @type {string}
     * @memberof FeedGroup
     */
    type: string;
}

/**
 * Check if a given object implements the FeedGroup interface.
 */
export function instanceOfFeedGroup(value: object): value is FeedGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FeedGroupFromJSON(json: any): FeedGroup {
    return FeedGroupFromJSONTyped(json, false);
}

export function FeedGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
    };
}

export function FeedGroupToJSON(json: any): FeedGroup {
    return FeedGroupToJSONTyped(json, false);
}

export function FeedGroupToJSONTyped(value?: FeedGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
    };
}

