/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamificationSummaryBadgesRecentInner
 */
export interface GamificationSummaryBadgesRecentInner {
    /**
     * 
     * @type {string}
     * @memberof GamificationSummaryBadgesRecentInner
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof GamificationSummaryBadgesRecentInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GamificationSummaryBadgesRecentInner
     */
    icon: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GamificationSummaryBadgesRecentInner
     */
    earnedAt: Date;
}

/**
 * Check if a given object implements the GamificationSummaryBadgesRecentInner interface.
 */
export function instanceOfGamificationSummaryBadgesRecentInner(value: object): value is GamificationSummaryBadgesRecentInner {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('earnedAt' in value) || value['earnedAt'] === undefined) return false;
    return true;
}

export function GamificationSummaryBadgesRecentInnerFromJSON(json: any): GamificationSummaryBadgesRecentInner {
    return GamificationSummaryBadgesRecentInnerFromJSONTyped(json, false);
}

export function GamificationSummaryBadgesRecentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamificationSummaryBadgesRecentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'icon': json['icon'],
        'earnedAt': (new Date(json['earnedAt'])),
    };
}

export function GamificationSummaryBadgesRecentInnerToJSON(json: any): GamificationSummaryBadgesRecentInner {
    return GamificationSummaryBadgesRecentInnerToJSONTyped(json, false);
}

export function GamificationSummaryBadgesRecentInnerToJSONTyped(value?: GamificationSummaryBadgesRecentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'icon': value['icon'],
        'earnedAt': value['earnedAt'].toISOString(),
    };
}

