/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * XP summary
 * @export
 * @interface GamificationSummaryXp
 */
export interface GamificationSummaryXp {
    /**
     * Total XP
     * @type {number}
     * @memberof GamificationSummaryXp
     */
    total: number;
    /**
     * Current level
     * @type {number}
     * @memberof GamificationSummaryXp
     */
    level: number;
    /**
     * XP to next level
     * @type {number}
     * @memberof GamificationSummaryXp
     */
    xpToNextLevel: number;
    /**
     * Progress (0-1)
     * @type {number}
     * @memberof GamificationSummaryXp
     */
    levelProgress: number;
}

/**
 * Check if a given object implements the GamificationSummaryXp interface.
 */
export function instanceOfGamificationSummaryXp(value: object): value is GamificationSummaryXp {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('xpToNextLevel' in value) || value['xpToNextLevel'] === undefined) return false;
    if (!('levelProgress' in value) || value['levelProgress'] === undefined) return false;
    return true;
}

export function GamificationSummaryXpFromJSON(json: any): GamificationSummaryXp {
    return GamificationSummaryXpFromJSONTyped(json, false);
}

export function GamificationSummaryXpFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamificationSummaryXp {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'level': json['level'],
        'xpToNextLevel': json['xpToNextLevel'],
        'levelProgress': json['levelProgress'],
    };
}

export function GamificationSummaryXpToJSON(json: any): GamificationSummaryXp {
    return GamificationSummaryXpToJSONTyped(json, false);
}

export function GamificationSummaryXpToJSONTyped(value?: GamificationSummaryXp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'level': value['level'],
        'xpToNextLevel': value['xpToNextLevel'],
        'levelProgress': value['levelProgress'],
    };
}

