/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamificationSummaryStreaksInner
 */
export interface GamificationSummaryStreaksInner {
    /**
     * 
     * @type {string}
     * @memberof GamificationSummaryStreaksInner
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof GamificationSummaryStreaksInner
     */
    current: number;
    /**
     * 
     * @type {number}
     * @memberof GamificationSummaryStreaksInner
     */
    longest: number;
    /**
     * 
     * @type {string}
     * @memberof GamificationSummaryStreaksInner
     */
    lastActivityDate: string | null;
}

/**
 * Check if a given object implements the GamificationSummaryStreaksInner interface.
 */
export function instanceOfGamificationSummaryStreaksInner(value: object): value is GamificationSummaryStreaksInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('longest' in value) || value['longest'] === undefined) return false;
    if (!('lastActivityDate' in value) || value['lastActivityDate'] === undefined) return false;
    return true;
}

export function GamificationSummaryStreaksInnerFromJSON(json: any): GamificationSummaryStreaksInner {
    return GamificationSummaryStreaksInnerFromJSONTyped(json, false);
}

export function GamificationSummaryStreaksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamificationSummaryStreaksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'current': json['current'],
        'longest': json['longest'],
        'lastActivityDate': json['lastActivityDate'],
    };
}

export function GamificationSummaryStreaksInnerToJSON(json: any): GamificationSummaryStreaksInner {
    return GamificationSummaryStreaksInnerToJSONTyped(json, false);
}

export function GamificationSummaryStreaksInnerToJSONTyped(value?: GamificationSummaryStreaksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'current': value['current'],
        'longest': value['longest'],
        'lastActivityDate': value['lastActivityDate'],
    };
}

