/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GamificationSummaryBadgesRecentInner } from './GamificationSummaryBadgesRecentInner';
import {
    GamificationSummaryBadgesRecentInnerFromJSON,
    GamificationSummaryBadgesRecentInnerFromJSONTyped,
    GamificationSummaryBadgesRecentInnerToJSON,
    GamificationSummaryBadgesRecentInnerToJSONTyped,
} from './GamificationSummaryBadgesRecentInner';

/**
 * Badge summary
 * @export
 * @interface GamificationSummaryBadges
 */
export interface GamificationSummaryBadges {
    /**
     * Badges earned
     * @type {number}
     * @memberof GamificationSummaryBadges
     */
    earned: number;
    /**
     * Recently earned badges
     * @type {Array<GamificationSummaryBadgesRecentInner>}
     * @memberof GamificationSummaryBadges
     */
    recent: Array<GamificationSummaryBadgesRecentInner>;
}

/**
 * Check if a given object implements the GamificationSummaryBadges interface.
 */
export function instanceOfGamificationSummaryBadges(value: object): value is GamificationSummaryBadges {
    if (!('earned' in value) || value['earned'] === undefined) return false;
    if (!('recent' in value) || value['recent'] === undefined) return false;
    return true;
}

export function GamificationSummaryBadgesFromJSON(json: any): GamificationSummaryBadges {
    return GamificationSummaryBadgesFromJSONTyped(json, false);
}

export function GamificationSummaryBadgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamificationSummaryBadges {
    if (json == null) {
        return json;
    }
    return {
        
        'earned': json['earned'],
        'recent': ((json['recent'] as Array<any>).map(GamificationSummaryBadgesRecentInnerFromJSON)),
    };
}

export function GamificationSummaryBadgesToJSON(json: any): GamificationSummaryBadges {
    return GamificationSummaryBadgesToJSONTyped(json, false);
}

export function GamificationSummaryBadgesToJSONTyped(value?: GamificationSummaryBadges | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'earned': value['earned'],
        'recent': ((value['recent'] as Array<any>).map(GamificationSummaryBadgesRecentInnerToJSON)),
    };
}

