/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiV1ChatCompletionsPost400ResponseAllOfError } from './AiV1ChatCompletionsPost400ResponseAllOfError';
import {
    AiV1ChatCompletionsPost400ResponseAllOfErrorFromJSON,
    AiV1ChatCompletionsPost400ResponseAllOfErrorFromJSONTyped,
    AiV1ChatCompletionsPost400ResponseAllOfErrorToJSON,
    AiV1ChatCompletionsPost400ResponseAllOfErrorToJSONTyped,
} from './AiV1ChatCompletionsPost400ResponseAllOfError';

/**
 * 
 * @export
 * @interface GamificationErrorResponse
 */
export interface GamificationErrorResponse {
    /**
     * 
     * @type {AiV1ChatCompletionsPost400ResponseAllOfError}
     * @memberof GamificationErrorResponse
     */
    error: AiV1ChatCompletionsPost400ResponseAllOfError;
}

/**
 * Check if a given object implements the GamificationErrorResponse interface.
 */
export function instanceOfGamificationErrorResponse(value: object): value is GamificationErrorResponse {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GamificationErrorResponseFromJSON(json: any): GamificationErrorResponse {
    return GamificationErrorResponseFromJSONTyped(json, false);
}

export function GamificationErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamificationErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': AiV1ChatCompletionsPost400ResponseAllOfErrorFromJSON(json['error']),
    };
}

export function GamificationErrorResponseToJSON(json: any): GamificationErrorResponse {
    return GamificationErrorResponseToJSONTyped(json, false);
}

export function GamificationErrorResponseToJSONTyped(value?: GamificationErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': AiV1ChatCompletionsPost400ResponseAllOfErrorToJSON(value['error']),
    };
}

