/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationPreferences } from './NotificationPreferences';
import {
    NotificationPreferencesFromJSON,
    NotificationPreferencesFromJSONTyped,
    NotificationPreferencesToJSON,
    NotificationPreferencesToJSONTyped,
} from './NotificationPreferences';

/**
 * 
 * @export
 * @interface GetPreferencesResponse
 */
export interface GetPreferencesResponse {
    /**
     * 
     * @type {NotificationPreferences}
     * @memberof GetPreferencesResponse
     */
    preferences: NotificationPreferences;
    /**
     * Whether push notifications are enabled globally
     * @type {boolean}
     * @memberof GetPreferencesResponse
     */
    pushEnabled: boolean;
    /**
     * Quiet hours start time (HH:MM)
     * @type {string}
     * @memberof GetPreferencesResponse
     */
    quietHoursStart: string | null;
    /**
     * Quiet hours end time (HH:MM)
     * @type {string}
     * @memberof GetPreferencesResponse
     */
    quietHoursEnd: string | null;
}

/**
 * Check if a given object implements the GetPreferencesResponse interface.
 */
export function instanceOfGetPreferencesResponse(value: object): value is GetPreferencesResponse {
    if (!('preferences' in value) || value['preferences'] === undefined) return false;
    if (!('pushEnabled' in value) || value['pushEnabled'] === undefined) return false;
    if (!('quietHoursStart' in value) || value['quietHoursStart'] === undefined) return false;
    if (!('quietHoursEnd' in value) || value['quietHoursEnd'] === undefined) return false;
    return true;
}

export function GetPreferencesResponseFromJSON(json: any): GetPreferencesResponse {
    return GetPreferencesResponseFromJSONTyped(json, false);
}

export function GetPreferencesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPreferencesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'preferences': NotificationPreferencesFromJSON(json['preferences']),
        'pushEnabled': json['pushEnabled'],
        'quietHoursStart': json['quietHoursStart'],
        'quietHoursEnd': json['quietHoursEnd'],
    };
}

export function GetPreferencesResponseToJSON(json: any): GetPreferencesResponse {
    return GetPreferencesResponseToJSONTyped(json, false);
}

export function GetPreferencesResponseToJSONTyped(value?: GetPreferencesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'preferences': NotificationPreferencesToJSON(value['preferences']),
        'pushEnabled': value['pushEnabled'],
        'quietHoursStart': value['quietHoursStart'],
        'quietHoursEnd': value['quietHoursEnd'],
    };
}

