/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Goal } from './Goal';
import {
    GoalFromJSON,
    GoalFromJSONTyped,
    GoalToJSON,
    GoalToJSONTyped,
} from './Goal';
import type { SponsorPledge } from './SponsorPledge';
import {
    SponsorPledgeFromJSON,
    SponsorPledgeFromJSONTyped,
    SponsorPledgeToJSON,
    SponsorPledgeToJSONTyped,
} from './SponsorPledge';

/**
 * 
 * @export
 * @interface GoalWithPledges
 */
export interface GoalWithPledges {
    /**
     * 
     * @type {Goal}
     * @memberof GoalWithPledges
     */
    goal: Goal;
    /**
     * Pledges for this goal
     * @type {Array<SponsorPledge>}
     * @memberof GoalWithPledges
     */
    pledges: Array<SponsorPledge>;
    /**
     * Total amount pledged
     * @type {number}
     * @memberof GoalWithPledges
     */
    totalPledged: number;
    /**
     * Total amount currently owed
     * @type {number}
     * @memberof GoalWithPledges
     */
    totalOwed: number;
}

/**
 * Check if a given object implements the GoalWithPledges interface.
 */
export function instanceOfGoalWithPledges(value: object): value is GoalWithPledges {
    if (!('goal' in value) || value['goal'] === undefined) return false;
    if (!('pledges' in value) || value['pledges'] === undefined) return false;
    if (!('totalPledged' in value) || value['totalPledged'] === undefined) return false;
    if (!('totalOwed' in value) || value['totalOwed'] === undefined) return false;
    return true;
}

export function GoalWithPledgesFromJSON(json: any): GoalWithPledges {
    return GoalWithPledgesFromJSONTyped(json, false);
}

export function GoalWithPledgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoalWithPledges {
    if (json == null) {
        return json;
    }
    return {
        
        'goal': GoalFromJSON(json['goal']),
        'pledges': ((json['pledges'] as Array<any>).map(SponsorPledgeFromJSON)),
        'totalPledged': json['totalPledged'],
        'totalOwed': json['totalOwed'],
    };
}

export function GoalWithPledgesToJSON(json: any): GoalWithPledges {
    return GoalWithPledgesToJSONTyped(json, false);
}

export function GoalWithPledgesToJSONTyped(value?: GoalWithPledges | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'goal': GoalToJSON(value['goal']),
        'pledges': ((value['pledges'] as Array<any>).map(SponsorPledgeToJSON)),
        'totalPledged': value['totalPledged'],
        'totalOwed': value['totalOwed'],
    };
}

