/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrantConsentResponse
 */
export interface GrantConsentResponse {
    /**
     * Whether consent was granted successfully
     * @type {boolean}
     * @memberof GrantConsentResponse
     */
    success: boolean;
    /**
     * Status message
     * @type {string}
     * @memberof GrantConsentResponse
     */
    message: string;
}

/**
 * Check if a given object implements the GrantConsentResponse interface.
 */
export function instanceOfGrantConsentResponse(value: object): value is GrantConsentResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GrantConsentResponseFromJSON(json: any): GrantConsentResponse {
    return GrantConsentResponseFromJSONTyped(json, false);
}

export function GrantConsentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantConsentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
    };
}

export function GrantConsentResponseToJSON(json: any): GrantConsentResponse {
    return GrantConsentResponseToJSONTyped(json, false);
}

export function GrantConsentResponseToJSONTyped(value?: GrantConsentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

