/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrantConsentRequest
 */
export interface GrantConsentRequest {
    /**
     * Platform user ID of the child to grant consent for
     * @type {string}
     * @memberof GrantConsentRequest
     */
    childUserId: string;
}

/**
 * Check if a given object implements the GrantConsentRequest interface.
 */
export function instanceOfGrantConsentRequest(value: object): value is GrantConsentRequest {
    if (!('childUserId' in value) || value['childUserId'] === undefined) return false;
    return true;
}

export function GrantConsentRequestFromJSON(json: any): GrantConsentRequest {
    return GrantConsentRequestFromJSONTyped(json, false);
}

export function GrantConsentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantConsentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'childUserId': json['childUserId'],
    };
}

export function GrantConsentRequestToJSON(json: any): GrantConsentRequest {
    return GrantConsentRequestToJSONTyped(json, false);
}

export function GrantConsentRequestToJSONTyped(value?: GrantConsentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'childUserId': value['childUserId'],
    };
}

