/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group';

/**
 * 
 * @export
 * @interface GroupListResponse
 */
export interface GroupListResponse {
    /**
     * List of groups
     * @type {Array<Group>}
     * @memberof GroupListResponse
     */
    groups: Array<Group>;
}

/**
 * Check if a given object implements the GroupListResponse interface.
 */
export function instanceOfGroupListResponse(value: object): value is GroupListResponse {
    if (!('groups' in value) || value['groups'] === undefined) return false;
    return true;
}

export function GroupListResponseFromJSON(json: any): GroupListResponse {
    return GroupListResponseFromJSONTyped(json, false);
}

export function GroupListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'groups': ((json['groups'] as Array<any>).map(GroupFromJSON)),
    };
}

export function GroupListResponseToJSON(json: any): GroupListResponse {
    return GroupListResponseToJSONTyped(json, false);
}

export function GroupListResponseToJSONTyped(value?: GroupListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groups': ((value['groups'] as Array<any>).map(GroupToJSON)),
    };
}

