/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthzResponse
 */
export interface HealthzResponse {
    /**
     * Health status indicator
     * @type {string}
     * @memberof HealthzResponse
     */
    status: HealthzResponseStatusEnum;
    /**
     * Service name
     * @type {string}
     * @memberof HealthzResponse
     */
    service: string;
    /**
     * Deployment environment
     * @type {string}
     * @memberof HealthzResponse
     */
    environment: string;
    /**
     * Service version
     * @type {string}
     * @memberof HealthzResponse
     */
    version: string;
    /**
     * Current server time in ISO 8601 format
     * @type {Date}
     * @memberof HealthzResponse
     */
    timestamp: Date;
    /**
     * Service uptime in seconds (if available)
     * @type {number}
     * @memberof HealthzResponse
     */
    uptime?: number;
}


/**
 * @export
 */
export const HealthzResponseStatusEnum = {
    OK: 'ok'
} as const;
export type HealthzResponseStatusEnum = typeof HealthzResponseStatusEnum[keyof typeof HealthzResponseStatusEnum];


/**
 * Check if a given object implements the HealthzResponse interface.
 */
export function instanceOfHealthzResponse(value: object): value is HealthzResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function HealthzResponseFromJSON(json: any): HealthzResponse {
    return HealthzResponseFromJSONTyped(json, false);
}

export function HealthzResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthzResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'service': json['service'],
        'environment': json['environment'],
        'version': json['version'],
        'timestamp': (new Date(json['timestamp'])),
        'uptime': json['uptime'] == null ? undefined : json['uptime'],
    };
}

export function HealthzResponseToJSON(json: any): HealthzResponse {
    return HealthzResponseToJSONTyped(json, false);
}

export function HealthzResponseToJSONTyped(value?: HealthzResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'service': value['service'],
        'environment': value['environment'],
        'version': value['version'],
        'timestamp': value['timestamp'].toISOString(),
        'uptime': value['uptime'],
    };
}

