/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HelloWorldHelloResponse
 */
export interface HelloWorldHelloResponse {
    /**
     * Greeting message
     * @type {string}
     * @memberof HelloWorldHelloResponse
     */
    message: string;
    /**
     * Service name
     * @type {string}
     * @memberof HelloWorldHelloResponse
     */
    service: string;
    /**
     * Environment (development/staging/production)
     * @type {string}
     * @memberof HelloWorldHelloResponse
     */
    environment: string;
    /**
     * ISO 8601 timestamp
     * @type {Date}
     * @memberof HelloWorldHelloResponse
     */
    timestamp: Date;
    /**
     * Service version
     * @type {string}
     * @memberof HelloWorldHelloResponse
     */
    version: string;
}

/**
 * Check if a given object implements the HelloWorldHelloResponse interface.
 */
export function instanceOfHelloWorldHelloResponse(value: object): value is HelloWorldHelloResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function HelloWorldHelloResponseFromJSON(json: any): HelloWorldHelloResponse {
    return HelloWorldHelloResponseFromJSONTyped(json, false);
}

export function HelloWorldHelloResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelloWorldHelloResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'service': json['service'],
        'environment': json['environment'],
        'timestamp': (new Date(json['timestamp'])),
        'version': json['version'],
    };
}

export function HelloWorldHelloResponseToJSON(json: any): HelloWorldHelloResponse {
    return HelloWorldHelloResponseToJSONTyped(json, false);
}

export function HelloWorldHelloResponseToJSONTyped(value?: HelloWorldHelloResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'service': value['service'],
        'environment': value['environment'],
        'timestamp': value['timestamp'].toISOString(),
        'version': value['version'],
    };
}

