/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HelloWorldProtectedResponse
 */
export interface HelloWorldProtectedResponse {
    /**
     * Success message
     * @type {string}
     * @memberof HelloWorldProtectedResponse
     */
    message: string;
    /**
     * Authenticated user or service ID (from auth.sub)
     * @type {string}
     * @memberof HelloWorldProtectedResponse
     */
    userId: string;
    /**
     * User roles or service scopes (from auth.roles)
     * @type {Array<string>}
     * @memberof HelloWorldProtectedResponse
     */
    roles: Array<string>;
    /**
     * ISO 8601 timestamp
     * @type {Date}
     * @memberof HelloWorldProtectedResponse
     */
    timestamp: Date;
}

/**
 * Check if a given object implements the HelloWorldProtectedResponse interface.
 */
export function instanceOfHelloWorldProtectedResponse(value: object): value is HelloWorldProtectedResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function HelloWorldProtectedResponseFromJSON(json: any): HelloWorldProtectedResponse {
    return HelloWorldProtectedResponseFromJSONTyped(json, false);
}

export function HelloWorldProtectedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelloWorldProtectedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'userId': json['userId'],
        'roles': json['roles'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function HelloWorldProtectedResponseToJSON(json: any): HelloWorldProtectedResponse {
    return HelloWorldProtectedResponseToJSONTyped(json, false);
}

export function HelloWorldProtectedResponseToJSONTyped(value?: HelloWorldProtectedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'userId': value['userId'],
        'roles': value['roles'],
        'timestamp': value['timestamp'].toISOString(),
    };
}

