/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified API for all BriskStack platform services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiGatewayErrorResponseError } from './AiGatewayErrorResponseError';
import {
    AiGatewayErrorResponseErrorFromJSON,
    AiGatewayErrorResponseErrorFromJSONTyped,
    AiGatewayErrorResponseErrorToJSON,
    AiGatewayErrorResponseErrorToJSONTyped,
} from './AiGatewayErrorResponseError';

/**
 * 
 * @export
 * @interface HelloWorldErrorResponse
 */
export interface HelloWorldErrorResponse {
    /**
     * 
     * @type {AiGatewayErrorResponseError}
     * @memberof HelloWorldErrorResponse
     */
    error: AiGatewayErrorResponseError;
}

/**
 * Check if a given object implements the HelloWorldErrorResponse interface.
 */
export function instanceOfHelloWorldErrorResponse(value: object): value is HelloWorldErrorResponse {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function HelloWorldErrorResponseFromJSON(json: any): HelloWorldErrorResponse {
    return HelloWorldErrorResponseFromJSONTyped(json, false);
}

export function HelloWorldErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelloWorldErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': AiGatewayErrorResponseErrorFromJSON(json['error']),
    };
}

export function HelloWorldErrorResponseToJSON(json: any): HelloWorldErrorResponse {
    return HelloWorldErrorResponseToJSONTyped(json, false);
}

export function HelloWorldErrorResponseToJSONTyped(value?: HelloWorldErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': AiGatewayErrorResponseErrorToJSON(value['error']),
    };
}

