/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface InboxResponse
 */
export interface InboxResponse {
    /**
     * List of notifications
     * @type {Array<Notification>}
     * @memberof InboxResponse
     */
    notifications: Array<Notification>;
    /**
     * Total number of unread notifications
     * @type {number}
     * @memberof InboxResponse
     */
    unreadCount: number;
    /**
     * Cursor for next page
     * @type {string}
     * @memberof InboxResponse
     */
    nextCursor: string | null;
    /**
     * Whether there are more notifications
     * @type {boolean}
     * @memberof InboxResponse
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the InboxResponse interface.
 */
export function instanceOfInboxResponse(value: object): value is InboxResponse {
    if (!('notifications' in value) || value['notifications'] === undefined) return false;
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function InboxResponseFromJSON(json: any): InboxResponse {
    return InboxResponseFromJSONTyped(json, false);
}

export function InboxResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InboxResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': ((json['notifications'] as Array<any>).map(NotificationFromJSON)),
        'unreadCount': json['unreadCount'],
        'nextCursor': json['nextCursor'],
        'hasMore': json['hasMore'],
    };
}

export function InboxResponseToJSON(json: any): InboxResponse {
    return InboxResponseToJSONTyped(json, false);
}

export function InboxResponseToJSONTyped(value?: InboxResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notifications': ((value['notifications'] as Array<any>).map(NotificationToJSON)),
        'unreadCount': value['unreadCount'],
        'nextCursor': value['nextCursor'],
        'hasMore': value['hasMore'],
    };
}

