/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeaderboardRanking
 */
export interface LeaderboardRanking {
    /**
     * Position in the leaderboard
     * @type {number}
     * @memberof LeaderboardRanking
     */
    rank: number;
    /**
     * User ID
     * @type {string}
     * @memberof LeaderboardRanking
     */
    userId: string;
    /**
     * User display name
     * @type {string}
     * @memberof LeaderboardRanking
     */
    displayName: string | null;
    /**
     * XP earned in this period
     * @type {number}
     * @memberof LeaderboardRanking
     */
    xp: number;
    /**
     * Current level
     * @type {number}
     * @memberof LeaderboardRanking
     */
    level: number;
}

/**
 * Check if a given object implements the LeaderboardRanking interface.
 */
export function instanceOfLeaderboardRanking(value: object): value is LeaderboardRanking {
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('xp' in value) || value['xp'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    return true;
}

export function LeaderboardRankingFromJSON(json: any): LeaderboardRanking {
    return LeaderboardRankingFromJSONTyped(json, false);
}

export function LeaderboardRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'userId': json['userId'],
        'displayName': json['displayName'],
        'xp': json['xp'],
        'level': json['level'],
    };
}

export function LeaderboardRankingToJSON(json: any): LeaderboardRanking {
    return LeaderboardRankingToJSONTyped(json, false);
}

export function LeaderboardRankingToJSONTyped(value?: LeaderboardRanking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'userId': value['userId'],
        'displayName': value['displayName'],
        'xp': value['xp'],
        'level': value['level'],
    };
}

