/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeaderboardRanking } from './LeaderboardRanking';
import {
    LeaderboardRankingFromJSON,
    LeaderboardRankingFromJSONTyped,
    LeaderboardRankingToJSON,
    LeaderboardRankingToJSONTyped,
} from './LeaderboardRanking';
import type { LeaderboardResponseGroup } from './LeaderboardResponseGroup';
import {
    LeaderboardResponseGroupFromJSON,
    LeaderboardResponseGroupFromJSONTyped,
    LeaderboardResponseGroupToJSON,
    LeaderboardResponseGroupToJSONTyped,
} from './LeaderboardResponseGroup';

/**
 * 
 * @export
 * @interface LeaderboardResponse
 */
export interface LeaderboardResponse {
    /**
     * 
     * @type {LeaderboardResponseGroup}
     * @memberof LeaderboardResponse
     */
    group: LeaderboardResponseGroup;
    /**
     * Time period (today, week, month, all)
     * @type {string}
     * @memberof LeaderboardResponse
     */
    period: string;
    /**
     * User rankings
     * @type {Array<LeaderboardRanking>}
     * @memberof LeaderboardResponse
     */
    rankings: Array<LeaderboardRanking>;
}

/**
 * Check if a given object implements the LeaderboardResponse interface.
 */
export function instanceOfLeaderboardResponse(value: object): value is LeaderboardResponse {
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('rankings' in value) || value['rankings'] === undefined) return false;
    return true;
}

export function LeaderboardResponseFromJSON(json: any): LeaderboardResponse {
    return LeaderboardResponseFromJSONTyped(json, false);
}

export function LeaderboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'group': LeaderboardResponseGroupFromJSON(json['group']),
        'period': json['period'],
        'rankings': ((json['rankings'] as Array<any>).map(LeaderboardRankingFromJSON)),
    };
}

export function LeaderboardResponseToJSON(json: any): LeaderboardResponse {
    return LeaderboardResponseToJSONTyped(json, false);
}

export function LeaderboardResponseToJSONTyped(value?: LeaderboardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': LeaderboardResponseGroupToJSON(value['group']),
        'period': value['period'],
        'rankings': ((value['rankings'] as Array<any>).map(LeaderboardRankingToJSON)),
    };
}

