/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Group info
 * @export
 * @interface LeaderboardResponseGroup
 */
export interface LeaderboardResponseGroup {
    /**
     * 
     * @type {string}
     * @memberof LeaderboardResponseGroup
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardResponseGroup
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardResponseGroup
     */
    name: string | null;
}

/**
 * Check if a given object implements the LeaderboardResponseGroup interface.
 */
export function instanceOfLeaderboardResponseGroup(value: object): value is LeaderboardResponseGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function LeaderboardResponseGroupFromJSON(json: any): LeaderboardResponseGroup {
    return LeaderboardResponseGroupFromJSONTyped(json, false);
}

export function LeaderboardResponseGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardResponseGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'name': json['name'],
    };
}

export function LeaderboardResponseGroupToJSON(json: any): LeaderboardResponseGroup {
    return LeaderboardResponseGroupToJSONTyped(json, false);
}

export function LeaderboardResponseGroupToJSONTyped(value?: LeaderboardResponseGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'name': value['name'],
    };
}

