/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutRequest
 */
export interface LogoutRequest {
    /**
     * Refresh token to revoke (optional, will revoke current session)
     * @type {string}
     * @memberof LogoutRequest
     */
    refreshToken?: string;
    /**
     * Revoke all sessions for this user
     * @type {boolean}
     * @memberof LogoutRequest
     */
    allSessions?: boolean;
}

/**
 * Check if a given object implements the LogoutRequest interface.
 */
export function instanceOfLogoutRequest(value: object): value is LogoutRequest {
    return true;
}

export function LogoutRequestFromJSON(json: any): LogoutRequest {
    return LogoutRequestFromJSONTyped(json, false);
}

export function LogoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'allSessions': json['allSessions'] == null ? undefined : json['allSessions'],
    };
}

export function LogoutRequestToJSON(json: any): LogoutRequest {
    return LogoutRequestToJSONTyped(json, false);
}

export function LogoutRequestToJSONTyped(value?: LogoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshToken': value['refreshToken'],
        'allSessions': value['allSessions'],
    };
}

