/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupMembership } from './GroupMembership';
import {
    GroupMembershipFromJSON,
    GroupMembershipFromJSONTyped,
    GroupMembershipToJSON,
    GroupMembershipToJSONTyped,
} from './GroupMembership';

/**
 * 
 * @export
 * @interface MemberListResponse
 */
export interface MemberListResponse {
    /**
     * List of group members
     * @type {Array<GroupMembership>}
     * @memberof MemberListResponse
     */
    members: Array<GroupMembership>;
}

/**
 * Check if a given object implements the MemberListResponse interface.
 */
export function instanceOfMemberListResponse(value: object): value is MemberListResponse {
    if (!('members' in value) || value['members'] === undefined) return false;
    return true;
}

export function MemberListResponseFromJSON(json: any): MemberListResponse {
    return MemberListResponseFromJSONTyped(json, false);
}

export function MemberListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'members': ((json['members'] as Array<any>).map(GroupMembershipFromJSON)),
    };
}

export function MemberListResponseToJSON(json: any): MemberListResponse {
    return MemberListResponseToJSONTyped(json, false);
}

export function MemberListResponseToJSONTyped(value?: MemberListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'members': ((value['members'] as Array<any>).map(GroupMembershipToJSON)),
    };
}

