/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthStartRequest
 */
export interface OAuthStartRequest {
    /**
     * OAuth provider
     * @type {string}
     * @memberof OAuthStartRequest
     */
    provider: OAuthStartRequestProviderEnum;
    /**
     * Redirect URI after OAuth
     * @type {string}
     * @memberof OAuthStartRequest
     */
    redirectUri: string;
    /**
     * Venture ID for scoped sessions
     * @type {string}
     * @memberof OAuthStartRequest
     */
    ventureId?: string;
}


/**
 * @export
 */
export const OAuthStartRequestProviderEnum = {
    GOOGLE: 'google',
    APPLE: 'apple'
} as const;
export type OAuthStartRequestProviderEnum = typeof OAuthStartRequestProviderEnum[keyof typeof OAuthStartRequestProviderEnum];


/**
 * Check if a given object implements the OAuthStartRequest interface.
 */
export function instanceOfOAuthStartRequest(value: object): value is OAuthStartRequest {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    return true;
}

export function OAuthStartRequestFromJSON(json: any): OAuthStartRequest {
    return OAuthStartRequestFromJSONTyped(json, false);
}

export function OAuthStartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthStartRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'redirectUri': json['redirectUri'],
        'ventureId': json['ventureId'] == null ? undefined : json['ventureId'],
    };
}

export function OAuthStartRequestToJSON(json: any): OAuthStartRequest {
    return OAuthStartRequestToJSONTyped(json, false);
}

export function OAuthStartRequestToJSONTyped(value?: OAuthStartRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'redirectUri': value['redirectUri'],
        'ventureId': value['ventureId'],
    };
}

