/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthStartResponse
 */
export interface OAuthStartResponse {
    /**
     * OAuth authorization URL
     * @type {string}
     * @memberof OAuthStartResponse
     */
    authUrl: string;
    /**
     * OAuth state parameter
     * @type {string}
     * @memberof OAuthStartResponse
     */
    state: string;
}

/**
 * Check if a given object implements the OAuthStartResponse interface.
 */
export function instanceOfOAuthStartResponse(value: object): value is OAuthStartResponse {
    if (!('authUrl' in value) || value['authUrl'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function OAuthStartResponseFromJSON(json: any): OAuthStartResponse {
    return OAuthStartResponseFromJSONTyped(json, false);
}

export function OAuthStartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthStartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authUrl': json['authUrl'],
        'state': json['state'],
    };
}

export function OAuthStartResponseToJSON(json: any): OAuthStartResponse {
    return OAuthStartResponseToJSONTyped(json, false);
}

export function OAuthStartResponseToJSONTyped(value?: OAuthStartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authUrl': value['authUrl'],
        'state': value['state'],
    };
}

