/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SponsorPledge } from './SponsorPledge';
import {
    SponsorPledgeFromJSON,
    SponsorPledgeFromJSONTyped,
    SponsorPledgeToJSON,
    SponsorPledgeToJSONTyped,
} from './SponsorPledge';

/**
 * 
 * @export
 * @interface PledgeListResponse
 */
export interface PledgeListResponse {
    /**
     * List of pledges
     * @type {Array<SponsorPledge>}
     * @memberof PledgeListResponse
     */
    pledges: Array<SponsorPledge>;
}

/**
 * Check if a given object implements the PledgeListResponse interface.
 */
export function instanceOfPledgeListResponse(value: object): value is PledgeListResponse {
    if (!('pledges' in value) || value['pledges'] === undefined) return false;
    return true;
}

export function PledgeListResponseFromJSON(json: any): PledgeListResponse {
    return PledgeListResponseFromJSONTyped(json, false);
}

export function PledgeListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PledgeListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pledges': ((json['pledges'] as Array<any>).map(SponsorPledgeFromJSON)),
    };
}

export function PledgeListResponseToJSON(json: any): PledgeListResponse {
    return PledgeListResponseToJSONTyped(json, false);
}

export function PledgeListResponseToJSONTyped(value?: PledgeListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pledges': ((value['pledges'] as Array<any>).map(SponsorPledgeToJSON)),
    };
}

