/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordActivityResponseNewBadgesInner } from './RecordActivityResponseNewBadgesInner';
import {
    RecordActivityResponseNewBadgesInnerFromJSON,
    RecordActivityResponseNewBadgesInnerFromJSONTyped,
    RecordActivityResponseNewBadgesInnerToJSON,
    RecordActivityResponseNewBadgesInnerToJSONTyped,
} from './RecordActivityResponseNewBadgesInner';

/**
 * 
 * @export
 * @interface RecordActivityResponse
 */
export interface RecordActivityResponse {
    /**
     * Activity ID
     * @type {string}
     * @memberof RecordActivityResponse
     */
    id: string;
    /**
     * Activity type code
     * @type {string}
     * @memberof RecordActivityResponse
     */
    activityType: string;
    /**
     * Activity value
     * @type {number}
     * @memberof RecordActivityResponse
     */
    value: number;
    /**
     * XP awarded for this activity
     * @type {number}
     * @memberof RecordActivityResponse
     */
    xpAwarded: number;
    /**
     * When the activity was performed
     * @type {Date}
     * @memberof RecordActivityResponse
     */
    performedAt: Date;
    /**
     * User total XP after this activity
     * @type {number}
     * @memberof RecordActivityResponse
     */
    totalXp: number;
    /**
     * User level after this activity
     * @type {number}
     * @memberof RecordActivityResponse
     */
    level: number;
    /**
     * Current streak count (if streak-eligible activity)
     * @type {number}
     * @memberof RecordActivityResponse
     */
    currentStreak?: number;
    /**
     * Badges earned from this activity
     * @type {Array<RecordActivityResponseNewBadgesInner>}
     * @memberof RecordActivityResponse
     */
    newBadges?: Array<RecordActivityResponseNewBadgesInner>;
}

/**
 * Check if a given object implements the RecordActivityResponse interface.
 */
export function instanceOfRecordActivityResponse(value: object): value is RecordActivityResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('activityType' in value) || value['activityType'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('xpAwarded' in value) || value['xpAwarded'] === undefined) return false;
    if (!('performedAt' in value) || value['performedAt'] === undefined) return false;
    if (!('totalXp' in value) || value['totalXp'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    return true;
}

export function RecordActivityResponseFromJSON(json: any): RecordActivityResponse {
    return RecordActivityResponseFromJSONTyped(json, false);
}

export function RecordActivityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordActivityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'activityType': json['activityType'],
        'value': json['value'],
        'xpAwarded': json['xpAwarded'],
        'performedAt': (new Date(json['performedAt'])),
        'totalXp': json['totalXp'],
        'level': json['level'],
        'currentStreak': json['currentStreak'] == null ? undefined : json['currentStreak'],
        'newBadges': json['newBadges'] == null ? undefined : ((json['newBadges'] as Array<any>).map(RecordActivityResponseNewBadgesInnerFromJSON)),
    };
}

export function RecordActivityResponseToJSON(json: any): RecordActivityResponse {
    return RecordActivityResponseToJSONTyped(json, false);
}

export function RecordActivityResponseToJSONTyped(value?: RecordActivityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'activityType': value['activityType'],
        'value': value['value'],
        'xpAwarded': value['xpAwarded'],
        'performedAt': value['performedAt'].toISOString(),
        'totalXp': value['totalXp'],
        'level': value['level'],
        'currentStreak': value['currentStreak'],
        'newBadges': value['newBadges'] == null ? undefined : ((value['newBadges'] as Array<any>).map(RecordActivityResponseNewBadgesInnerToJSON)),
    };
}

