/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordActivityResponseNewBadgesInner
 */
export interface RecordActivityResponseNewBadgesInner {
    /**
     * 
     * @type {string}
     * @memberof RecordActivityResponseNewBadgesInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RecordActivityResponseNewBadgesInner
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof RecordActivityResponseNewBadgesInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RecordActivityResponseNewBadgesInner
     */
    icon: string | null;
}

/**
 * Check if a given object implements the RecordActivityResponseNewBadgesInner interface.
 */
export function instanceOfRecordActivityResponseNewBadgesInner(value: object): value is RecordActivityResponseNewBadgesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    return true;
}

export function RecordActivityResponseNewBadgesInnerFromJSON(json: any): RecordActivityResponseNewBadgesInner {
    return RecordActivityResponseNewBadgesInnerFromJSONTyped(json, false);
}

export function RecordActivityResponseNewBadgesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordActivityResponseNewBadgesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'name': json['name'],
        'icon': json['icon'],
    };
}

export function RecordActivityResponseNewBadgesInnerToJSON(json: any): RecordActivityResponseNewBadgesInner {
    return RecordActivityResponseNewBadgesInnerToJSONTyped(json, false);
}

export function RecordActivityResponseNewBadgesInnerToJSONTyped(value?: RecordActivityResponseNewBadgesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'icon': value['icon'],
    };
}

