/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshResponse
 */
export interface RefreshResponse {
    /**
     * New JWT access token
     * @type {string}
     * @memberof RefreshResponse
     */
    accessToken: string;
    /**
     * New refresh token (rotated)
     * @type {string}
     * @memberof RefreshResponse
     */
    refreshToken: string;
    /**
     * New access token expiration
     * @type {Date}
     * @memberof RefreshResponse
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the RefreshResponse interface.
 */
export function instanceOfRefreshResponse(value: object): value is RefreshResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function RefreshResponseFromJSON(json: any): RefreshResponse {
    return RefreshResponseFromJSONTyped(json, false);
}

export function RefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function RefreshResponseToJSON(json: any): RefreshResponse {
    return RefreshResponseToJSONTyped(json, false);
}

export function RefreshResponseToJSONTyped(value?: RefreshResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'expiresAt': value['expiresAt'].toISOString(),
    };
}

