/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDeviceResponse
 */
export interface RegisterDeviceResponse {
    /**
     * Device token record ID
     * @type {string}
     * @memberof RegisterDeviceResponse
     */
    id: string;
    /**
     * Whether the device was registered successfully
     * @type {boolean}
     * @memberof RegisterDeviceResponse
     */
    registered: boolean;
}

/**
 * Check if a given object implements the RegisterDeviceResponse interface.
 */
export function instanceOfRegisterDeviceResponse(value: object): value is RegisterDeviceResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('registered' in value) || value['registered'] === undefined) return false;
    return true;
}

export function RegisterDeviceResponseFromJSON(json: any): RegisterDeviceResponse {
    return RegisterDeviceResponseFromJSONTyped(json, false);
}

export function RegisterDeviceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDeviceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'registered': json['registered'],
    };
}

export function RegisterDeviceResponseToJSON(json: any): RegisterDeviceResponse {
    return RegisterDeviceResponseToJSONTyped(json, false);
}

export function RegisterDeviceResponseToJSONTyped(value?: RegisterDeviceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'registered': value['registered'],
    };
}

