/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendNotificationRequest
 */
export interface SendNotificationRequest {
    /**
     * Recipient user ID
     * @type {string}
     * @memberof SendNotificationRequest
     */
    userId: string;
    /**
     * Type of notification
     * @type {string}
     * @memberof SendNotificationRequest
     */
    notificationType: string;
    /**
     * Notification title
     * @type {string}
     * @memberof SendNotificationRequest
     */
    title: string;
    /**
     * Notification body
     * @type {string}
     * @memberof SendNotificationRequest
     */
    body?: string;
    /**
     * Icon emoji or name
     * @type {string}
     * @memberof SendNotificationRequest
     */
    icon?: string;
    /**
     * Source type
     * @type {string}
     * @memberof SendNotificationRequest
     */
    sourceType?: string;
    /**
     * Source record ID
     * @type {string}
     * @memberof SendNotificationRequest
     */
    sourceId?: string;
    /**
     * Deep link URL
     * @type {string}
     * @memberof SendNotificationRequest
     */
    actionUrl?: string;
}

/**
 * Check if a given object implements the SendNotificationRequest interface.
 */
export function instanceOfSendNotificationRequest(value: object): value is SendNotificationRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('notificationType' in value) || value['notificationType'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function SendNotificationRequestFromJSON(json: any): SendNotificationRequest {
    return SendNotificationRequestFromJSONTyped(json, false);
}

export function SendNotificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendNotificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'notificationType': json['notificationType'],
        'title': json['title'],
        'body': json['body'] == null ? undefined : json['body'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'sourceType': json['sourceType'] == null ? undefined : json['sourceType'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'actionUrl': json['actionUrl'] == null ? undefined : json['actionUrl'],
    };
}

export function SendNotificationRequestToJSON(json: any): SendNotificationRequest {
    return SendNotificationRequestToJSONTyped(json, false);
}

export function SendNotificationRequestToJSONTyped(value?: SendNotificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'notificationType': value['notificationType'],
        'title': value['title'],
        'body': value['body'],
        'icon': value['icon'],
        'sourceType': value['sourceType'],
        'sourceId': value['sourceId'],
        'actionUrl': value['actionUrl'],
    };
}

