/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * Session ID
     * @type {string}
     * @memberof Session
     */
    id: string;
    /**
     * User agent string
     * @type {string}
     * @memberof Session
     */
    userAgent: string | null;
    /**
     * IP address
     * @type {string}
     * @memberof Session
     */
    ipAddress: string | null;
    /**
     * Session creation timestamp
     * @type {Date}
     * @memberof Session
     */
    createdAt: Date;
    /**
     * Last activity timestamp
     * @type {Date}
     * @memberof Session
     */
    lastUsedAt: Date;
    /**
     * Is this the current session
     * @type {boolean}
     * @memberof Session
     */
    current: boolean;
}

/**
 * Check if a given object implements the Session interface.
 */
export function instanceOfSession(value: object): value is Session {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userAgent' in value) || value['userAgent'] === undefined) return false;
    if (!('ipAddress' in value) || value['ipAddress'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('lastUsedAt' in value) || value['lastUsedAt'] === undefined) return false;
    if (!('current' in value) || value['current'] === undefined) return false;
    return true;
}

export function SessionFromJSON(json: any): Session {
    return SessionFromJSONTyped(json, false);
}

export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userAgent': json['userAgent'],
        'ipAddress': json['ipAddress'],
        'createdAt': (new Date(json['createdAt'])),
        'lastUsedAt': (new Date(json['lastUsedAt'])),
        'current': json['current'],
    };
}

export function SessionToJSON(json: any): Session {
    return SessionToJSONTyped(json, false);
}

export function SessionToJSONTyped(value?: Session | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userAgent': value['userAgent'],
        'ipAddress': value['ipAddress'],
        'createdAt': value['createdAt'].toISOString(),
        'lastUsedAt': value['lastUsedAt'].toISOString(),
        'current': value['current'],
    };
}

