/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Comparison with previous period (if includeComparison=true)
 * @export
 * @interface StatsResponseComparison
 */
export interface StatsResponseComparison {
    /**
     * Total value in previous period
     * @type {number}
     * @memberof StatsResponseComparison
     */
    previousPeriodValue: number;
    /**
     * Percentage change from previous period
     * @type {number}
     * @memberof StatsResponseComparison
     */
    changePercent: number;
}

/**
 * Check if a given object implements the StatsResponseComparison interface.
 */
export function instanceOfStatsResponseComparison(value: object): value is StatsResponseComparison {
    if (!('previousPeriodValue' in value) || value['previousPeriodValue'] === undefined) return false;
    if (!('changePercent' in value) || value['changePercent'] === undefined) return false;
    return true;
}

export function StatsResponseComparisonFromJSON(json: any): StatsResponseComparison {
    return StatsResponseComparisonFromJSONTyped(json, false);
}

export function StatsResponseComparisonFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsResponseComparison {
    if (json == null) {
        return json;
    }
    return {
        
        'previousPeriodValue': json['previousPeriodValue'],
        'changePercent': json['changePercent'],
    };
}

export function StatsResponseComparisonToJSON(json: any): StatsResponseComparison {
    return StatsResponseComparisonToJSONTyped(json, false);
}

export function StatsResponseComparisonToJSONTyped(value?: StatsResponseComparison | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'previousPeriodValue': value['previousPeriodValue'],
        'changePercent': value['changePercent'],
    };
}

