/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Query period
 * @export
 * @interface StatsResponsePeriod
 */
export interface StatsResponsePeriod {
    /**
     * Period start date
     * @type {string}
     * @memberof StatsResponsePeriod
     */
    from: string;
    /**
     * Period end date
     * @type {string}
     * @memberof StatsResponsePeriod
     */
    to: string;
    /**
     * Period label
     * @type {string}
     * @memberof StatsResponsePeriod
     */
    label: string;
}

/**
 * Check if a given object implements the StatsResponsePeriod interface.
 */
export function instanceOfStatsResponsePeriod(value: object): value is StatsResponsePeriod {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function StatsResponsePeriodFromJSON(json: any): StatsResponsePeriod {
    return StatsResponsePeriodFromJSONTyped(json, false);
}

export function StatsResponsePeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatsResponsePeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'label': json['label'],
    };
}

export function StatsResponsePeriodToJSON(json: any): StatsResponsePeriod {
    return StatsResponsePeriodToJSONTyped(json, false);
}

export function StatsResponsePeriodToJSONTyped(value?: StatsResponsePeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
        'label': value['label'],
    };
}

