/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Streak } from './Streak';
import {
    StreakFromJSON,
    StreakFromJSONTyped,
    StreakToJSON,
    StreakToJSONTyped,
} from './Streak';

/**
 * 
 * @export
 * @interface StreakListResponse
 */
export interface StreakListResponse {
    /**
     * List of user streaks
     * @type {Array<Streak>}
     * @memberof StreakListResponse
     */
    streaks: Array<Streak>;
}

/**
 * Check if a given object implements the StreakListResponse interface.
 */
export function instanceOfStreakListResponse(value: object): value is StreakListResponse {
    if (!('streaks' in value) || value['streaks'] === undefined) return false;
    return true;
}

export function StreakListResponseFromJSON(json: any): StreakListResponse {
    return StreakListResponseFromJSONTyped(json, false);
}

export function StreakListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreakListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'streaks': ((json['streaks'] as Array<any>).map(StreakFromJSON)),
    };
}

export function StreakListResponseToJSON(json: any): StreakListResponse {
    return StreakListResponseToJSONTyped(json, false);
}

export function StreakListResponseToJSONTyped(value?: StreakListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'streaks': ((value['streaks'] as Array<any>).map(StreakToJSON)),
    };
}

