/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Streak
 */
export interface Streak {
    /**
     * Streak ID
     * @type {string}
     * @memberof Streak
     */
    id: string;
    /**
     * User ID
     * @type {string}
     * @memberof Streak
     */
    userId: string;
    /**
     * Streak type (global, reading, study, etc.)
     * @type {string}
     * @memberof Streak
     */
    streakType: string;
    /**
     * Current streak count
     * @type {number}
     * @memberof Streak
     */
    currentCount: number;
    /**
     * Longest streak achieved
     * @type {number}
     * @memberof Streak
     */
    longestCount: number;
    /**
     * Date of last activity that counted toward streak
     * @type {string}
     * @memberof Streak
     */
    lastActivityDate: string | null;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof Streak
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Streak interface.
 */
export function instanceOfStreak(value: object): value is Streak {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('streakType' in value) || value['streakType'] === undefined) return false;
    if (!('currentCount' in value) || value['currentCount'] === undefined) return false;
    if (!('longestCount' in value) || value['longestCount'] === undefined) return false;
    if (!('lastActivityDate' in value) || value['lastActivityDate'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function StreakFromJSON(json: any): Streak {
    return StreakFromJSONTyped(json, false);
}

export function StreakFromJSONTyped(json: any, ignoreDiscriminator: boolean): Streak {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'streakType': json['streakType'],
        'currentCount': json['currentCount'],
        'longestCount': json['longestCount'],
        'lastActivityDate': json['lastActivityDate'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function StreakToJSON(json: any): Streak {
    return StreakToJSONTyped(json, false);
}

export function StreakToJSONTyped(value?: Streak | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'streakType': value['streakType'],
        'currentCount': value['currentCount'],
        'longestCount': value['longestCount'],
        'lastActivityDate': value['lastActivityDate'],
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

