/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleReactionResponse
 */
export interface ToggleReactionResponse {
    /**
     * Whether the reaction was added (true) or removed (false)
     * @type {boolean}
     * @memberof ToggleReactionResponse
     */
    added: boolean;
    /**
     * Reaction ID (if added)
     * @type {string}
     * @memberof ToggleReactionResponse
     */
    reactionId?: string;
}

/**
 * Check if a given object implements the ToggleReactionResponse interface.
 */
export function instanceOfToggleReactionResponse(value: object): value is ToggleReactionResponse {
    if (!('added' in value) || value['added'] === undefined) return false;
    return true;
}

export function ToggleReactionResponseFromJSON(json: any): ToggleReactionResponse {
    return ToggleReactionResponseFromJSONTyped(json, false);
}

export function ToggleReactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleReactionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'added': json['added'],
        'reactionId': json['reactionId'] == null ? undefined : json['reactionId'],
    };
}

export function ToggleReactionResponseToJSON(json: any): ToggleReactionResponse {
    return ToggleReactionResponseToJSONTyped(json, false);
}

export function ToggleReactionResponseToJSONTyped(value?: ToggleReactionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'added': value['added'],
        'reactionId': value['reactionId'],
    };
}

