/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePledgeRequest
 */
export interface UpdatePledgeRequest {
    /**
     * Updated status
     * @type {string}
     * @memberof UpdatePledgeRequest
     */
    status?: UpdatePledgeRequestStatusEnum;
    /**
     * Updated amount paid
     * @type {number}
     * @memberof UpdatePledgeRequest
     */
    amountPaid?: number;
}


/**
 * @export
 */
export const UpdatePledgeRequestStatusEnum = {
    ACTIVE: 'active',
    FULFILLED: 'fulfilled',
    CANCELLED: 'cancelled'
} as const;
export type UpdatePledgeRequestStatusEnum = typeof UpdatePledgeRequestStatusEnum[keyof typeof UpdatePledgeRequestStatusEnum];


/**
 * Check if a given object implements the UpdatePledgeRequest interface.
 */
export function instanceOfUpdatePledgeRequest(value: object): value is UpdatePledgeRequest {
    return true;
}

export function UpdatePledgeRequestFromJSON(json: any): UpdatePledgeRequest {
    return UpdatePledgeRequestFromJSONTyped(json, false);
}

export function UpdatePledgeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePledgeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'amountPaid': json['amountPaid'] == null ? undefined : json['amountPaid'],
    };
}

export function UpdatePledgeRequestToJSON(json: any): UpdatePledgeRequest {
    return UpdatePledgeRequestToJSONTyped(json, false);
}

export function UpdatePledgeRequestToJSONTyped(value?: UpdatePledgeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'amountPaid': value['amountPaid'],
    };
}

