/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRewardRequest
 */
export interface UpdateRewardRequest {
    /**
     * Reward name
     * @type {string}
     * @memberof UpdateRewardRequest
     */
    name?: string;
    /**
     * Reward description
     * @type {string}
     * @memberof UpdateRewardRequest
     */
    description?: string | null;
    /**
     * Monetary value
     * @type {number}
     * @memberof UpdateRewardRequest
     */
    monetaryValue?: number | null;
    /**
     * New status
     * @type {string}
     * @memberof UpdateRewardRequest
     */
    status?: UpdateRewardRequestStatusEnum;
}


/**
 * @export
 */
export const UpdateRewardRequestStatusEnum = {
    ACTIVE: 'active',
    FULFILLED: 'fulfilled',
    CANCELLED: 'cancelled'
} as const;
export type UpdateRewardRequestStatusEnum = typeof UpdateRewardRequestStatusEnum[keyof typeof UpdateRewardRequestStatusEnum];


/**
 * Check if a given object implements the UpdateRewardRequest interface.
 */
export function instanceOfUpdateRewardRequest(value: object): value is UpdateRewardRequest {
    return true;
}

export function UpdateRewardRequestFromJSON(json: any): UpdateRewardRequest {
    return UpdateRewardRequestFromJSONTyped(json, false);
}

export function UpdateRewardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRewardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'monetaryValue': json['monetaryValue'] == null ? undefined : json['monetaryValue'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateRewardRequestToJSON(json: any): UpdateRewardRequest {
    return UpdateRewardRequestToJSONTyped(json, false);
}

export function UpdateRewardRequestToJSONTyped(value?: UpdateRewardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'monetaryValue': value['monetaryValue'],
        'status': value['status'],
    };
}

