/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGoalRequest
 */
export interface UpdateGoalRequest {
    /**
     * Updated progress value
     * @type {number}
     * @memberof UpdateGoalRequest
     */
    currentValue?: number;
    /**
     * Updated status
     * @type {string}
     * @memberof UpdateGoalRequest
     */
    status?: UpdateGoalRequestStatusEnum;
}


/**
 * @export
 */
export const UpdateGoalRequestStatusEnum = {
    ACTIVE: 'active',
    COMPLETED: 'completed',
    EXPIRED: 'expired',
    CANCELLED: 'cancelled'
} as const;
export type UpdateGoalRequestStatusEnum = typeof UpdateGoalRequestStatusEnum[keyof typeof UpdateGoalRequestStatusEnum];


/**
 * Check if a given object implements the UpdateGoalRequest interface.
 */
export function instanceOfUpdateGoalRequest(value: object): value is UpdateGoalRequest {
    return true;
}

export function UpdateGoalRequestFromJSON(json: any): UpdateGoalRequest {
    return UpdateGoalRequestFromJSONTyped(json, false);
}

export function UpdateGoalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGoalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentValue': json['currentValue'] == null ? undefined : json['currentValue'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateGoalRequestToJSON(json: any): UpdateGoalRequest {
    return UpdateGoalRequestToJSONTyped(json, false);
}

export function UpdateGoalRequestToJSONTyped(value?: UpdateGoalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentValue': value['currentValue'],
        'status': value['status'],
    };
}

