/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGroupRequest
 */
export interface UpdateGroupRequest {
    /**
     * Group display name
     * @type {string}
     * @memberof UpdateGroupRequest
     */
    name?: string;
    /**
     * Group description
     * @type {string}
     * @memberof UpdateGroupRequest
     */
    description?: string;
    /**
     * Flexible metadata
     * @type {{ [key: string]: any | null; }}
     * @memberof UpdateGroupRequest
     */
    metadata?: { [key: string]: any | null; };
    /**
     * Whether the group is discoverable
     * @type {boolean}
     * @memberof UpdateGroupRequest
     */
    isPublic?: boolean;
    /**
     * Whether the group is active
     * @type {boolean}
     * @memberof UpdateGroupRequest
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the UpdateGroupRequest interface.
 */
export function instanceOfUpdateGroupRequest(value: object): value is UpdateGroupRequest {
    return true;
}

export function UpdateGroupRequestFromJSON(json: any): UpdateGroupRequest {
    return UpdateGroupRequestFromJSONTyped(json, false);
}

export function UpdateGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function UpdateGroupRequestToJSON(json: any): UpdateGroupRequest {
    return UpdateGroupRequestToJSONTyped(json, false);
}

export function UpdateGroupRequestToJSONTyped(value?: UpdateGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'metadata': value['metadata'],
        'isPublic': value['isPublic'],
        'isActive': value['isActive'],
    };
}

