/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMemberRequest
 */
export interface UpdateMemberRequest {
    /**
     * Role within group
     * @type {string}
     * @memberof UpdateMemberRequest
     */
    role?: UpdateMemberRequestRoleEnum;
    /**
     * Membership status
     * @type {string}
     * @memberof UpdateMemberRequest
     */
    status?: UpdateMemberRequestStatusEnum;
    /**
     * Role-specific metadata
     * @type {{ [key: string]: any | null; }}
     * @memberof UpdateMemberRequest
     */
    metadata?: { [key: string]: any | null; };
}


/**
 * @export
 */
export const UpdateMemberRequestRoleEnum = {
    MEMBER: 'member',
    ADMIN: 'admin',
    OWNER: 'owner'
} as const;
export type UpdateMemberRequestRoleEnum = typeof UpdateMemberRequestRoleEnum[keyof typeof UpdateMemberRequestRoleEnum];

/**
 * @export
 */
export const UpdateMemberRequestStatusEnum = {
    ACTIVE: 'active',
    PENDING: 'pending',
    REJECTED: 'rejected'
} as const;
export type UpdateMemberRequestStatusEnum = typeof UpdateMemberRequestStatusEnum[keyof typeof UpdateMemberRequestStatusEnum];


/**
 * Check if a given object implements the UpdateMemberRequest interface.
 */
export function instanceOfUpdateMemberRequest(value: object): value is UpdateMemberRequest {
    return true;
}

export function UpdateMemberRequestFromJSON(json: any): UpdateMemberRequest {
    return UpdateMemberRequestFromJSONTyped(json, false);
}

export function UpdateMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
        'status': json['status'] == null ? undefined : json['status'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateMemberRequestToJSON(json: any): UpdateMemberRequest {
    return UpdateMemberRequestToJSONTyped(json, false);
}

export function UpdateMemberRequestToJSONTyped(value?: UpdateMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'status': value['status'],
        'metadata': value['metadata'],
    };
}

