/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadUrlResponse
 */
export interface UploadUrlResponse {
    /**
     * Pre-signed URL for uploading
     * @type {string}
     * @memberof UploadUrlResponse
     */
    uploadUrl: string;
    /**
     * Public URL where the object will be accessible after upload
     * @type {string}
     * @memberof UploadUrlResponse
     */
    publicUrl: string;
    /**
     * Upload URL expiration timestamp
     * @type {Date}
     * @memberof UploadUrlResponse
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the UploadUrlResponse interface.
 */
export function instanceOfUploadUrlResponse(value: object): value is UploadUrlResponse {
    if (!('uploadUrl' in value) || value['uploadUrl'] === undefined) return false;
    if (!('publicUrl' in value) || value['publicUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function UploadUrlResponseFromJSON(json: any): UploadUrlResponse {
    return UploadUrlResponseFromJSONTyped(json, false);
}

export function UploadUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadUrl': json['uploadUrl'],
        'publicUrl': json['publicUrl'],
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function UploadUrlResponseToJSON(json: any): UploadUrlResponse {
    return UploadUrlResponseToJSONTyped(json, false);
}

export function UploadUrlResponseToJSONTyped(value?: UploadUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploadUrl': value['uploadUrl'],
        'publicUrl': value['publicUrl'],
        'expiresAt': value['expiresAt'].toISOString(),
    };
}

