/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeaderboardResponseGroup } from './LeaderboardResponseGroup';
import {
    LeaderboardResponseGroupFromJSON,
    LeaderboardResponseGroupFromJSONTyped,
    LeaderboardResponseGroupToJSON,
    LeaderboardResponseGroupToJSONTyped,
} from './LeaderboardResponseGroup';

/**
 * 
 * @export
 * @interface UserLeaderboard
 */
export interface UserLeaderboard {
    /**
     * 
     * @type {LeaderboardResponseGroup}
     * @memberof UserLeaderboard
     */
    group: LeaderboardResponseGroup;
    /**
     * User rank in this group
     * @type {number}
     * @memberof UserLeaderboard
     */
    rank: number;
    /**
     * Total members in the group
     * @type {number}
     * @memberof UserLeaderboard
     */
    totalMembers: number;
    /**
     * User XP
     * @type {number}
     * @memberof UserLeaderboard
     */
    xp: number;
}

/**
 * Check if a given object implements the UserLeaderboard interface.
 */
export function instanceOfUserLeaderboard(value: object): value is UserLeaderboard {
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('totalMembers' in value) || value['totalMembers'] === undefined) return false;
    if (!('xp' in value) || value['xp'] === undefined) return false;
    return true;
}

export function UserLeaderboardFromJSON(json: any): UserLeaderboard {
    return UserLeaderboardFromJSONTyped(json, false);
}

export function UserLeaderboardFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLeaderboard {
    if (json == null) {
        return json;
    }
    return {
        
        'group': LeaderboardResponseGroupFromJSON(json['group']),
        'rank': json['rank'],
        'totalMembers': json['totalMembers'],
        'xp': json['xp'],
    };
}

export function UserLeaderboardToJSON(json: any): UserLeaderboard {
    return UserLeaderboardToJSONTyped(json, false);
}

export function UserLeaderboardToJSONTyped(value?: UserLeaderboard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': LeaderboardResponseGroupToJSON(value['group']),
        'rank': value['rank'],
        'totalMembers': value['totalMembers'],
        'xp': value['xp'],
    };
}

