/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserLeaderboard } from './UserLeaderboard';
import {
    UserLeaderboardFromJSON,
    UserLeaderboardFromJSONTyped,
    UserLeaderboardToJSON,
    UserLeaderboardToJSONTyped,
} from './UserLeaderboard';

/**
 * 
 * @export
 * @interface UserLeaderboardsResponse
 */
export interface UserLeaderboardsResponse {
    /**
     * User rankings across all their groups
     * @type {Array<UserLeaderboard>}
     * @memberof UserLeaderboardsResponse
     */
    leaderboards: Array<UserLeaderboard>;
}

/**
 * Check if a given object implements the UserLeaderboardsResponse interface.
 */
export function instanceOfUserLeaderboardsResponse(value: object): value is UserLeaderboardsResponse {
    if (!('leaderboards' in value) || value['leaderboards'] === undefined) return false;
    return true;
}

export function UserLeaderboardsResponseFromJSON(json: any): UserLeaderboardsResponse {
    return UserLeaderboardsResponseFromJSONTyped(json, false);
}

export function UserLeaderboardsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLeaderboardsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'leaderboards': ((json['leaderboards'] as Array<any>).map(UserLeaderboardFromJSON)),
    };
}

export function UserLeaderboardsResponseToJSON(json: any): UserLeaderboardsResponse {
    return UserLeaderboardsResponseToJSONTyped(json, false);
}

export function UserLeaderboardsResponseToJSONTyped(value?: UserLeaderboardsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'leaderboards': ((value['leaderboards'] as Array<any>).map(UserLeaderboardToJSON)),
    };
}

