/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Badge } from './Badge';
import {
    BadgeFromJSON,
    BadgeFromJSONTyped,
    BadgeToJSON,
    BadgeToJSONTyped,
} from './Badge';

/**
 * 
 * @export
 * @interface UserBadge
 */
export interface UserBadge {
    /**
     * User badge record ID
     * @type {string}
     * @memberof UserBadge
     */
    id: string;
    /**
     * User ID
     * @type {string}
     * @memberof UserBadge
     */
    userId: string;
    /**
     * Badge details
     * @type {Badge}
     * @memberof UserBadge
     */
    badge: Badge;
    /**
     * When the badge was earned
     * @type {Date}
     * @memberof UserBadge
     */
    earnedAt: Date;
    /**
     * Context about how badge was earned
     * @type {{ [key: string]: any | null; }}
     * @memberof UserBadge
     */
    metadata?: { [key: string]: any | null; };
}

/**
 * Check if a given object implements the UserBadge interface.
 */
export function instanceOfUserBadge(value: object): value is UserBadge {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('badge' in value) || value['badge'] === undefined) return false;
    if (!('earnedAt' in value) || value['earnedAt'] === undefined) return false;
    return true;
}

export function UserBadgeFromJSON(json: any): UserBadge {
    return UserBadgeFromJSONTyped(json, false);
}

export function UserBadgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBadge {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'badge': BadgeFromJSON(json['badge']),
        'earnedAt': (new Date(json['earnedAt'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UserBadgeToJSON(json: any): UserBadge {
    return UserBadgeToJSONTyped(json, false);
}

export function UserBadgeToJSONTyped(value?: UserBadge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'badge': BadgeToJSON(value['badge']),
        'earnedAt': value['earnedAt'].toISOString(),
        'metadata': value['metadata'],
    };
}

