/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroup } from './UserGroup';
import {
    UserGroupFromJSON,
    UserGroupFromJSONTyped,
    UserGroupToJSON,
    UserGroupToJSONTyped,
} from './UserGroup';

/**
 * 
 * @export
 * @interface UserGroupsResponse
 */
export interface UserGroupsResponse {
    /**
     * List of groups the user belongs to
     * @type {Array<UserGroup>}
     * @memberof UserGroupsResponse
     */
    groups: Array<UserGroup>;
}

/**
 * Check if a given object implements the UserGroupsResponse interface.
 */
export function instanceOfUserGroupsResponse(value: object): value is UserGroupsResponse {
    if (!('groups' in value) || value['groups'] === undefined) return false;
    return true;
}

export function UserGroupsResponseFromJSON(json: any): UserGroupsResponse {
    return UserGroupsResponseFromJSONTyped(json, false);
}

export function UserGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'groups': ((json['groups'] as Array<any>).map(UserGroupFromJSON)),
    };
}

export function UserGroupsResponseToJSON(json: any): UserGroupsResponse {
    return UserGroupsResponseToJSONTyped(json, false);
}

export function UserGroupsResponseToJSONTyped(value?: UserGroupsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groups': ((value['groups'] as Array<any>).map(UserGroupToJSON)),
    };
}

