/* tslint:disable */
/* eslint-disable */
/**
 * BriskStack Platform API
 * Unified platform service for BriskStack ventures. Provides authentication, storage, AI gateway, and activity tracking.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoUploadRequest
 */
export interface VideoUploadRequest {
    /**
     * Video filename for reference
     * @type {string}
     * @memberof VideoUploadRequest
     */
    name?: string;
    /**
     * Maximum video duration in seconds (default: 5 minutes, max: 6 hours)
     * @type {number}
     * @memberof VideoUploadRequest
     */
    maxDurationSeconds?: number;
    /**
     * Require signed URLs for playback
     * @type {boolean}
     * @memberof VideoUploadRequest
     */
    requireSignedUrls?: boolean;
    /**
     * Allowed origins for playback
     * @type {Array<string>}
     * @memberof VideoUploadRequest
     */
    allowedOrigins?: Array<string>;
    /**
     * Custom metadata for the video
     * @type {{ [key: string]: string; }}
     * @memberof VideoUploadRequest
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the VideoUploadRequest interface.
 */
export function instanceOfVideoUploadRequest(value: object): value is VideoUploadRequest {
    return true;
}

export function VideoUploadRequestFromJSON(json: any): VideoUploadRequest {
    return VideoUploadRequestFromJSONTyped(json, false);
}

export function VideoUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'maxDurationSeconds': json['maxDurationSeconds'] == null ? undefined : json['maxDurationSeconds'],
        'requireSignedUrls': json['requireSignedUrls'] == null ? undefined : json['requireSignedUrls'],
        'allowedOrigins': json['allowedOrigins'] == null ? undefined : json['allowedOrigins'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function VideoUploadRequestToJSON(json: any): VideoUploadRequest {
    return VideoUploadRequestToJSONTyped(json, false);
}

export function VideoUploadRequestToJSONTyped(value?: VideoUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'maxDurationSeconds': value['maxDurationSeconds'],
        'requireSignedUrls': value['requireSignedUrls'],
        'allowedOrigins': value['allowedOrigins'],
        'metadata': value['metadata'],
    };
}

